


/*    =============    Elemental Champions    =============    */

	"aquosia_alpha" => array(
		"name" => "Aquosia",
		"type" => "monster",
		"form" => "Alpha",
		"faction" => "Elemental Champions",
		"agenda" => "Protectors",
		"energyType" => "Elemental",
		"set" => "Now",
		"rarity" => 3,
		"speed" => 6,
		"defense" => 6,
		"brawl" => 7,
		"brawlBoost" => 2,
		"blast" => 6,
		"blastBoost" => 2,
		"blastRange" => "short",
		"power" => 7,
		"powerBoost" => 2,
		"health" => 5,
		"hyper" => 0,
		"abilities" => array(
			"Extinguish" => array(),
			"Transport" => array(),
			"Energy Cycle" => array(),
			"Quick" => array("color" => "red",),)
	),
  
	"aquosia_ultra" => array(
		"name" => "Aquosia",
		"type" => "monster",
		"form" => "Ultra",
		"faction" => "Elemental Champions",
		"agenda" => "Protectors",
		"energyType" => "Elemental",
		"set" => "Now",
		"rarity" => 3,
		"speed" => 6,
		"defense" => 6,
		"brawl" => 8,
		"brawlBoost" => 3,
		"blast" => 7,
		"blastBoost" => 3,
		"blastRange" => "short",
		"power" => 8,
		"powerBoost" => 3,
		"health" => 5,
		"hyper" => 5,
		"abilities" => array(
			"Extinguish" => array(),
			"Transport" => array(),
			"All Terrain" => array("color" => "blue", ),
			"Annihilate" => array(),
			"Quick" => array(),)
	),
  
	"aquosia_mega" => array(
		"name" => "Aquosia",
		"type" => "monster",
		"form" => "Mega",
		"faction" => "Elemental Champions",
		"agenda" => "Protectors",
		"energyType" => "Elemental",
		"set" => "Now",
		"setColor" => "blue",
		"rarity" => 4,
		"speed" => 7,
		"defense" => 5,
		"brawl" => 7,
		"brawlBoost" => 3,
		"blast" => 8,
		"blastBoost" => 3,
		"blastRange" => "long",
		"power" => 7,
		"powerBoost" => 2,
		"health" => 6,
		"hyper" => 4,
		"abilities" => array(
			"Extinguish" => array(),
			"Transport" => array(),
			"Crunch" => array("trigger" => "brawl", ),
			"Weapon Master" => array("trigger" => "blast", ),
			"Overload" => array("trigger" => "power", ),
			"Jump_short" => array(),)
	),
  
	"hurricanus_alpha" => array(
		"name" => "Hurricanus",
		"type" => "monster",
		"form" => "Alpha",
		"faction" => "Elemental Champions",
		"agenda" => "Protectors",
		"energyType" => "Elemental",
		"set" => "Big in Japan",
		"rarity" => 3,
		"speed" => 7,
		"defense" => 6,
		"brawl" => 5,
		"brawlBoost" => 1,
		"blast" => 8,
		"blastBoost" => 3,
		"blastRange" => "long",
		"power" => 5,
		"powerBoost" => 2,
		"health" => 5,
		"hyper" => 0,
		"abilities" => array(
			"Extinguish" => array(),
			"Energy Drain" => array("trigger" => "blast", ),
			"Flight" => array(),
			"Hasten" => array("color" => "red",),
			"Weaken" => array(),)
	),
  
	"hurricanus_ultra" => array(
		"name" => "Hurricanus",
		"type" => "monster",
		"form" => "Ultra",
		"faction" => "Elemental Champions",
		"agenda" => "Protectors",
		"energyType" => "Elemental",
		"set" => "Big in Japan",
		"rarity" => 3,
		"speed" => 7,
		"defense" => 7,
		"brawl" => 7,
		"brawlBoost" => 1,
		"blast" => 9,
		"blastBoost" => 3,
		"blastRange" => "long",
		"power" => 6,
		"powerBoost" => 3,
		"health" => 5,
		"hyper" => 4,
		"abilities" => array(
			"Extinguish" => array(),
			"Lightning Attack" => array("trigger" => "blast", ),
			"Flight_short" => array(),
			"Hasten" => array("color" => "blue", ),
			"Quick" => array(),
			"Weaken" => array(),)
	),
  
	"hurricanus_mega" => array(
		"name" => "Hurricanus",
		"type" => "monster",
		"form" => "Mega",
		"faction" => "Elemental Champions",
		"agenda" => "Protectors",
		"energyType" => "Elemental",
		"set" => "Big in Japan",
		"setColor" => "blue",
		"rarity" => 4,
		"speed" => 8,
		"defense" => 7,
		"brawl" => 6,
		"brawlBoost" => 2,
		"blast" => 8,
		"blastBoost" => 3,
		"blastRange" => "short",
		"power" => 7,
		"powerBoost" => 2,
		"health" => 5,
		"hyper" => 3,
		"abilities" => array(
			"Telekinesis" => array(),
			"Power Strike" => array("trigger" => "blast", ),
			"Toss" => array("trigger" => "blast", ),
			"Flight_short" => array(),
			"Hasten" => array("color" => "blue", ),)
	),
  
	"incinerus_alpha" => array(
		"name" => "Incinerus",
		"type" => "monster",
		"form" => "Alpha",
		"faction" => "Elemental Champions",
		"agenda" => "Protectors",
		"energyType" => "Elemental",
		"set" => "Now",
		"rarity" => 3,
		"speed" => 8,
		"defense" => 6,
		"brawl" => 5,
		"brawlBoost" => 1,
		"blast" => 6,
		"blastBoost" => 3,
		"blastRange" => "long",
		"power" => 6,
		"powerBoost" => 1,
		"health" => 5,
		"hyper" => 0,
		"abilities" => array(
			"Ignite" => array(),
			"Chain Reaction" => array("trigger" => "blast", ),
			"Siphon" => array("trigger" => "blast", ),
			"Fireproof" => array(),
			"Flight_short" => array(),)
	),
  
	"incinerus_ultra" => array(
		"name" => "Incinerus",
		"type" => "monster",
		"form" => "Ultra",
		"faction" => "Elemental Champions",
		"agenda" => "Protectors",
		"energyType" => "Elemental",
		"set" => "Now",
		"rarity" => 3,
		"speed" => 7,
		"defense" => 6,
		"brawl" => 6,
		"brawlBoost" => 2,
		"blast" => 7,
		"blastBoost" => 4,
		"blastRange" => "long",
		"power" => 7,
		"powerBoost" => 2,
		"health" => 5,
		"hyper" => 4,
		"abilities" => array(
			"Ignite_short" => array(),
			"Explosion" => array("trigger" => "blast", ),
			"Radial Attack_short" => array("trigger" => "blast", ),
			"Fireproof" => array(),
			"Flight_short" => array(),
			"Hazardous" => array("color" => "red",),)
	),
  
	"incinerus_mega" => array(
		"name" => "Incinerus",
		"type" => "monster",
		"form" => "Mega",
		"faction" => "Elemental Champions",
		"agenda" => "Protectors",
		"energyType" => "Elemental",
		"set" => "Now",
		"setColor" => "blue",
		"rarity" => 4,
		"speed" => 8,
		"defense" => 5,
		"brawl" => 7,
		"brawlBoost" => 2,
		"blast" => 8,
		"blastBoost" => 3,
		"blastRange" => "long",
		"power" => 6,
		"powerBoost" => 3,
		"health" => 6,
		"hyper" => 5,
		"abilities" => array(
			"Ignite_short" => array(),
			"Multi-shot_short" => array("trigger" => "blast", ),
			"Siphon" => array("trigger" => "blast", ),
			"Fireproof" => array(),
			"Flight_short" => array(),
			"Volatile_short" => array(),)
	),
  
	"tectomoc_alpha" => array(
		"name" => "Tectomoc",
		"type" => "monster",
		"form" => "Alpha",
		"faction" => "Elemental Champions",
		"agenda" => "Protectors",
		"energyType" => "Elemental",
		"set" => "Big in Japan",
		"rarity" => 3,
		"speed" => 5,
		"defense" => 5,
		"brawl" => 7,
		"brawlBoost" => 3,
		"power" => 7,
		"powerBoost" => 2,
		"health" => 7,
		"hyper" => 0,
		"abilities" => array(
			"Beat Back" => array("trigger" => "brawl", ),
			"Power Gorge" => array("trigger" => "brawl", ),
			"Steady" => array(),)
	),
  
	"tectomoc_ultra" => array(
		"name" => "Tectomoc",
		"type" => "monster",
		"form" => "Ultra",
		"faction" => "Elemental Champions",
		"agenda" => "Protectors",
		"energyType" => "Elemental",
		"set" => "Big in Japan",
		"rarity" => 3,
		"speed" => 5,
		"defense" => 5,
		"brawl" => 9,
		"brawlBoost" => 4,
		"power" => 8,
		"powerBoost" => 3,
		"health" => 5,
		"hyper" => 3,
		"abilities" => array(
			"Chain Attack" => array("trigger" => "brawl", ),
			"Power Drain" => array("trigger" => "brawl", ),
			"Burrow" => array(),
			"Tenacious" => array(),)
	),
  
	"tectomoc_mega" => array(
		"name" => "Tectomoc",
		"type" => "monster",
		"form" => "Mega",
		"faction" => "Elemental Champions",
		"agenda" => "Protectors",
		"energyType" => "Elemental",
		"set" => "Big in Japan",
		"setColor" => "blue",
		"rarity" => 4,
		"speed" => 6,
		"defense" => 6,
		"brawl" => 6,
		"brawlBoost" => 3,
		"power" => 6,
		"powerBoost" => 4,
		"health" => 6,
		"hyper" => 4,
		"abilities" => array(
			"Rage" => array(),
			"Crunch" => array("trigger" => "power", ),
			"Burrow" => array(),
			"Massive" => array(),)
	),
  
	"tornadus" => array(
		"name" => "Tornadus",
		"type" => "character",
		"form" => "Air Kami",
		"class" => "Elite",
		"faction" => "Elemental Champions",
		"agenda" => "Protectors",
		"energyType" => "Elemental",
		"set" => "Big in Japan",
		"rarity" => 4,
		"speed" => 7,
		"defense" => 3,
		"brawl" => 2,
		"brawlBoost" => 2,
		"blast" => 2,
		"blastBoost" => 2,
		"blastRange" => "short",
		"cost" => 2,
		"abilities" => array(
			"Hoist" => array("color" => "red",),
			"Fling" => array("trigger" => "blast", ),
			"Flight" => array(),
			"Limited" => array(),)
	),
  
	"air_kami_grunt" => array(
		"name" => "Air Kami",
		"type" => "unit",
		"class" => "Grunt",
		"faction" => "Elemental Champions",
		"agenda" => "Protectors",
		"energyType" => "Elemental",
		"set" => "Big in Japan",
		"rarity" => 1,
		"speed" => 5,
		"defense" => 3,
		"brawl" => 2,
		"blast" => 1,
		"blastRange" => "short",
		"cost" => 1,
		"abilities" => array(
			"Distract" => array(),
			"Flight" => array(),
			"Lift" => array(),)
	),
  
	"air_kami_elite" => array(
		"name" => "Air Kami",
		"type" => "unit",
		"class" => "Elite",
		"faction" => "Elemental Champions",
		"agenda" => "Protectors",
		"energyType" => "Elemental",
		"set" => "Big in Japan",
		"rarity" => 3,
		"speed" => 5,
		"defense" => 3,
		"brawl" => 2,
		"brawlBoost" => 1,
		"blast" => 1,
		"blastBoost" => 1,
		"blastRange" => "short",
		"cost" => 2,
		"abilities" => array(
			"Distract" => array("color" => "red",),
			"Flight" => array(),
			"Leadership" => array(),
			"Lift" => array(),)
	),
  
	"earth_avatar_grunt" => array(
		"name" => "Earth Avatar",
		"type" => "unit",
		"class" => "Grunt",
		"faction" => "Elemental Champions",
		"agenda" => "Protectors",
		"energyType" => "Elemental",
		"set" => "Now",
		"rarity" => 2,
		"speed" => 4,
		"defense" => 4,
		"brawl" => 2,
		"cost" => 2,
		"abilities" => array(
			"Nesting" => array(),
			"Amplify" => array(),
			"Countermeasures" => array(),)
	),
  
	"earth_avatar_glass" => array(
		"name" => "Earth Avatar",
		"type" => "unit",
		"form" => "Glass",
		"class" => "Grunt",
		"faction" => "Elemental Champions",
		"agenda" => "Protectors",
		"energyType" => "Elemental",
		"set" => "Now",
		"setColor" => "blue",
		"rarity" => 4,
		"speed" => 5,
		"defense" => 4,
		"brawl" => 2,
		"cost" => 1,
		"abilities" => array(
			"Nesting" => array(),
			"Burrow" => array(),
			"Fragile" => array(),)
	),
  
	"earth_kami_grunt" => array(
		"name" => "Earth Kami",
		"type" => "unit",
		"class" => "Grunt",
		"faction" => "Elemental Champions",
		"agenda" => "Protectors",
		"energyType" => "Elemental",
		"set" => "Big in Japan",
		"rarity" => 1,
		"speed" => 5,
		"defense" => 4,
		"brawl" => 2,
		"brawlBoost" => 1,
		"cost" => 1,
		"abilities" => array(
			"Fling" => array("trigger" => "brawl", ),
			"Burrow" => array(),)
	),
  
	"earth_kami_elite" => array(
		"name" => "Earth Kami",
		"type" => "unit",
		"class" => "Elite",
		"faction" => "Elemental Champions",
		"agenda" => "Protectors",
		"energyType" => "Elemental",
		"set" => "Big in Japan",
		"rarity" => 2,
		"speed" => 5,
		"defense" => 4,
		"brawl" => 2,
		"brawlBoost" => 2,
		"cost" => 2,
		"abilities" => array(
			"Fling" => array("trigger" => "brawl", ),
			"Burrow" => array(),
			"Leadership" => array(),)
	),
  
	"earth_kami_glass" => array(
		"name" => "Earth Kami",
		"type" => "unit",
		"form" => "Glass",
		"class" => "Grunt",
		"faction" => "Elemental Champions",
		"agenda" => "Protectors",
		"energyType" => "Elemental",
		"set" => "Big in Japan",
		"setColor" => "blue",
		"rarity" => 4,
		"speed" => 5,
		"defense" => 4,
		"brawl" => 2,
		"brawlBoost" => 1,
		"blast" => 1,
		"blastRange" => "long",
		"cost" => 1,
		"abilities" => array(
			"Multi-shot" => array("trigger" => "brawl", ),
			"Burrow" => array(),
			"Fragile" => array(),
			"Safeguard" => array(),)
	),
  
	"fire_kami_grunt" => array(
		"name" => "Fire Kami",
		"type" => "unit",
		"class" => "Grunt",
		"faction" => "Elemental Champions",
		"agenda" => "Protectors",
		"energyType" => "Elemental",
		"set" => "Now",
		"rarity" => 1,
		"speed" => 6,
		"defense" => 3,
		"brawl" => 1,
		"blast" => 1,
		"blastBoost" => 1,
		"blastRange" => "short",
		"cost" => 1,
		"abilities" => array(
			"Ignite" => array(),
			"Rage" => array(),)
	),
  
	"fire_kami_elite" => array(
		"name" => "Fire Kami",
		"type" => "unit",
		"class" => "Elite",
		"faction" => "Elemental Champions",
		"agenda" => "Protectors",
		"energyType" => "Elemental",
		"set" => "Now",
		"rarity" => 3,
		"speed" => 6,
		"defense" => 3,
		"brawl" => 1,
		"brawlBoost" => 1,
		"blast" => 1,
		"blastBoost" => 2,
		"blastRange" => "short",
		"cost" => 2,
		"abilities" => array(
			"Ignite" => array(),
			"Rage" => array(),
			"Leadership" => array(),)
	),
  
	"water_avatar_grunt" => array(
		"name" => "Water Avatar",
		"type" => "unit",
		"class" => "Grunt",
		"faction" => "Elemental Champions",
		"agenda" => "Protectors",
		"energyType" => "Elemental",
		"set" => "Now",
		"rarity" => 2,
		"speed" => 7,
		"defense" => 2,
		"cost" => 1,
		"abilities" => array(
			"Transport" => array(),
			"Drain Life" => array("color" => "red",),
			"Hover" => array(),
			"Power Tap" => array(),)
	),
  
	"water_kami_grunt" => array(
		"name" => "Water Kami",
		"type" => "unit",
		"class" => "Grunt",
		"faction" => "Elemental Champions",
		"agenda" => "Protectors",
		"energyType" => "Elemental",
		"set" => "Now",
		"rarity" => 1,
		"speed" => 4,
		"defense" => 3,
		"brawl" => 1,
		"brawlBoost" => 1,
		"blast" => 1,
		"blastRange" => "short",
		"cost" => 1,
		"abilities" => array(
			"Amphibious" => array(),
			"Cargo" => array(),
			"Flank" => array(),)
	),
  
	"water_kami_elite" => array(
		"name" => "Water Kami",
		"type" => "unit",
		"class" => "Elite",
		"faction" => "Elemental Champions",
		"agenda" => "Protectors",
		"energyType" => "Elemental",
		"set" => "Now",
		"rarity" => 3,
		"speed" => 4,
		"defense" => 3,
		"brawl" => 1,
		"brawlBoost" => 2,
		"blast" => 1,
		"blastBoost" => 1,
		"blastRange" => "short",
		"cost" => 2,
		"abilities" => array(
			"Amphibious" => array(),
			"Cargo" => array(),
			"Flank" => array(),
			"Leadership" => array(),)
	),
