


/*    =============    Empire of the Apes    =============    */

	"gakura_alpha" => array(
		"name" => "Gakura",
		"type" => "monster",
		"form" => "Alpha",
		"faction" => "Empire of the Apes",
		"agenda" => "Radicals",
		"energyType" => "Nature",
		"set" => "Now",
		"rarity" => 3,
		"speed" => 6,
		"defense" => 6,
		"brawl" => 6,
		"brawlBoost" => 3,
		"power" => 6,
		"powerBoost" => 2,
		"health" => 6,
		"hyper" => 0,
		"abilities" => array(
			"Blitz" => array("trigger" => "brawl", ),
			"Demolish" => array("trigger" => "brawl", ),
			"Berserk" => array("color" => "blue", ),
			"Jump_short" => array(),
			"Super Stomp" => array(),)
	),
  
	"gakura_ultra" => array(
		"name" => "Gakura",
		"type" => "monster",
		"form" => "Ultra",
		"faction" => "Empire of the Apes",
		"agenda" => "Radicals",
		"energyType" => "Nature",
		"set" => "Now",
		"rarity" => 3,
		"speed" => 6,
		"defense" => 6,
		"brawl" => 8,
		"brawlBoost" => 4,
		"power" => 7,
		"powerBoost" => 3,
		"health" => 6,
		"hyper" => 4,
		"abilities" => array(
			"Energy Drain" => array("trigger" => "brawl", ),
			"Lightning Attack" => array("trigger" => "brawl", ),
			"Power Drain" => array("trigger" => "brawl", ),
			"Berserk" => array("color" => "blue", ),
			"Jump" => array(),)
	),
  
	"gakura_mega" => array(
		"name" => "Gakura",
		"type" => "monster",
		"form" => "Mega",
		"faction" => "Empire of the Apes",
		"agenda" => "Radicals",
		"energyType" => "Nature",
		"set" => "Now",
		"setColor" => "blue",
		"rarity" => 4,
		"speed" => 6,
		"defense" => 7,
		"brawl" => 7,
		"brawlBoost" => 3,
		"power" => 7,
		"powerBoost" => 3,
		"health" => 5,
		"hyper" => 3,
		"abilities" => array(
			"Beat Back" => array("trigger" => "brawl", ),
			"Jump" => array(),
			"Motivator" => array(),
			"Resilience" => array(),)
	),
  
	"general_hondo_alpha" => array(
		"name" => "General Hondo",
		"type" => "monster",
		"form" => "Alpha",
		"faction" => "Empire of the Apes",
		"agenda" => "Radicals",
		"energyType" => "Nature",
		"set" => "Big in Japan",
		"rarity" => 3,
		"speed" => 6,
		"defense" => 5,
		"brawl" => 7,
		"brawlBoost" => 2,
		"power" => 7,
		"powerBoost" => 2,
		"health" => 5,
		"hyper" => 0,
		"abilities" => array(
			"Follow Through" => array("trigger" => "brawl", ),
			"Armored" => array(),
			"Force Field" => array("color" => "blue", ),
			"Riled" => array(),
			"Shock Wave" => array(),)
	),
  
	"general_hondo_ultra" => array(
		"name" => "General Hondo",
		"type" => "monster",
		"form" => "Ultra",
		"faction" => "Empire of the Apes",
		"agenda" => "Radicals",
		"energyType" => "Nature",
		"set" => "Big in Japan",
		"rarity" => 3,
		"speed" => 6,
		"defense" => 5,
		"brawl" => 8,
		"brawlBoost" => 3,
		"power" => 8,
		"powerBoost" => 3,
		"health" => 5,
		"hyper" => 4,
		"abilities" => array(
			"Chain Attack" => array("trigger" => "brawl", ),
			"Power Gorge" => array("trigger" => "brawl", ),
			"Armored" => array(),
			"Force Field" => array("color" => "blue", ),
			"Juggernaut_short" => array(),
			"Shock Wave" => array(),)
	),
  
	"general_hondo_mega" => array(
		"name" => "General Hondo",
		"type" => "monster",
		"form" => "Mega",
		"faction" => "Empire of the Apes",
		"agenda" => "Radicals",
		"energyType" => "Nature",
		"set" => "Big in Japan",
		"setColor" => "blue",
		"rarity" => 4,
		"speed" => 5,
		"defense" => 6,
		"brawl" => 8,
		"brawlBoost" => 2,
		"power" => 8,
		"powerBoost" => 4,
		"health" => 5,
		"hyper" => 4,
		"abilities" => array(
			"Power Gorge" => array("trigger" => "power", ),
			"Riot" => array("trigger" => "power", ),
			"Armored" => array(),
			"Force Field" => array("color" => "blue", ),
			"Shock Wave" => array(),)
	),
  
	"king_kondo_alpha" => array(
		"name" => "King Kondo",
		"type" => "monster",
		"form" => "Alpha",
		"faction" => "Empire of the Apes",
		"agenda" => "Radicals",
		"energyType" => "Nature",
		"set" => "Now",
		"rarity" => 3,
		"speed" => 6,
		"defense" => 5,
		"brawl" => 6,
		"brawlBoost" => 3,
		"power" => 6,
		"powerBoost" => 2,
		"health" => 6,
		"hyper" => 0,
		"abilities" => array(
			"Riot" => array("trigger" => "brawl", ),
			"Berserk" => array("color" => "blue", ),
			"Jump" => array(),
			"Motivator" => array(),
			"Super Swat" => array(),)
	),
  
	"king_kondo_ultra" => array(
		"name" => "King Kondo",
		"type" => "monster",
		"form" => "Ultra",
		"faction" => "Empire of the Apes",
		"agenda" => "Radicals",
		"energyType" => "Nature",
		"set" => "Now",
		"rarity" => 3,
		"speed" => 6,
		"defense" => 5,
		"brawl" => 7,
		"brawlBoost" => 3,
		"power" => 7,
		"powerBoost" => 3,
		"health" => 6,
		"hyper" => 5,
		"abilities" => array(
			"Riot" => array("trigger" => "power", ),
			"Adaptable" => array(),
			"Climb" => array(),
			"Super Swat" => array(),)
	),
  
	"king_kondo_mega" => array(
		"name" => "King Kondo",
		"type" => "monster",
		"form" => "Mega",
		"faction" => "Empire of the Apes",
		"agenda" => "Radicals",
		"energyType" => "Nature",
		"set" => "Now",
		"setColor" => "blue",
		"rarity" => 4,
		"speed" => 7,
		"defense" => 5,
		"brawl" => 7,
		"brawlBoost" => 2,
		"power" => 9,
		"powerBoost" => 4,
		"health" => 6,
		"hyper" => 5,
		"abilities" => array(
			"Energy Cycle" => array(),
			"Power Gorge" => array("trigger" => "power", ),
			"Riot" => array("trigger" => "power", ),
			"Climb" => array(),
			"Super Rampage" => array(),)
	),
  
	"king_kondo_quantum" => array(
		"name" => "King Kondo",
		"type" => "monster",
		"form" => "Quantum",
		"quantum" => array("speed", "powerBoost", "hyper", ),
		"faction" => "Empire of the Apes",
		"agenda" => "Radicals",
		"energyType" => "Nature",
		"set" => "Now",
		"setColor" => "blue",
		"rarity" => 4,
		"speed" => 7,
		"defense" => 6,
		"brawl" => 7,
		"brawlBoost" => 3,
		"power" => 7,
		"powerBoost" => 2,
		"health" => 6,
		"hyper" => 2,
		"abilities" => array(
			"Sprint" => array(),
			"Hit and Run" => array("trigger" => "brawl", ),
			"Berserk" => array("color" => "blue", ),
			"Hasten" => array("color" => "blue", ),
			"Super Rampage" => array(),
			"Temporal Displacement" => array(),)
	),
  
	"white_dajan_alpha" => array(
		"name" => "White Dajan",
		"type" => "monster",
		"form" => "Alpha",
		"faction" => "Empire of the Apes",
		"agenda" => "Radicals",
		"energyType" => "Nature",
		"set" => "Big in Japan",
		"rarity" => 3,
		"speed" => 6,
		"defense" => 6,
		"brawl" => 7,
		"brawlBoost" => 2,
		"power" => 8,
		"powerBoost" => 2,
		"health" => 5,
		"hyper" => 0,
		"abilities" => array(
			"Riot" => array("trigger" => "brawl", ),
			"Power Drain" => array("trigger" => "power", ),
			"Synchronized Move" => array("trigger" => "power", ),
			"Climb" => array(),)
	),
  
	"white_dajan_ultra" => array(
		"name" => "White Dajan",
		"type" => "monster",
		"form" => "Ultra",
		"faction" => "Empire of the Apes",
		"agenda" => "Radicals",
		"energyType" => "Nature",
		"set" => "Big in Japan",
		"rarity" => 3,
		"speed" => 6,
		"defense" => 6,
		"brawl" => 7,
		"brawlBoost" => 2,
		"power" => 9,
		"powerBoost" => 3,
		"health" => 6,
		"hyper" => 3,
		"abilities" => array(
			"Sprint" => array(),
			"Lightning Attack" => array("trigger" => "brawl", ),
			"Power Strike" => array("trigger" => "power", ),
			"Synchronized Move" => array("trigger" => "power", ),
			"Climb" => array(),)
	),
  
	"white_dajan_mega" => array(
		"name" => "White Dajan",
		"type" => "monster",
		"form" => "Mega",
		"faction" => "Empire of the Apes",
		"agenda" => "Radicals",
		"energyType" => "Nature",
		"set" => "Big in Japan",
		"setColor" => "blue",
		"rarity" => 4,
		"speed" => 7,
		"defense" => 7,
		"brawl" => 8,
		"brawlBoost" => 4,
		"power" => 7,
		"powerBoost" => 2,
		"health" => 6,
		"hyper" => 5,
		"abilities" => array(
			"Beat Back" => array("trigger" => "brawl", ),
			"Hit and Run" => array("trigger" => "brawl", ),
			"Synchronized Move" => array("trigger" => "brawl", ),
			"Jump" => array(),)
	),
  
	"commander_haldar" => array(
		"name" => "Commander Haldar",
		"type" => "character",
		"form" => "Rocket Ape",
		"class" => "Elite",
		"faction" => "Empire of the Apes",
		"agenda" => "Radicals",
		"energyType" => "Nature",
		"set" => "Big in Japan",
		"rarity" => 4,
		"speed" => 5,
		"defense" => 3,
		"brawl" => 2,
		"brawlBoost" => 1,
		"blast" => 2,
		"blastBoost" => 2,
		"blastRange" => "short",
		"cost" => 2,
		"abilities" => array(
			"Chain Reaction" => array("trigger" => "blast", ),
			"Anti-air" => array("color" => "red",),
			"Limited" => array(),)
	),
  
	"airborne_ape_grunt" => array(
		"name" => "Airborne Ape",
		"type" => "unit",
		"class" => "Grunt",
		"faction" => "Empire of the Apes",
		"agenda" => "Radicals",
		"energyType" => "Nature",
		"set" => "Now",
		"rarity" => 1,
		"speed" => 6,
		"defense" => 3,
		"brawl" => 2,
		"blast" => 3,
		"blastRange" => "short",
		"cost" => 1,
		"abilities" => array(
			"Radial Attack" => array("trigger" => "blast", ),
			"Bomber" => array(),
			"Flight" => array(),)
	),
  
	"airborne_ape_elite" => array(
		"name" => "Airborne Ape",
		"type" => "unit",
		"class" => "Elite",
		"faction" => "Empire of the Apes",
		"agenda" => "Radicals",
		"energyType" => "Nature",
		"set" => "Now",
		"rarity" => 3,
		"speed" => 6,
		"defense" => 3,
		"brawl" => 2,
		"brawlBoost" => 1,
		"blast" => 3,
		"blastBoost" => 1,
		"blastRange" => "short",
		"cost" => 2,
		"abilities" => array(
			"Radial Attack" => array("trigger" => "blast", ),
			"Bomber" => array(),
			"Flight" => array(),
			"Leadership" => array(),)
	),
  
	"airborne_ape_glass" => array(
		"name" => "Airborne Ape",
		"type" => "unit",
		"form" => "Glass",
		"class" => "Grunt",
		"faction" => "Empire of the Apes",
		"agenda" => "Radicals",
		"energyType" => "Nature",
		"set" => "Now",
		"setColor" => "blue",
		"rarity" => 4,
		"speed" => 6,
		"defense" => 3,
		"brawl" => 2,
		"brawlBoost" => 1,
		"blast" => 3,
		"blastBoost" => 1,
		"blastRange" => "short",
		"cost" => 1,
		"abilities" => array(
			"Radial Attack" => array("trigger" => "blast", ),
			"Bomber" => array(),
			"Flight" => array(),
			"Fragile" => array(),)
	),
  
	"command_ape_grunt" => array(
		"name" => "Command Ape",
		"type" => "unit",
		"class" => "Grunt",
		"faction" => "Empire of the Apes",
		"agenda" => "Radicals",
		"energyType" => "Nature",
		"set" => "Now",
		"rarity" => 2,
		"speed" => 4,
		"defense" => 3,
		"brawl" => 3,
		"cost" => 1,
		"abilities" => array(
			"Command" => array("color" => "red",),
			"Countermeasures" => array("color" => "red",),
			"Logistics" => array(),)
	),
  
	"howitzer_ape_grunt" => array(
		"name" => "Howitzer Ape",
		"type" => "unit",
		"class" => "Grunt",
		"faction" => "Empire of the Apes",
		"agenda" => "Radicals",
		"energyType" => "Nature",
		"set" => "Now",
		"rarity" => 1,
		"speed" => 4,
		"defense" => 3,
		"brawl" => 1,
		"blast" => 2,
		"blastRange" => "long",
		"cost" => 1,
		"abilities" => array(
			"All Terrain" => array(),
			"Intensify" => array(),)
	),
  
	"howitzer_ape_elite" => array(
		"name" => "Howitzer Ape",
		"type" => "unit",
		"class" => "Elite",
		"faction" => "Empire of the Apes",
		"agenda" => "Radicals",
		"energyType" => "Nature",
		"set" => "Now",
		"rarity" => 3,
		"speed" => 4,
		"defense" => 3,
		"brawl" => 1,
		"brawlBoost" => 1,
		"blast" => 2,
		"blastBoost" => 1,
		"blastRange" => "long",
		"cost" => 2,
		"abilities" => array(
			"All Terrain" => array(),
			"Intensify" => array(),
			"Leadership" => array(),)
	),
  
	"frontline_ape_grunt" => array(
		"name" => "Frontline Ape",
		"type" => "unit",
		"class" => "Grunt",
		"faction" => "Empire of the Apes",
		"agenda" => "Radicals",
		"energyType" => "Nature",
		"set" => "Big in Japan",
		"rarity" => 1,
		"speed" => 6,
		"defense" => 3,
		"brawl" => 2,
		"brawlBoost" => 1,
		"cost" => 1,
		"abilities" => array(
			"Gang" => array(),)
	),
  
	"frontline_ape_elite" => array(
		"name" => "Frontline Ape",
		"type" => "unit",
		"class" => "Elite",
		"faction" => "Empire of the Apes",
		"agenda" => "Radicals",
		"energyType" => "Nature",
		"set" => "Big in Japan",
		"rarity" => 3,
		"speed" => 6,
		"defense" => 3,
		"brawl" => 2,
		"brawlBoost" => 2,
		"cost" => 2,
		"abilities" => array(
			"Gang" => array(),
			"Leadership" => array(),)
	),
  
	"rocket_ape_grunt" => array(
		"name" => "Rocket Ape",
		"type" => "unit",
		"class" => "Grunt",
		"faction" => "Empire of the Apes",
		"agenda" => "Radicals",
		"energyType" => "Nature",
		"set" => "Big in Japan",
		"rarity" => 1,
		"speed" => 5,
		"defense" => 3,
		"brawl" => 2,
		"blast" => 2,
		"blastBoost" => 1,
		"blastRange" => "short",
		"cost" => 1,
		"abilities" => array(
			"Explosion" => array("trigger" => "blast", ),)
	),
  
	"rocket_ape_elite" => array(
		"name" => "Rocket Ape",
		"type" => "unit",
		"class" => "Elite",
		"faction" => "Empire of the Apes",
		"agenda" => "Radicals",
		"energyType" => "Nature",
		"set" => "Big in Japan",
		"rarity" => 2,
		"speed" => 5,
		"defense" => 3,
		"brawl" => 2,
		"brawlBoost" => 1,
		"blast" => 2,
		"blastBoost" => 2,
		"blastRange" => "short",
		"cost" => 2,
		"abilities" => array(
			"Explosion" => array("trigger" => "blast", ),
			"Leadership" => array(),)
	),
  
	"rocket_ape_glass" => array(
		"name" => "Rocket Ape",
		"type" => "unit",
		"form" => "Glass",
		"class" => "Grunt",
		"faction" => "Empire of the Apes",
		"agenda" => "Radicals",
		"energyType" => "Nature",
		"set" => "Big in Japan",
		"setColor" => "blue",
		"rarity" => 4,
		"speed" => 5,
		"defense" => 3,
		"brawl" => 1,
		"blast" => 1,
		"blastBoost" => 1,
		"blastRange" => "short",
		"cost" => 1,
		"abilities" => array(
			"Explosion" => array("trigger" => "blast", ),
			"All Terrain" => array(),
			"Fragile" => array(),
			"Indirect Fire" => array(),)
	),
  
	"stealth_ape_grunt" => array(
		"name" => "Stealth Ape",
		"type" => "unit",
		"class" => "Grunt",
		"faction" => "Empire of the Apes",
		"agenda" => "Radicals",
		"energyType" => "Nature",
		"set" => "Now",
		"rarity" => 2,
		"speed" => 5,
		"defense" => 3,
		"brawl" => 1,
		"brawlBoost" => 1,
		"cost" => 1,
		"abilities" => array(
			"Hit and Run" => array("trigger" => "brawl", ),
			"Cloak" => array(),
			"Jump" => array(),
			"Spotter" => array(),)
	),
  
