


/*    =============    Guard    =============    */

	"defender_x_alpha" => array(
		"name" => "Defender X",
		"type" => "monster",
		"form" => "Alpha",
		"faction" => "G.U.A.R.D.",
		"agenda" => "Protectors",
		"energyType" => "Mechanical",
		"set" => "Rise",
		"rarity" => 3,
		"speed" => 6,
		"defense" => 6,
		"brawl" => 7,
		"brawlBoost" => 2,
		"blast" => 7,
		"blastBoost" => 2,
		"blastRange" => "short",
		"power" => 5,
		"powerBoost" => 2,
		"health" => 5,
		"hyper" => 0,
		"abilities" => array(
			"Energy Drain" => array("trigger" => "blast", ),
			"Force Field" => array("color" => "blue", ),
			"Jump" => array(),
			"Safeguard" => array(),)
	),
  
	"defender_x_ultra" => array(
		"name" => "Defender X",
		"type" => "monster",
		"form" => "Ultra",
		"faction" => "G.U.A.R.D.",
		"agenda" => "Protectors",
		"energyType" => "Mechanical",
		"set" => "Rise",
		"rarity" => 3,
		"speed" => 7,
		"defense" => 7,
		"brawl" => 7,
		"brawlBoost" => 3,
		"blast" => 7,
		"blastBoost" => 3,
		"blastRange" => "short",
		"power" => 6,
		"powerBoost" => 2,
		"health" => 6,
		"hyper" => 4,
		"abilities" => array(
			"Energy Cycle" => array("color" => "blue", ),
			"Explosion" => array("trigger" => "blast", ),
			"Beat Back" => array("trigger" => "blast", ),
			"Flight_short" => array(),
			"Safeguard" => array(),)
	),
  
	"defender_x_mega" => array(
		"name" => "Defender X",
		"type" => "monster",
		"form" => "Mega",
		"faction" => "G.U.A.R.D.",
		"agenda" => "Protectors",
		"energyType" => "Mechanical",
		"set" => "Rise",
		"setColor" => "blue",
		"rarity" => 5,
		"speed" => 7,
		"defense" => 7,
		"brawl" => 8,
		"brawlBoost" => 4,
		"blast" => 5,
		"blastBoost" => 1,
		"blastRange" => "short",
		"power" => 5,
		"powerBoost" => 2,
		"health" => 6,
		"hyper" => 5,
		"abilities" => array(
			"Hit and Run" => array("trigger" => "brawl", ),
			"Power Drain" => array("trigger" => "brawl", ),
			"Beat Back" => array("trigger" => "brawl", ),
			"Jump_short" => array(),
			"Super Strength" => array(),)
	),
  
	"laser_knight_alpha" => array(
		"name" => "Laser Knight",
		"type" => "monster",
		"form" => "Alpha",
		"faction" => "G.U.A.R.D.",
		"agenda" => "Protectors",
		"energyType" => "Mechanical",
		"set" => "I Chomp NY",
		"rarity" => 3,
		"speed" => 6,
		"defense" => 6,
		"brawl" => 7,
		"brawlBoost" => 3,
		"power" => 6,
		"powerBoost" => 2,
		"health" => 6,
		"hyper" => 0,
		"abilities" => array(
			"Crunch" => array("trigger" => "brawl", ),
			"Hit and Run" => array("trigger" => "brawl", ),
			"Amplify" => array("color" => "blue", ),
			"Resilience" => array(),
			"Solid" => array(),)
	),
  
	"laser_knight_ultra" => array(
		"name" => "Laser Knight",
		"type" => "monster",
		"form" => "Ultra",
		"faction" => "G.U.A.R.D.",
		"agenda" => "Protectors",
		"energyType" => "Mechanical",
		"set" => "I Chomp NY",
		"rarity" => 3,
		"speed" => 6,
		"defense" => 7,
		"brawl" => 8,
		"brawlBoost" => 4,
		"blast" => 5,
		"blastBoost" => 2,
		"blastRange" => "long",
		"power" => 7,
		"powerBoost" => 3,
		"health" => 6,
		"hyper" => 4,
		"abilities" => array(
			"Chain Attack" => array("trigger" => "brawl", ),
			"Amplify" => array("color" => "blue", ),
			"Resilience" => array(),
			"Solid" => array(),
			"Super Strength" => array(),)
	),
  
	"laser_knight_mega" => array(
		"name" => "Laser Knight",
		"type" => "monster",
		"form" => "Mega",
		"faction" => "G.U.A.R.D.",
		"agenda" => "Protectors",
		"energyType" => "Mechanical",
		"set" => "I Chomp NY",
		"setColor" => "blue",
		"rarity" => 4,
		"speed" => 6,
		"defense" => 7,
		"brawl" => 7,
		"brawlBoost" => 3,
		"power" => 5,
		"powerBoost" => 3,
		"health" => 5,
		"hyper" => 4,
		"abilities" => array(
			"Energy Cycle" => array(),
			"Hit and Run" => array("trigger" => "brawl", ),
			"Amplify" => array("color" => "blue", ),
			"Armored" => array(),)
	),
  
	"legionnaire_alpha_gladius_1" => array(
		"name" => "Legionnaire",
		"type" => "monster",
		"form" => "Gladius 1",
		"faction" => "G.U.A.R.D.",
		"agenda" => "Protectors",
		"energyType" => "Mechanical",
		"set" => "All Your Base",
		"rarity" => 3,
		"speed" => 6,
		"defense" => 4,
		"blast" => 3,
		"blastBoost" => 1,
		"blastRange" => "short",
		"health" => 6,
		"hyper" => 0,
		"abilities" => array(
			"Marker" => array("color" => "red",),
			"Chain Reaction" => array("trigger" => "blast", ),
			"Bomber" => array(),
			"Flight" => array(),)
	),
  
	"legionnaire_alpha_gladius_2" => array(
		"name" => "Legionnaire",
		"type" => "monster",
		"form" => "Gladius 2",
		"faction" => "G.U.A.R.D.",
		"agenda" => "Protectors",
		"energyType" => "Mechanical",
		"set" => "All Your Base",
		"rarity" => 3,
		"speed" => 6,
		"defense" => 4,
		"blast" => 3,
		"blastBoost" => 1,
		"blastRange" => "short",
		"health" => 6,
		"hyper" => 0,
		"abilities" => array(
			"Flight" => array(),
			"Jam" => array(),
			"Radar" => array("color" => "red",),
			"Spotter" => array(),)
	),
  
	"legionnaire_alpha_shield_3" => array(
		"name" => "Legionnaire",
		"type" => "monster",
		"form" => "Shield 3",
		"faction" => "G.U.A.R.D.",
		"agenda" => "Protectors",
		"energyType" => "Mechanical",
		"set" => "All Your Base",
		"rarity" => 3,
		"speed" => 5,
		"defense" => 5,
		"brawl" => 2,
		"brawlBoost" => 2,
		"blast" => 3,
		"blastBoost" => 1,
		"blastRange" => "long",
		"health" => 6,
		"hyper" => 0,
		"abilities" => array(
			"Overload" => array("trigger" => "blast", ),
			"All Terrain" => array(),
			"Deflector Shield" => array(),
			"Force Field" => array("color" => "red",),)
	),
  
	"legionnaire_alpha_shield_4" => array(
		"name" => "Legionnaire",
		"type" => "monster",
		"form" => "Shield 4",
		"faction" => "G.U.A.R.D.",
		"agenda" => "Protectors",
		"energyType" => "Mechanical",
		"set" => "All Your Base",
		"rarity" => 3,
		"speed" => 5,
		"defense" => 5,
		"brawl" => 2,
		"brawlBoost" => 1,
		"blast" => 3,
		"blastBoost" => 1,
		"blastRange" => "long",
		"health" => 6,
		"hyper" => 0,
		"abilities" => array(
			"Crunch" => array("trigger" => "blast", ),
			"Flak" => array("trigger" => "blast", ),
			"All Terrain" => array(),
			"No-Fly Zone" => array(),)
	),
  
	"legionnaire_ultra" => array(
		"name" => "Legionnaire",
		"type" => "monster",
		"form" => "Ultra",
		"faction" => "G.U.A.R.D.",
		"agenda" => "Protectors",
		"energyType" => "Mechanical",
		"set" => "All Your Base",
		"rarity" => 3,
		"speed" => 6,
		"defense" => 7,
		"brawl" => 8,
		"brawlBoost" => 3,
		"blast" => 8,
		"blastBoost" => 3,
		"blastRange" => "short",
		"power" => 7,
		"powerBoost" => 2,
		"health" => 5,
		"hyper" => 3,
		"abilities" => array(
			"Toss" => array("trigger" => "brawl", ),
			"Multi-shot" => array("trigger" => "blast", ),
			"Flight" => array(),
			"Radar" => array("color" => "blue", ),)
	),
  
	"legionnaire_mega" => array(
		"name" => "Legionnaire",
		"type" => "monster",
		"form" => "Mega",
		"faction" => "G.U.A.R.D.",
		"agenda" => "Protectors",
		"energyType" => "Mechanical",
		"set" => "All Your Base",
		"setColor" => "blue",
		"rarity" => 4,
		"speed" => 7,
		"defense" => 7,
		"brawl" => 7,
		"brawlBoost" => 2,
		"blast" => 7,
		"blastBoost" => 3,
		"blastRange" => "long",
		"power" => 7,
		"powerBoost" => 3,
		"health" => 5,
		"hyper" => 3,
		"abilities" => array(
			"Hit and Run" => array("trigger" => "blast", ),
			"Power Drain" => array("trigger" => "blast", ),
			"Weapon Master" => array("trigger" => "blast", ),
			"Jump" => array(),
			"Radar" => array("color" => "blue", ),)
	),
  
	"nova_esr_alpha" => array(
		"name" => "Nova ESR",
		"type" => "monster",
		"form" => "Alpha",
		"faction" => "G.U.A.R.D.",
		"agenda" => "Protectors",
		"energyType" => "Mechanical",
		"set" => "I Chomp NY",
		"rarity" => 3,
		"speed" => 6,
		"defense" => 5,
		"brawl" => 7,
		"brawlBoost" => 1,
		"blast" => 7,
		"blastBoost" => 2,
		"blastRange" => "short",
		"power" => 7,
		"powerBoost" => 2,
		"health" => 5,
		"hyper" => 0,
		"abilities" => array(
			"Sprint" => array("color" => "blue", ),
			"Hit and Run" => array("trigger" => "blast", ),
			"Lightning Attack" => array("trigger" => "blast", ),
			"Flight" => array(),)
	),
  
	"nova_esr_ultra" => array(
		"name" => "Nova ESR",
		"type" => "monster",
		"form" => "Ultra",
		"faction" => "G.U.A.R.D.",
		"agenda" => "Protectors",
		"energyType" => "Mechanical",
		"set" => "I Chomp NY",
		"rarity" => 3,
		"speed" => 7,
		"defense" => 6,
		"brawl" => 8,
		"brawlBoost" => 2,
		"blast" => 8,
		"blastBoost" => 3,
		"blastRange" => "short",
		"power" => 8,
		"powerBoost" => 2,
		"health" => 5,
		"hyper" => 4,
		"abilities" => array(
			"Sprint" => array("color" => "blue", ),
			"Multi-shot" => array("trigger" => "blast", ),
			"Weapon Master" => array("trigger" => "blast", ),
			"Flight" => array(),)
	),
  
	"nova_esr_mega" => array(
		"name" => "Nova ESR",
		"type" => "monster",
		"form" => "Mega",
		"faction" => "G.U.A.R.D.",
		"agenda" => "Protectors",
		"energyType" => "Mechanical",
		"set" => "I Chomp NY",
		"setColor" => "blue",
		"rarity" => 4,
		"speed" => 9,
		"defense" => 7,
		"brawl" => 8,
		"brawlBoost" => 2,
		"blast" => 5,
		"blastBoost" => 4,
		"blastRange" => "short",
		"power" => 5,
		"powerBoost" => 2,
		"health" => 6,
		"hyper" => 3,
		"abilities" => array(
			"Fission" => array(),
			"Energy Cycle" => array("color" => "blue", ),
			"Overload" => array("trigger" => "blast", ),
			"Flight" => array(),)
	),
  
	"sky_sentinel_alpha" => array(
		"name" => "Sky Sentinel",
		"type" => "monster",
		"form" => "Alpha",
		"faction" => "G.U.A.R.D.",
		"agenda" => "Protectors",
		"energyType" => "Mechanical",
		"set" => "Rise",
		"rarity" => 3,
		"speed" => 7,
		"defense" => 7,
		"brawl" => 6,
		"brawlBoost" => 1,
		"blast" => 6,
		"blastBoost" => 2,
		"blastRange" => "long",
		"power" => 5,
		"powerBoost" => 1,
		"health" => 5,
		"hyper" => 0,
		"abilities" => array(
			"Anti-air" => array(),
			"Flight" => array(),
			"Ground Control" => array("color" => "blue", ),
			"Radar" => array("color" => "red",),
			"Wing Leader" => array("color" => "blue", ),)
	),
  
	"sky_sentinel_ultra" => array(
		"name" => "Sky Sentinel",
		"type" => "monster",
		"form" => "Ultra",
		"faction" => "G.U.A.R.D.",
		"agenda" => "Protectors",
		"energyType" => "Mechanical",
		"set" => "Rise",
		"rarity" => 3,
		"speed" => 7,
		"defense" => 7,
		"brawl" => 6,
		"brawlBoost" => 2,
		"blast" => 7,
		"blastBoost" => 3,
		"blastRange" => "long",
		"power" => 5,
		"powerBoost" => 2,
		"health" => 5,
		"hyper" => 4,
		"abilities" => array(
			"Lightning Attack" => array("trigger" => "blast", ),
			"Flight_short" => array(),
			"Ground Control" => array("color" => "blue", ),
			"Low Flyer" => array("color" => "blue", ),
			"Radar" => array("color" => "red",),
			"Wing Leader" => array("color" => "blue", ),)
	),
  
	"sky_sentinel_mega" => array(
		"name" => "Sky Sentinel",
		"type" => "monster",
		"form" => "Mega",
		"faction" => "G.U.A.R.D.",
		"agenda" => "Protectors",
		"energyType" => "Mechanical",
		"set" => "Rise",
		"setColor" => "blue",
		"rarity" => 5,
		"speed" => 9,
		"defense" => 8,
		"brawl" => 7,
		"brawlBoost" => 2,
		"blast" => 6,
		"blastBoost" => 2,
		"blastRange" => "short",
		"power" => 8,
		"powerBoost" => 3,
		"health" => 5,
		"hyper" => 5,
		"abilities" => array(
			"Energy Drain" => array("trigger" => "power", ),
			"Power Gorge" => array("trigger" => "power", ),
			"Charge" => array(),
			"Flight_short" => array(),
			"Super Smash" => array(),
			"Wing Leader" => array("color" => "blue", ),)
	),
  
	"g.u.a.r.d._defense_base" => array(
		"name" => "G.U.A.R.D. Defense Base",
		"type" => "building",
		"hazard" => "rubble",
		"faction" => "G.U.A.R.D.",
		"agenda" => "Protectors",
		"set" => "All Your Base",
		"rarity" => 3,
		"defense" => 6,
		"energy" => 5,
		"blast" => 2,
		"blastRange" => "long",
		"abilities" => array(
			"Teleport" => array(),
			"Discount" => array(),
			"Radar Network" => array(),)
	),
  
	"anti-aircraft_tank_grunt" => array(
		"name" => "Anti-Aircraft Tank",
		"type" => "unit",
		"class" => "Grunt",
		"faction" => "G.U.A.R.D.",
		"agenda" => "Protectors",
		"energyType" => "Mechanical",
		"set" => "All Your Base",
		"rarity" => 1,
		"speed" => 4,
		"defense" => 4,
		"brawl" => 1,
		"blast" => 1,
		"blastRange" => "short",
		"cost" => 1,
		"abilities" => array(
			"Flak" => array("trigger" => "blast", ),
			"All Terrain" => array(),
			"Anti-air" => array(),)
	),
  
	"anti-aircraft_tank_elite" => array(
		"name" => "Anti-Aircraft Tank",
		"type" => "unit",
		"class" => "Elite",
		"faction" => "G.U.A.R.D.",
		"agenda" => "Protectors",
		"energyType" => "Mechanical",
		"set" => "All Your Base",
		"rarity" => 2,
		"speed" => 4,
		"defense" => 4,
		"brawl" => 1,
		"brawlBoost" => 1,
		"blast" => 1,
		"blastBoost" => 1,
		"blastRange" => "short",
		"cost" => 2,
		"abilities" => array(
			"Flak" => array("trigger" => "blast", ),
			"All Terrain" => array(),
			"Anti-air" => array(),
			"Leadership" => array(),)
	),
  
	"fuel_truck_grunt" => array(
		"name" => "Fuel Truck",
		"type" => "unit",
		"class" => "Grunt",
		"faction" => "G.U.A.R.D.",
		"agenda" => "Protectors",
		"energyType" => "Mechanical",
		"set" => "All Your Base",
		"rarity" => 3,
		"speed" => 4,
		"defense" => 2,
		"cost" => 1,
		"abilities" => array(
			"Refuel" => array(),
			"Energize" => array("color" => "red",),
			"Unstable" => array(),)
	),
  
	"fuel_truck_shadow" => array(
		"name" => "Fuel Truck",
		"type" => "unit",
		"form" => "Shadow",
		"class" => "Grunt",
		"faction" => "G.U.A.R.D.",
		"agenda" => "Protectors",
		"energyType" => "Mechanical",
		"set" => "All Your Base",
		"setColor" => "blue",
		"rarity" => 4,
		"speed" => 4,
		"defense" => 2,
		"cost" => 2,
		"abilities" => array(
			"Refuel" => array(),
			"Cloak" => array(),
			"Energize" => array("color" => "red",),
			"Unstable" => array(),)
	),
  
	"g-tank_grunt" => array(
		"name" => "G-Tank",
		"type" => "unit",
		"class" => "Grunt",
		"faction" => "G.U.A.R.D.",
		"agenda" => "Protectors",
		"energyType" => "Mechanical",
		"set" => "Rise",
		"rarity" => 1,
		"speed" => 4,
		"defense" => 4,
		"brawl" => 1,
		"blast" => 2,
		"blastRange" => "long",
		"cost" => 1,
		"abilities" => array(
			"All Terrain" => array(),)
	),
  
	"g-tank_elite" => array(
		"name" => "G-Tank",
		"type" => "unit",
		"class" => "Elite",
		"faction" => "G.U.A.R.D.",
		"agenda" => "Protectors",
		"energyType" => "Mechanical",
		"set" => "Rise",
		"rarity" => 2,
		"speed" => 4,
		"defense" => 4,
		"brawl" => 1,
		"brawlBoost" => 1,
		"blast" => 2,
		"blastBoost" => 1,
		"blastRange" => "long",
		"cost" => 2,
		"abilities" => array(
			"All Terrain" => array(),
			"Leadership" => array(),)
	),
  
	"g1_strike_fighter_grunt" => array(
		"name" => "G1 Strike Fighter",
		"type" => "unit",
		"class" => "Grunt",
		"faction" => "G.U.A.R.D.",
		"agenda" => "Protectors",
		"energyType" => "Mechanical",
		"set" => "I Chomp NY",
		"rarity" => 2,
		"speed" => 8,
		"defense" => 2,
		"blast" => 1,
		"blastBoost" => 1,
		"blastRange" => "short",
		"cost" => 1,
		"abilities" => array(
			"Flight" => array(),
			"Indirect Fire" => array(),)
	),
  
	"g1_strike_fighter_elite" => array(
		"name" => "G1 Strike Fighter",
		"type" => "unit",
		"class" => "Elite",
		"faction" => "G.U.A.R.D.",
		"agenda" => "Protectors",
		"energyType" => "Mechanical",
		"set" => "I Chomp NY",
		"rarity" => 3,
		"speed" => 8,
		"defense" => 2,
		"blast" => 1,
		"blastBoost" => 2,
		"blastRange" => "short",
		"cost" => 2,
		"abilities" => array(
			"Flight" => array(),
			"Indirect Fire" => array(),
			"Leadership" => array(),)
	),
  
	"g1_strike_fighter_shadow" => array(
		"name" => "G1 Strike Fighter",
		"type" => "unit",
		"form" => "Shadow",
		"class" => "Grunt",
		"faction" => "G.U.A.R.D.",
		"agenda" => "Protectors",
		"energyType" => "Mechanical",
		"set" => "I Chomp NY",
		"setColor" => "blue",
		"rarity" => 4,
		"speed" => 8,
		"defense" => 2,
		"blast" => 1,
		"blastBoost" => 1,
		"blastRange" => "short",
		"cost" => 2,
		"abilities" => array(
			"Cloak" => array(),
			"Flight" => array(),
			"Indirect Fire" => array(),)
	),
  
	"ion_cannon_tank_grunt" => array(
		"name" => "Ion Cannon Tank",
		"type" => "unit",
		"class" => "Grunt",
		"faction" => "G.U.A.R.D.",
		"agenda" => "Protectors",
		"energyType" => "Mechanical",
		"set" => "I Chomp NY",
		"rarity" => 1,
		"speed" => 4,
		"defense" => 4,
		"brawl" => 1,
		"blast" => 2,
		"blastRange" => "short",
		"cost" => 1,
		"abilities" => array(
			"Disrupt" => array("trigger" => "blast", ),
			"Power Drain" => array("trigger" => "blast", ),
			"All Terrain" => array(),)
	),
  
	"ion_cannon_tank_elite" => array(
		"name" => "Ion Cannon Tank",
		"type" => "unit",
		"class" => "Elite",
		"faction" => "G.U.A.R.D.",
		"agenda" => "Protectors",
		"energyType" => "Mechanical",
		"set" => "I Chomp NY",
		"rarity" => 2,
		"speed" => 4,
		"defense" => 4,
		"brawl" => 1,
		"brawlBoost" => 1,
		"blast" => 2,
		"blastBoost" => 1,
		"blastRange" => "short",
		"cost" => 2,
		"abilities" => array(
			"Disrupt" => array("trigger" => "blast", ),
			"Power Drain" => array("trigger" => "blast", ),
			"All Terrain" => array(),
			"Leadership" => array(),)
	),
  
	"mobile_ops_center_grunt" => array(
		"name" => "Mobile Ops Center",
		"type" => "unit",
		"class" => "Grunt",
		"faction" => "G.U.A.R.D.",
		"agenda" => "Protectors",
		"energyType" => "Mechanical",
		"set" => "Rise",
		"rarity" => 3,
		"speed" => 5,
		"defense" => 2,
		"cost" => 1,
		"abilities" => array(
			"Logistics" => array(),
			"Radar" => array("color" => "red",),)
	),
  
	"repair_vehicle_grunt" => array(
		"name" => "Repair Vehicle",
		"type" => "unit",
		"class" => "Grunt",
		"faction" => "G.U.A.R.D.",
		"agenda" => "Protectors",
		"energyType" => "Mechanical",
		"set" => "Rise",
		"rarity" => 3,
		"speed" => 5,
		"defense" => 2,
		"cost" => 1,
		"abilities" => array(
			"Repair" => array(),)
	),
  
	"rocket_chopper_grunt" => array(
		"name" => "Rocket Chopper",
		"type" => "unit",
		"class" => "Grunt",
		"faction" => "G.U.A.R.D.",
		"agenda" => "Protectors",
		"energyType" => "Mechanical",
		"set" => "Rise",
		"rarity" => 1,
		"speed" => 5,
		"defense" => 2,
		"blast" => 2,
		"blastRange" => "short",
		"cost" => 1,
		"abilities" => array(
			"Flight" => array(),
			"Spotter" => array(),)
	),
  
	"rocket_chopper_elite" => array(
		"name" => "Rocket Chopper",
		"type" => "unit",
		"class" => "Elite",
		"faction" => "G.U.A.R.D.",
		"agenda" => "Protectors",
		"energyType" => "Mechanical",
		"set" => "Rise",
		"rarity" => 2,
		"speed" => 5,
		"defense" => 2,
		"blast" => 2,
		"blastBoost" => 1,
		"blastRange" => "short",
		"cost" => 2,
		"abilities" => array(
			"Flight" => array(),
			"Leadership" => array(),
			"Spotter" => array(),)
	),
  
 	"rocket_chopper_shadow" => array(
		"name" => "Rocket Chopper",
		"type" => "unit",
		"form" => "Shadow",
		"class" => "Elite",
		"faction" => "G.U.A.R.D.",
		"agenda" => "Protectors",
		"energyType" => "Mechanical",
		"set" => "Rise",
		"setColor" => "blue",
		"rarity" => 5,
		"speed" => 5,
		"defense" => 2,
		"blast" => 2,
		"blastBoost" => 1,
		"blastRange" => "short",
		"cost" => 3,
		"abilities" => array(
			"Cloak" => array(),
			"Flight" => array(),
			"Leadership" => array(),
			"Spotter" => array(),)
	),
  
