


/*    =============    Galaxy Garrison    =============    */

	"voltron_alpha_black_lion" => array(
		"name" => "Voltron",
		"type" => "monster",
		"form" => "Black Lion",
		"faction" => "Galaxy Garrison",
		"agenda" => "Protectors",
		"energyType" => "Mechanical",
		"set" => "Voltron Box Set",
		"rarity" => 3,
		"speed" => 5,
		"defense" => 5,
		"brawl" => 4,
		"brawlBoost" => 1,
		"blast" => 4,
		"blastBoost" => 1,
		"blastRange" => "short",
		"health" => 5,
		"hyper" => 0,
		"abilities" => array(
			"Toss" => array("trigger" => "brawl", ),
			"Crunch" => array("trigger" => "blast", ),
			"Flight" => array(),)
	),
  
	"voltron_alpha_blue_lion" => array(
		"name" => "Voltron",
		"type" => "monster",
		"form" => "Blue Lion",
		"faction" => "Galaxy Garrison",
		"agenda" => "Protectors",
		"energyType" => "Mechanical",
		"set" => "Voltron Box Set",
		"rarity" => 3,
		"speed" => 5,
		"defense" => 5,
		"brawl" => 4,
		"brawlBoost" => 1,
		"blast" => 3,
		"blastBoost" => 1,
		"blastRange" => "short",
		"health" => 5,
		"hyper" => 0,
		"abilities" => array(
			"Power Gorge" => array("trigger" => "blast", ),
			"Flight" => array(),
			"Motivator" => array(),)
	),
  
	"voltron_alpha_green_lion" => array(
		"name" => "Voltron",
		"type" => "monster",
		"form" => "Green Lion",
		"faction" => "Galaxy Garrison",
		"agenda" => "Protectors",
		"energyType" => "Mechanical",
		"set" => "Voltron Box Set",
		"rarity" => 3,
		"speed" => 6,
		"defense" => 5,
		"brawl" => 3,
		"brawlBoost" => 1,
		"blast" => 3,
		"blastRange" => "short",
		"health" => 5,
		"hyper" => 0,
		"abilities" => array(
			"Synchronized Move" => array("trigger" => "brawl", ),
			"Flight" => array(),
			"Quick" => array(),)
	),
  
	"voltron_alpha_red_lion" => array(
		"name" => "Voltron",
		"type" => "monster",
		"form" => "Red Lion",
		"faction" => "Galaxy Garrison",
		"agenda" => "Protectors",
		"energyType" => "Mechanical",
		"set" => "Voltron Box Set",
		"rarity" => 3,
		"speed" => 6,
		"defense" => 5,
		"brawl" => 3,
		"blast" => 3,
		"blastBoost" => 1,
		"blastRange" => "short",
		"health" => 5,
		"hyper" => 0,
		"abilities" => array(
			"Explosion" => array("trigger" => "blast", ),
			"Flight" => array(),)
	),
  
	"voltron_alpha_yellow_lion" => array(
		"name" => "Voltron",
		"type" => "monster",
		"form" => "Yellow Lion",
		"faction" => "Galaxy Garrison",
		"agenda" => "Protectors",
		"energyType" => "Mechanical",
		"set" => "Voltron Box Set",
		"rarity" => 3,
		"speed" => 5,
		"defense" => 5,
		"brawl" => 4,
		"brawlBoost" => 1,
		"blast" => 3,
		"blastBoost" => 1,
		"blastRange" => "short",
		"health" => 5,
		"hyper" => 0,
		"abilities" => array(
			"Radial Attack" => array("trigger" => "brawl", ),
			"Flight" => array(),)
	),
  
	"voltron_ultra" => array(
		"name" => "Voltron",
		"type" => "monster",
		"form" => "Ultra",
		"faction" => "Galaxy Garrison",
		"agenda" => "Protectors",
		"energyType" => "Mechanical",
		"set" => "Voltron Box Set",
		"rarity" => 3,
		"speed" => 6,
		"defense" => 7,
		"brawl" => 8,
		"brawlBoost" => 4,
		"blast" => 8,
		"blastBoost" => 3,
		"blastRange" => "short",
		"power" => 7,
		"powerBoost" => 3,
		"health" => 6,
		"hyper" => 4,
		"abilities" => array(
			"Weapon Master" => array("trigger" => "brawl", ),
			"Synchronized Move" => array("trigger" => "power", ),
			"Flight_short" => array(),
			"Reach" => array(),
			"Super Smash" => array(),)
	),
  
	"voltron_mega" => array(
		"name" => "Voltron",
		"type" => "monster",
		"form" => "Mega",
		"faction" => "Galaxy Garrison",
		"agenda" => "Protectors",
		"energyType" => "Mechanical",
		"set" => "Voltron Box Set",
		"setColor" => "black",
		"rarity" => 4,
		"speed" => 7,
		"defense" => 6,
		"brawl" => 7,
		"brawlBoost" => 3,
		"blast" => 8,
		"blastBoost" => 3,
		"blastRange" => "short",
		"power" => 7,
		"powerBoost" => 4,
		"health" => 6,
		"hyper" => 4,
		"abilities" => array(
			"Lightning Attack" => array("trigger" => "brawl", ),
			"Multi-shot" => array("trigger" => "blast", ),
			"Crunch" => array("trigger" => "power", ),
			"Flight_short" => array(),
			"Reach" => array(),)
	),
  
	"galaxy_garrison_cruiser_grunt" => array(
		"name" => "Galaxy Garrison Cruiser",
		"type" => "unit",
		"class" => "Grunt",
		"faction" => "Galaxy Garrison",
		"agenda" => "Protectors",
		"energyType" => "Mechanical",
		"set" => "Voltron Box Set",
		"rarity" => 1,
		"speed" => 5,
		"defense" => 2,
		"blast" => 3,
		"blastBoost" => 1,
		"blastRange" => "short",
		"cost" => 1,
		"abilities" => array(
			"Synchronized Move" => array("trigger" => "blast", ),
			"Flight" => array(),)
	),
