


/*    =============    Lords of Cthul    =============    */

	"ancient_osheroth_alpha_despair_tentacle" => array(
		"name" => "Ancient Osheroth",
		"type" => "monster",
		"form" => "Despair Tentacle",
		"faction" => "Lords of Cthul",
		"agenda" => "Fiends",
		"energyType" => "Occult",
		"set" => "All Your Base",
		"rarity" => 3,
		"speed" => 5,
		"defense" => 5,
		"brawl" => 3,
		"brawlBoost" => 1,
		"blast" => 2,
		"blastBoost" => 1,
		"blastRange" => "short",
		"health" => 5,
		"hyper" => 0,
		"abilities" => array(
			"Telekinesis" => array("color" => "red",),
			"Fling" => array("trigger" => "brawl", ),
			"Burrow" => array(),
			"Reach" => array(),)
	),
  
	"ancient_osheroth_alpha_dismay_tentacle" => array(
		"name" => "Ancient Osheroth",
		"type" => "monster",
		"form" => "Dismay Tentacle",
		"faction" => "Lords of Cthul",
		"agenda" => "Fiends",
		"energyType" => "Occult",
		"set" => "All Your Base",
		"rarity" => 3,
		"speed" => 5,
		"defense" => 5,
		"brawl" => 3,
		"brawlBoost" => 1,
		"blast" => 2,
		"blastBoost" => 1,
		"blastRange" => "short",
		"health" => 5,
		"hyper" => 0,
		"abilities" => array(
			"Beat Back" => array("trigger" => "brawl", ),
			"Hit and Run" => array("color" => "red","trigger" => "brawl", ),
			"Burrow" => array(),
			"Reach" => array(),)
	),
  
	"ancient_osheroth_alpha_distress_tentacle" => array(
		"name" => "Ancient Osheroth",
		"type" => "monster",
		"form" => "Distress Tentacle",
		"faction" => "Lords of Cthul",
		"agenda" => "Fiends",
		"energyType" => "Occult",
		"set" => "All Your Base",
		"rarity" => 3,
		"speed" => 5,
		"defense" => 5,
		"brawl" => 3,
		"brawlBoost" => 1,
		"blast" => 2,
		"blastBoost" => 1,
		"blastRange" => "short",
		"health" => 5,
		"hyper" => 0,
		"abilities" => array(
			"Summon" => array(),
			"Siphon" => array("color" => "red","trigger" => "brawl", ),
			"Burrow" => array(),
			"Reach" => array(),)
	),
  
	"ancient_osheroth_alpha_dread_tentacle" => array(
		"name" => "Ancient Osheroth",
		"type" => "monster",
		"form" => "Dread Tentacle",
		"faction" => "Lords of Cthul",
		"agenda" => "Fiends",
		"energyType" => "Occult",
		"set" => "All Your Base",
		"rarity" => 3,
		"speed" => 5,
		"defense" => 5,
		"brawl" => 3,
		"brawlBoost" => 1,
		"blast" => 2,
		"blastBoost" => 1,
		"blastRange" => "short",
		"health" => 5,
		"hyper" => 0,
		"abilities" => array(
			"Vampirism" => array("trigger" => "brawl", ),
			"Burrow" => array(),
			"Penetrator" => array("color" => "red",),
			"Reach" => array(),)
	),
  
	"ancient_osheroth_ultra" => array(
		"name" => "Ancient Osheroth",
		"type" => "monster",
		"form" => "Ultra",
		"faction" => "Lords of Cthul",
		"agenda" => "Fiends",
		"energyType" => "Occult",
		"set" => "All Your Base",
		"rarity" => 3,
		"speed" => 6,
		"defense" => 7,
		"brawl" => 7,
		"brawlBoost" => 4,
		"blast" => 6,
		"blastBoost" => 2,
		"blastRange" => "short",
		"power" => 8,
		"powerBoost" => 3,
		"health" => 6,
		"hyper" => 3,
		"abilities" => array(
			"Sacrifice" => array(),
			"Telekinesis" => array("color" => "blue", ),
			"Radial Attack" => array("trigger" => "brawl", ),
			"Annihilate" => array(),)
	),
  
	"ancient_osheroth_mega" => array(
		"name" => "Ancient Osheroth",
		"type" => "monster",
		"form" => "Mega",
		"faction" => "Lords of Cthul",
		"agenda" => "Fiends",
		"energyType" => "Occult",
		"set" => "All Your Base",
		"setColor" => "blue",
		"rarity" => 4,
		"speed" => 6,
		"defense" => 7,
		"brawl" => 8,
		"brawlBoost" => 2,
		"blast" => 7,
		"blastBoost" => 3,
		"blastRange" => "long",
		"power" => 6,
		"powerBoost" => 3,
		"health" => 6,
		"hyper" => 4,
		"abilities" => array(
			"Extinguish" => array("color" => "blue", ),
			"Leach" => array(),
			"Feeding Frenzy" => array("trigger" => "blast", ),
			"Multi-shot" => array("trigger" => "blast", ),)
	),
  
	"cthugrosh_alpha" => array(
		"name" => "Cthugrosh",
		"type" => "monster",
		"form" => "Alpha",
		"faction" => "Lords of Cthul",
		"agenda" => "Fiends",
		"energyType" => "Occult",
		"set" => "Rise",
		"rarity" => 3,
		"speed" => 6,
		"defense" => 5,
		"brawl" => 7,
		"brawlBoost" => 2,
		"blast" => 5,
		"blastBoost" => 1,
		"blastRange" => "short",
		"power" => 6,
		"powerBoost" => 2,
		"health" => 6,
		"hyper" => 0,
		"abilities" => array(
			"Sacrifice" => array(),
			"Summon" => array(),
			"Telekinesis" => array(),
			"Power Gorge" => array("trigger" => "brawl", ),
			"Fling" => array("trigger" => "blast", ),
			"Flight_short" => array(),)
	),
  
	"cthugrosh_ultra" => array(
		"name" => "Cthugrosh",
		"type" => "monster",
		"form" => "Ultra",
		"faction" => "Lords of Cthul",
		"agenda" => "Fiends",
		"energyType" => "Occult",
		"set" => "Rise",
		"rarity" => 3,
		"speed" => 7,
		"defense" => 7,
		"brawl" => 8,
		"brawlBoost" => 3,
		"blast" => 5,
		"blastBoost" => 2,
		"blastRange" => "short",
		"power" => 7,
		"powerBoost" => 2,
		"health" => 5,
		"hyper" => 3,
		"abilities" => array(
			"Sacrifice" => array(),
			"Telekinesis" => array(),
			"Power Gorge" => array("trigger" => "brawl", ),
			"Fling_short" => array("trigger" => "blast", ),
			"Jump_short" => array(),
			"Terrify" => array(),)
	),
  
	"cthugrosh_mega" => array(
		"name" => "Cthugrosh",
		"type" => "monster",
		"form" => "Mega",
		"faction" => "Lords of Cthul",
		"agenda" => "Fiends",
		"energyType" => "Occult",
		"set" => "Rise",
		"setColor" => "blue",
		"rarity" => 5,
		"speed" => 7,
		"defense" => 7,
		"brawl" => 7,
		"brawlBoost" => 1,
		"blast" => 6,
		"blastBoost" => 3,
		"blastRange" => "long",
		"power" => 6,
		"powerBoost" => 2,
		"health" => 5,
		"hyper" => 3,
		"abilities" => array(
			"Overload" => array("trigger" => "blast", ),
			"Jump" => array(),
			"Mire" => array(),
			"Terrify" => array(),
			"Power Sink" => array(),)
	),
  
	"mogroth_alpha" => array(
		"name" => "Mogroth",
		"type" => "monster",
		"form" => "Alpha",
		"faction" => "Lords of Cthul",
		"agenda" => "Fiends",
		"energyType" => "Occult",
		"set" => "I Chomp NY",
		"rarity" => 3,
		"speed" => 6,
		"defense" => 6,
		"brawl" => 6,
		"brawlBoost" => 1,
		"blast" => 6,
		"blastBoost" => 2,
		"blastRange" => "long",
		"power" => 5,
		"powerBoost" => 2,
		"health" => 5,
		"hyper" => 0,
		"abilities" => array(
			"Energy Cycle" => array(),
			"Decoy" => array(),
			"Indirect Fire" => array("color" => "red",),
			"Terrify" => array(),)
	),
  
	"mogroth_ultra" => array(
		"name" => "Mogroth",
		"type" => "monster",
		"form" => "Ultra",
		"faction" => "Lords of Cthul",
		"agenda" => "Fiends",
		"energyType" => "Occult",
		"set" => "I Chomp NY",
		"rarity" => 3,
		"speed" => 6,
		"defense" => 7,
		"brawl" => 7,
		"brawlBoost" => 1,
		"blast" => 6,
		"blastBoost" => 3,
		"blastRange" => "long",
		"power" => 6,
		"powerBoost" => 3,
		"health" => 5,
		"hyper" => 4,
		"abilities" => array(
			"Energy Cycle" => array(),
			"Siphon" => array("trigger" => "blast", ),
			"Weapon Master" => array("trigger" => "blast", ),
			"Decoy" => array(),
			"Indirect Fire" => array("color" => "red",),)
	),
  
	"mogroth_mega" => array(
		"name" => "Mogroth",
		"type" => "monster",
		"form" => "Mega",
		"faction" => "Lords of Cthul",
		"agenda" => "Fiends",
		"energyType" => "Occult",
		"set" => "I Chomp NY",
		"setColor" => "blue",
		"rarity" => 4,
		"speed" => 6,
		"defense" => 7,
		"brawl" => 6,
		"brawlBoost" => 1,
		"blast" => 6,
		"blastBoost" => 3,
		"blastRange" => "long",
		"power" => 6,
		"powerBoost" => 2,
		"health" => 5,
		"hyper" => 6,
		"abilities" => array(
			"Sprint" => array(),
			"Energy Cycle" => array(),
			"Beat Back" => array("trigger" => "blast", ),
			"Indirect Fire" => array("color" => "red",),)
	),
  
	"ulgoth_alpha" => array(
		"name" => "Ulgoth",
		"type" => "monster",
		"form" => "Alpha",
		"faction" => "Lords of Cthul",
		"agenda" => "Fiends",
		"energyType" => "Occult",
		"set" => "I Chomp NY",
		"rarity" => 3,
		"speed" => 5,
		"defense" => 5,
		"brawl" => 6,
		"brawlBoost" => 2,
		"blast" => 6,
		"blastRange" => "long",
		"power" => 6,
		"powerBoost" => 2,
		"health" => 6,
		"hyper" => 0,
		"abilities" => array(
			"Radial Attack" => array("trigger" => "brawl", ),
			"Force Field" => array("color" => "red",),
			"Massive" => array(),
			"Mire" => array(),
			"Volatile" => array(),)
	),
  
	"ulgoth_ultra" => array(
		"name" => "Ulgoth",
		"type" => "monster",
		"form" => "Ultra",
		"faction" => "Lords of Cthul",
		"agenda" => "Fiends",
		"energyType" => "Occult",
		"set" => "I Chomp NY",
		"rarity" => 3,
		"speed" => 6,
		"defense" => 6,
		"brawl" => 8,
		"brawlBoost" => 3,
		"blast" => 8,
		"blastRange" => "long",
		"power" => 8,
		"powerBoost" => 3,
		"health" => 5,
		"hyper" => 3,
		"abilities" => array(
			"Radial Attack" => array("trigger" => "brawl", ),
			"Annihilate" => array(),
			"Massive" => array(),
			"Mire" => array("color" => "blue", ),
			"Volatile" => array(),)
	),
  
	"ulgoth_mega" => array(
		"name" => "Ulgoth",
		"type" => "monster",
		"form" => "Mega",
		"faction" => "Lords of Cthul",
		"agenda" => "Fiends",
		"energyType" => "Occult",
		"set" => "I Chomp NY",
		"setColor" => "blue",
		"rarity" => 4,
		"speed" => 5,
		"defense" => 5,
		"brawl" => 7,
		"brawlBoost" => 3,
		"blast" => 7,
		"blastBoost" => 2,
		"blastRange" => "long",
		"power" => 7,
		"powerBoost" => 3,
		"health" => 6,
		"hyper" => 3,
		"abilities" => array(
			"Beat Back" => array("trigger" => "brawl", ),
			"Massive" => array(),
			"Mire" => array("color" => "blue", ),
			"Volatile" => array(),)
	),
  
	"yasheth_alpha" => array(
		"name" => "Yasheth",
		"type" => "monster",
		"form" => "Alpha",
		"faction" => "Lords of Cthul",
		"agenda" => "Fiends",
		"energyType" => "Occult",
		"set" => "Rise",
		"rarity" => 3,
		"speed" => 6,
		"defense" => 6,
		"brawl" => 7,
		"brawlBoost" => 2,
		"power" => 6,
		"powerBoost" => 2,
		"health" => 5,
		"hyper" => 0,
		"abilities" => array(
			"Leach" => array(),
			"Vampirism" => array("trigger" => "brawl", ),
			"Power Sink" => array(),
			"Side Step" => array("color" => "blue", ),)
	),
  
	"yasheth_ultra" => array(
		"name" => "Yasheth",
		"type" => "monster",
		"form" => "Ultra",
		"faction" => "Lords of Cthul",
		"agenda" => "Fiends",
		"energyType" => "Occult",
		"set" => "Rise",
		"rarity" => 3,
		"speed" => 7,
		"defense" => 7,
		"brawl" => 8,
		"brawlBoost" => 3,
		"power" => 7,
		"powerBoost" => 2,
		"health" => 5,
		"hyper" => 3,
		"abilities" => array(
			"Leach" => array(),
			"Energy Drain" => array("trigger" => "brawl", ),
			"Vampirism" => array("trigger" => "brawl", ),
			"Flight_short" => array(),
			"Power Sink" => array(),)
	),
  
	"yasheth_mega" => array(
		"name" => "Yasheth",
		"type" => "monster",
		"form" => "Mega",
		"faction" => "Lords of Cthul",
		"agenda" => "Fiends",
		"energyType" => "Occult",
		"set" => "Rise",
		"setColor" => "blue",
		"rarity" => 5,
		"speed" => 8,
		"defense" => 7,
		"brawl" => 7,
		"brawlBoost" => 4,
		"power" => 6,
		"powerBoost" => 2,
		"health" => 5,
		"hyper" => 3,
		"abilities" => array(
			"Annihilate" => array(),
			"Berserk" => array("color" => "blue", ),
			"Cloak" => array(),
			"Disable" => array(),
			"Flight" => array(),)
	),
  
	"tower_of_corruption" => array(
		"name" => "Tower of Corruption",
		"type" => "building",
		"hazard" => "rubble",
		"faction" => "Lords of Cthul",
		"agenda" => "Fiends",
		"set" => "All Your Base",
		"rarity" => 3,
		"defense" => 4,
		"energy" => 5,
		"brawl" => 3,
		"brawlBoost" => 1,
		"blast" => 2,
		"blastBoost" => 1,
		"blastRange" => "short",
		"abilities" => array(
			"Summon" => array(),
			"Manufacture" => array(),
			"Transmutation" => array("trigger" => "blast", ),)
	),
  
	"cthulabite_grunt" => array(
		"name" => "Cthulabite",
		"type" => "unit",
		"class" => "Grunt",
		"faction" => "Lords of Cthul",
		"agenda" => "Fiends",
		"energyType" => "Occult",
		"set" => "All Your Base",
		"rarity" => 3,
		"speed" => 5,
		"defense" => 4,
		"brawl" => 3,
		"blast" => 3,
		"blastRange" => "short",
		"cost" => 2,
		"abilities" => array(
			"Multi-shot" => array("trigger" => "blast", ),
			"Distract" => array(),
			"Flight" => array(),
			"Weaken" => array(),)
	),
  
	"corrupter_grunt" => array(
		"name" => "Corrupter",
		"type" => "unit",
		"class" => "Grunt",
		"faction" => "Lords of Cthul",
		"agenda" => "Fiends",
		"energyType" => "Occult",
		"set" => "I Chomp NY",
		"rarity" => 1,
		"speed" => 5,
		"defense" => 3,
		"brawl" => 2,
		"cost" => 1,
		"abilities" => array(
			"Flank" => array("color" => "red",),
			"Jam" => array(),)
	),
  
	"corrupter_elite" => array(
		"name" => "Corrupter",
		"type" => "unit",
		"class" => "Elite",
		"faction" => "Lords of Cthul",
		"agenda" => "Fiends",
		"energyType" => "Occult",
		"set" => "I Chomp NY",
		"rarity" => 2,
		"speed" => 5,
		"defense" => 3,
		"brawl" => 2,
		"brawlBoost" => 1,
		"cost" => 2,
		"abilities" => array(
			"Overload" => array("color" => "red","trigger" => "brawl", ),
			"Flank" => array("color" => "red",),
			"Jam" => array(),
			"Leadership" => array(),)
	),
  
	"meat_slave_grunt" => array(
		"name" => "Meat Slave",
		"type" => "unit",
		"class" => "Grunt",
		"faction" => "Lords of Cthul",
		"agenda" => "Fiends",
		"energyType" => "Occult",
		"set" => "Rise",
		"rarity" => 3,
		"speed" => 4,
		"defense" => 2,
		"cost" => 1,
		"abilities" => array(
			"Bleed" => array(),
			"Incubator" => array(),)
	),
  
	"snatcher_grunt" => array(
		"name" => "Snatcher",
		"type" => "unit",
		"class" => "Grunt",
		"faction" => "Lords of Cthul",
		"agenda" => "Fiends",
		"energyType" => "Occult",
		"set" => "I Chomp NY",
		"rarity" => 2,
		"speed" => 5,
		"defense" => 2,
		"brawl" => 2,
		"cost" => 1,
		"abilities" => array(
			"Manufacture" => array(),
			"Jump" => array(),)
	),
  
	"snatcher_elite" => array(
		"name" => "Snatcher",
		"type" => "unit",
		"class" => "Elite",
		"faction" => "Lords of Cthul",
		"agenda" => "Fiends",
		"energyType" => "Occult",
		"set" => "I Chomp NY",
		"rarity" => 3,
		"speed" => 5,
		"defense" => 2,
		"brawl" => 2,
		"brawlBoost" => 1,
		"cost" => 2,
		"abilities" => array(
			"Manufacture" => array(),
			"Jump" => array(),
			"Leadership" => array(),)
	),
  
	"snatcher_shadow" => array(
		"name" => "Snatcher",
		"type" => "unit",
		"form" => "Shadow",
		"class" => "Grunt",
		"faction" => "Lords of Cthul",
		"agenda" => "Fiends",
		"energyType" => "Occult",
		"set" => "I Chomp NY",
		"setColor" => "blue",
		"rarity" => 4,
		"speed" => 5,
		"defense" => 2,
		"brawl" => 2,
		"cost" => 2,
		"abilities" => array(
			"Manufacture" => array(),
			"Cloak" => array(),
			"Jump" => array(),)
	),
  
	"spitter_grunt" => array(
		"name" => "Spitter",
		"type" => "unit",
		"class" => "Grunt",
		"faction" => "Lords of Cthul",
		"agenda" => "Fiends",
		"energyType" => "Occult",
		"set" => "Rise",
		"rarity" => 1,
		"speed" => 4,
		"defense" => 2,
		"blast" => 1,
		"blastBoost" => 1,
		"blastRange" => "short",
		"cost" => 1,
		"abilities" => array(
			"Extinguish" => array(),)
	),
  
	"spitter_elite" => array(
		"name" => "Spitter",
		"type" => "unit",
		"class" => "Elite",
		"faction" => "Lords of Cthul",
		"agenda" => "Fiends",
		"energyType" => "Occult",
		"set" => "Rise",
		"rarity" => 2,
		"speed" => 4,
		"defense" => 2,
		"blast" => 1,
		"blastBoost" => 2,
		"blastRange" => "short",
		"cost" => 2,
		"abilities" => array(
			"Extinguish" => array(),
			"Leadership" => array(),
			"Radar" => array("color" => "red",),)
	),
  
	"squix_grunt" => array(
		"name" => "Squix",
		"type" => "unit",
		"class" => "Grunt",
		"faction" => "Lords of Cthul",
		"agenda" => "Fiends",
		"energyType" => "Occult",
		"set" => "Rise",
		"rarity" => 1,
		"speed" => 5,
		"defense" => 3,
		"brawl" => 1,
		"blast" => 2,
		"blastRange" => "short",
		"cost" => 1,
		"abilities" => array(
			"Distract" => array(),
			"Flight" => array(),)
	),
  
	"squix_elite" => array(
		"name" => "Squix",
		"type" => "unit",
		"class" => "Elite",
		"faction" => "Lords of Cthul",
		"agenda" => "Fiends",
		"energyType" => "Occult",
		"set" => "Rise",
		"rarity" => 2,
		"speed" => 5,
		"defense" => 3,
		"brawl" => 1,
		"brawlBoost" => 1,
		"blast" => 2,
		"blastBoost" => 1,
		"blastRange" => "short",
		"cost" => 2,
		"abilities" => array(
			"Distract" => array(),
			"Flight" => array(),
			"Force Field" => array("color" => "red",),
			"Leadership" => array(),)
	),
  
	"tanglix_grunt" => array(
		"name" => "Tanglix",
		"type" => "unit",
		"class" => "Grunt",
		"faction" => "Lords of Cthul",
		"agenda" => "Fiends",
		"energyType" => "Occult",
		"set" => "All Your Base",
		"rarity" => 1,
		"speed" => 4,
		"defense" => 3,
		"brawl" => 3,
		"blast" => 3,
		"blastRange" => "short",
		"cost" => 1,
		"abilities" => array(
			"Radial Attack" => array("trigger" => "brawl", ),
			"Halt" => array(),)
	),
  
	"tanglix_elite" => array(
		"name" => "Tanglix",
		"type" => "unit",
		"class" => "Elite",
		"faction" => "Lords of Cthul",
		"agenda" => "Fiends",
		"energyType" => "Occult",
		"set" => "All Your Base",
		"rarity" => 2,
		"speed" => 4,
		"defense" => 3,
		"brawl" => 3,
		"brawlBoost" => 1,
		"blast" => 3,
		"blastBoost" => 1,
		"blastRange" => "short",
		"cost" => 2,
		"abilities" => array(
			"Radial Attack" => array("trigger" => "brawl", ),
			"Halt" => array(),
			"Leadership" => array(),)
	),
  
	"tanglix_shadow" => array(
		"name" => "Tanglix",
		"type" => "unit",
		"form" => "Shadow",
		"class" => "Elite",
		"faction" => "Lords of Cthul",
		"agenda" => "Fiends",
		"energyType" => "Occult",
		"set" => "All Your Base",
		"setColor" => "blue",
		"rarity" => 4,
		"speed" => 4,
		"defense" => 3,
		"brawl" => 3,
		"brawlBoost" => 1,
		"blast" => 3,
		"blastBoost" => 1,
		"blastRange" => "short",
		"cost" => 3,
		"abilities" => array(
			"Radial Attack" => array("trigger" => "brawl", ),
			"Cloak" => array(),
			"Halt" => array(),
			"Leadership" => array(),)
	),
  
	"task_master_elite" => array(
		"name" => "Task Master",
		"type" => "unit",
		"class" => "Elite",
		"faction" => "Lords of Cthul",
		"agenda" => "Fiends",
		"energyType" => "Occult",
		"set" => "Rise",
		"rarity" => 3,
		"speed" => 5,
		"defense" => 4,
		"brawl" => 3,
		"brawlBoost" => 1,
		"cost" => 2,
		"abilities" => array(
			"Telekinesis" => array(),
			"Fling" => array("trigger" => "brawl", ),
			"Motivator" => array(),)
	),

	"task_master_shadow" => array(
		"name" => "Task Master",
		"type" => "unit",
		"form" => "Shadow",
		"class" => "Elite",
		"faction" => "Lords of Cthul",
		"agenda" => "Fiends",
		"energyType" => "Occult",
		"set" => "Rise",
		"setColor" => "blue",
		"rarity" => 5,
		"speed" => 5,
		"defense" => 4,
		"brawl" => 3,
		"brawlBoost" => 1,
		"cost" => 3,
		"abilities" => array(
			"Telekinesis" => array(),
			"Fling" => array("trigger" => "brawl", ),
			"Cloak" => array(),
			"Motivator" => array(),)
	),
  
