


/*    =============    Martian Menace    =============    */

	"ares_mothership_alpha" => array(
		"name" => "Ares Mothership",
		"type" => "monster",
		"form" => "Alpha",
		"faction" => "Martian Menace",
		"agenda" => "Invaders",
		"energyType" => "Radioactive",
		"set" => "Rise",
		"rarity" => 3,
		"speed" => 7,
		"defense" => 5,
		"brawl" => 6,
		"brawlBoost" => 1,
		"blast" => 6,
		"blastBoost" => 2,
		"blastRange" => "short",
		"power" => 5,
		"powerBoost" => 1,
		"health" => 6,
		"hyper" => 0,
		"abilities" => array(
			"Abduct" => array(),
			"Transport" => array(),
			"Manufacture" => array(),
			"Flight_short" => array(),
			"Steady" => array(),
			"Power Sink" => array(),)
	),
  
	"ares_mothership_ultra" => array(
		"name" => "Ares Mothership",
		"type" => "monster",
		"form" => "Ultra",
		"faction" => "Martian Menace",
		"agenda" => "Invaders",
		"energyType" => "Radioactive",
		"set" => "Rise",
		"rarity" => 3,
		"speed" => 7,
		"defense" => 6,
		"brawl" => 6,
		"brawlBoost" => 2,
		"blast" => 6,
		"blastBoost" => 3,
		"blastRange" => "long",
		"power" => 5,
		"powerBoost" => 2,
		"health" => 6,
		"hyper" => 5,
		"abilities" => array(
			"Abduct" => array(),
			"Manufacture" => array(),
			"Flight_short" => array(),
			"Force Field" => array("color" => "blue", ),
			"Negation" => array(),
			"Power Sink" => array(),)
	),
  
	"ares_mothership_mega" => array(
		"name" => "Ares Mothership",
		"type" => "monster",
		"form" => "Mega",
		"faction" => "Martian Menace",
		"agenda" => "Invaders",
		"energyType" => "Radioactive",
		"set" => "Rise",
		"setColor" => "blue",
		"rarity" => 5,
		"speed" => 8,
		"defense" => 6,
		"brawl" => 8,
		"brawlBoost" => 3,
		"blast" => 5,
		"blastBoost" => 2,
		"blastRange" => "long",
		"power" => 5,
		"powerBoost" => 1,
		"health" => 6,
		"hyper" => 5,
		"abilities" => array(
			"Abduct" => array(),
			"Manufacture" => array(),
			"Marker" => array(),
			"Flight_short" => array(),
			"Resilience" => array(),)
	),
  
	"deimos-9_alpha" => array(
		"name" => "Deimos-9",
		"type" => "monster",
		"form" => "Alpha",
		"faction" => "Martian Menace",
		"agenda" => "Invaders",
		"energyType" => "Radioactive",
		"set" => "Rise",
		"rarity" => 3,
		"speed" => 6,
		"defense" => 6,
		"brawl" => 7,
		"brawlBoost" => 2,
		"blast" => 4,
		"blastRange" => "short",
		"power" => 6,
		"powerBoost" => 2,
		"health" => 5,
		"hyper" => 0,
		"abilities" => array(
			"Power Drain" => array("trigger" => "brawl", ),
			"Hit and Run" => array("color" => "blue", "trigger" => "blast", ),
			"Power Gorge" => array("trigger" => "blast", ),
			"Penetrator" => array(),)
	),
  
	"deimos-9_ultra" => array(
		"name" => "Deimos-9",
		"type" => "monster",
		"form" => "Ultra",
		"faction" => "Martian Menace",
		"agenda" => "Invaders",
		"energyType" => "Radioactive",
		"set" => "Rise",
		"rarity" => 3,
		"speed" => 6,
		"defense" => 6,
		"brawl" => 8,
		"brawlBoost" => 3,
		"blast" => 4,
		"blastRange" => "short",
		"power" => 7,
		"powerBoost" => 2,
		"health" => 5,
		"hyper" => 3,
		"abilities" => array(
			"Lightning Attack" => array("trigger" => "brawl", ),
			"Siphon" => array("trigger" => "brawl", ),
			"Hit and Run" => array("color" => "blue", "trigger" => "blast", ),
			"Power Gorge" => array("trigger" => "blast", ),
			"Penetrator" => array(),)
	),
  
	"deimos-9_mega" => array(
		"name" => "Deimos-9",
		"type" => "monster",
		"form" => "Mega",
		"faction" => "Martian Menace",
		"agenda" => "Invaders",
		"energyType" => "Radioactive",
		"set" => "Rise",
		"setColor" => "blue",
		"rarity" => 5,
		"speed" => 6,
		"defense" => 6,
		"brawl" => 8,
		"brawlBoost" => 4,
		"blast" => 4,
		"blastRange" => "short",
		"power" => 5,
		"powerBoost" => 2,
		"health" => 6,
		"hyper" => 3,
		"abilities" => array(
			"Chain Attack" => array("trigger" => "brawl", ),
			"Disrupt" => array("trigger" => "brawl", ),
			"Vampirism" => array("trigger" => "brawl", ),
			"Climb" => array(),
			"Low Flyer" => array("color" => "blue", ),)
	),
  
	"galaxius-4_alpha_galaxius_alpha" => array(
		"name" => "Galaxius-4",
		"type" => "monster",
		"form" => "Galaxius Alpha",
		"faction" => "Martian Menace",
		"agenda" => "Invaders",
		"energyType" => "Radioactive",
		"set" => "All Your Base",
		"rarity" => 3,
		"speed" => 5,
		"defense" => 5,
		"brawl" => 2,
		"brawlBoost" => 1,
		"blast" => 3,
		"blastBoost" => 1,
		"blastRange" => "short",
		"health" => 5,
		"hyper" => 0,
		"abilities" => array(
			"Climb" => array(),
			"Logistics" => array(),
			"Radar" => array("color" => "red",),
			"Satellite Support" => array(),)
	),
  
	"galaxius-4_alpha_galaxius_beta" => array(
		"name" => "Galaxius-4",
		"type" => "monster",
		"form" => "Galaxius Beta",
		"faction" => "Martian Menace",
		"agenda" => "Invaders",
		"energyType" => "Radioactive",
		"set" => "All Your Base",
		"rarity" => 3,
		"speed" => 5,
		"defense" => 5,
		"brawl" => 3,
		"brawlBoost" => 1,
		"blast" => 3,
		"blastBoost" => 1,
		"blastRange" => "short",
		"health" => 5,
		"hyper" => 0,
		"abilities" => array(
			"Climb" => array(),
			"Cloak" => array("color" => "red",),
			"Distract" => array(),
			"Weaken" => array(),)
	),
  
	"galaxius-4_alpha_galaxius_core" => array(
		"name" => "Galaxius-4",
		"type" => "monster",
		"form" => "Galaxius Core",
		"faction" => "Martian Menace",
		"agenda" => "Invaders",
		"energyType" => "Radioactive",
		"set" => "All Your Base",
		"rarity" => 3,
		"speed" => 7,
		"defense" => 4,
		"brawl" => 1,
		"brawlBoost" => 1,
		"blast" => 3,
		"blastBoost" => 1,
		"blastRange" => "short",
		"health" => 5,
		"hyper" => 0,
		"abilities" => array(
			"Telekinesis" => array(),
			"Fling" => array("trigger" => "blast", ),
			"Toss" => array("trigger" => "blast", ),
			"Flight_short" => array(),)
	),
  
	"galaxius-4_alpha_galaxius_gamma" => array(
		"name" => "Galaxius-4",
		"type" => "monster",
		"form" => "Galaxius Gamma",
		"faction" => "Martian Menace",
		"agenda" => "Invaders",
		"energyType" => "Radioactive",
		"set" => "All Your Base",
		"rarity" => 3,
		"speed" => 5,
		"defense" => 5,
		"brawl" => 3,
		"brawlBoost" => 1,
		"blast" => 3,
		"blastBoost" => 1,
		"blastRange" => "long",
		"health" => 5,
		"hyper" => 0,
		"abilities" => array(
			"Power Drain" => array("color" => "red","trigger" => "blast", ),
			"Explosion" => array("trigger" => "blast", ),
			"Climb" => array(),
			"Motivator" => array(),)
	),
  
	"galaxius-4_ultra" => array(
		"name" => "Galaxius-4",
		"type" => "monster",
		"form" => "Ultra",
		"faction" => "Martian Menace",
		"agenda" => "Invaders",
		"energyType" => "Mechanical",
		"set" => "All Your Base",
		"rarity" => 3,
		"speed" => 7,
		"defense" => 7,
		"brawl" => 8,
		"brawlBoost" => 4,
		"blast" => 7,
		"blastBoost" => 3,
		"blastRange" => "long",
		"power" => 8,
		"powerBoost" => 2,
		"health" => 5,
		"hyper" => 3,
		"abilities" => array(
			"Fission" => array(),
			"Overload" => array("trigger" => "brawl", ),
			"Radial Attack_short" => array("trigger" => "brawl", ),
			"Lightning Attack" => array("trigger" => "blast", ),
			"Flight_short" => array(),)
	),
  
	"galaxius-4_mega" => array(
		"name" => "Galaxius-4",
		"type" => "monster",
		"form" => "Mega",
		"faction" => "Martian Menace",
		"agenda" => "Invaders",
		"energyType" => "Radioactive",
		"set" => "All Your Base",
		"setColor" => "blue",
		"rarity" => 4,
		"speed" => 6,
		"defense" => 6,
		"brawl" => 7,
		"brawlBoost" => 2,
		"blast" => 8,
		"blastBoost" => 3,
		"blastRange" => "short",
		"power" => 7,
		"powerBoost" => 2,
		"health" => 5,
		"hyper" => 5,
		"abilities" => array(
			"Telekinesis" => array("color" => "blue", ),
			"Beat Back" => array("trigger" => "blast", ),
			"Vampirism" => array("trigger" => "blast", ),
			"Flight" => array(),)
	),
  
	"phobos-7_alpha" => array(
		"name" => "Phobos-7",
		"type" => "monster",
		"form" => "Alpha",
		"faction" => "Martian Menace",
		"agenda" => "Invaders",
		"energyType" => "Radioactive",
		"set" => "I Chomp NY",
		"rarity" => 3,
		"speed" => 6,
		"defense" => 6,
		"brawl" => 6,
		"brawlBoost" => 1,
		"blast" => 6,
		"blastBoost" => 3,
		"blastRange" => "long",
		"power" => 5,
		"powerBoost" => 2,
		"health" => 6,
		"hyper" => 0,
		"abilities" => array(
			"Marker" => array(),
			"Disintegrate" => array("trigger" => "blast", ),
			"Multi-shot" => array("trigger" => "blast", ),
			"Radar" => array("color" => "red",),)
	),
  
	"phobos-7_ultra" => array(
		"name" => "Phobos-7",
		"type" => "monster",
		"form" => "Ultra",
		"faction" => "Martian Menace",
		"agenda" => "Invaders",
		"energyType" => "Radioactive",
		"set" => "I Chomp NY",
		"rarity" => 3,
		"speed" => 6,
		"defense" => 6,
		"brawl" => 6,
		"brawlBoost" => 1,
		"blast" => 9,
		"blastBoost" => 4,
		"blastRange" => "long",
		"power" => 5,
		"powerBoost" => 2,
		"health" => 5,
		"hyper" => 3,
		"abilities" => array(
			"Disintegrate" => array("trigger" => "blast", ),
			"Fling" => array("trigger" => "blast", ),
			"Lightning Attack" => array("trigger" => "blast", ),
			"Radar" => array("color" => "blue", ),)
	),
  
	"phobos-7_mega" => array(
		"name" => "Phobos-7",
		"type" => "monster",
		"form" => "Mega",
		"faction" => "Martian Menace",
		"agenda" => "Invaders",
		"energyType" => "Radioactive",
		"set" => "I Chomp NY",
		"setColor" => "blue",
		"rarity" => 4,
		"speed" => 6,
		"defense" => 5,
		"brawl" => 7,
		"brawlBoost" => 3,
		"blast" => 9,
		"blastBoost" => 3,
		"blastRange" => "short",
		"power" => 5,
		"powerBoost" => 1,
		"health" => 6,
		"hyper" => 3,
		"abilities" => array(
			"Lightning Attack" => array("trigger" => "brawl", ),
			"Follow Through" => array("trigger" => "blast", ),
			"Hit and Run" => array("trigger" => "blast", ),
			"Armor Piercing" => array("color" => "red",),
			"Radar" => array("color" => "blue", ),)
	),
  
	"tharsis-5_alpha" => array(
		"name" => "Tharsis-5",
		"type" => "monster",
		"form" => "Alpha",
		"faction" => "Martian Menace",
		"agenda" => "Invaders",
		"energyType" => "Radioactive",
		"set" => "I Chomp NY",
		"rarity" => 3,
		"speed" => 6,
		"defense" => 5,
		"brawl" => 7,
		"brawlBoost" => 2,
		"blast" => 6,
		"blastBoost" => 1,
		"blastRange" => "short",
		"power" => 6,
		"powerBoost" => 2,
		"health" => 5,
		"hyper" => 0,
		"abilities" => array(
			"Energy Cycle" => array("color" => "blue", ),
			"Armored" => array(),
			"Flight" => array(),
			"Super Rampage" => array(),)
	),
  
	"tharsis-5_ultra" => array(
		"name" => "Tharsis-5",
		"type" => "monster",
		"form" => "Ultra",
		"faction" => "Martian Menace",
		"agenda" => "Invaders",
		"energyType" => "Radioactive",
		"set" => "I Chomp NY",
		"rarity" => 3,
		"speed" => 5,
		"defense" => 7,
		"brawl" => 6,
		"brawlBoost" => 3,
		"blast" => 6,
		"blastBoost" => 2,
		"blastRange" => "short",
		"power" => 7,
		"powerBoost" => 3,
		"health" => 5,
		"hyper" => 4,
		"abilities" => array(
			"Beat Back" => array("trigger" => "brawl", ),
			"Crunch" => array("trigger" => "brawl", ),
			"Energy Drain" => array("color" => "blue", "trigger" => "blast", ),
			"Flight_short" => array(),
			"Super Rampage" => array(),)
	),
  
	"tharsis-5_mega" => array(
		"name" => "Tharsis-5",
		"type" => "monster",
		"form" => "Mega",
		"faction" => "Martian Menace",
		"agenda" => "Invaders",
		"energyType" => "Radioactive",
		"set" => "I Chomp NY",
		"setColor" => "blue",
		"rarity" => 4,
		"speed" => 6,
		"defense" => 7,
		"brawl" => 6,
		"brawlBoost" => 2,
		"blast" => 6,
		"blastBoost" => 2,
		"blastRange" => "short",
		"power" => 9,
		"powerBoost" => 3,
		"health" => 5,
		"hyper" => 3,
		"abilities" => array(
			"Energy Sap" => array("color" => "blue", "trigger" => "blast", ),
			"Flight" => array(),
			"Super Smash" => array(),
			"Super Strength" => array(),)
	),
  
	"arsia_outpost" => array(
		"name" => "Arsia Outpost",
		"type" => "building",
		"hazard" => "radiation",
		"faction" => "Martian Menace",
		"agenda" => "Invaders",
		"set" => "All Your Base",
		"rarity" => 3,
		"defense" => 6,
		"energy" => 5,
		"blast" => 3,
		"blastRange" => "short",
		"abilities" => array(
			"Beacon" => array(),
			"Ground Control" => array("color" => "red",),
			"No-Fly Zone" => array(),
			"Radiated Zone" => array(),)
	),
  
	"despoiler_grunt" => array(
		"name" => "Despoiler",
		"type" => "unit",
		"class" => "Grunt",
		"faction" => "Martian Menace",
		"agenda" => "Invaders",
		"energyType" => "Radioactive",
		"set" => "All Your Base",
		"rarity" => 1,
		"speed" => 5,
		"defense" => 3,
		"brawl" => 1,
		"blast" => 2,
		"blastRange" => "long",
		"cost" => 1,
		"abilities" => array(
			"Climb" => array(),
			"Sniper" => array(),)
	),
  
	"despoiler_elite" => array(
		"name" => "Despoiler",
		"type" => "unit",
		"class" => "Elite",
		"faction" => "Martian Menace",
		"agenda" => "Invaders",
		"energyType" => "Radioactive",
		"set" => "All Your Base",
		"rarity" => 2,
		"speed" => 5,
		"defense" => 3,
		"brawl" => 1,
		"brawlBoost" => 1,
		"blast" => 2,
		"blastBoost" => 1,
		"blastRange" => "long",
		"cost" => 2,
		"abilities" => array(
			"Climb" => array(),
			"Leadership" => array(),
			"Sniper" => array("color" => "red",),)
	),
  
	"despoiler_shadow" => array(
		"name" => "Despoiler",
		"type" => "unit",
		"form" => "Shadow",
		"class" => "Elite",
		"faction" => "Martian Menace",
		"agenda" => "Invaders",
		"energyType" => "Radioactive",
		"set" => "All Your Base",
		"setColor" => "blue",
		"rarity" => 4,
		"speed" => 5,
		"defense" => 3,
		"brawl" => 1,
		"brawlBoost" => 1,
		"blast" => 2,
		"blastBoost" => 1,
		"blastRange" => "long",
		"cost" => 3,
		"abilities" => array(
			"Climb" => array(),
			"Cloak" => array(),
			"Leadership" => array(),
			"Sniper" => array("color" => "red",),)
	),
  
	"hunter_grunt" => array(
		"name" => "Hunter",
		"type" => "unit",
		"class" => "Grunt",
		"faction" => "Martian Menace",
		"agenda" => "Invaders",
		"energyType" => "Radioactive",
		"set" => "Rise",
		"rarity" => 1,
		"speed" => 6,
		"defense" => 2,
		"blast" => 3,
		"blastRange" => "long",
		"cost" => 1,
		"abilities" => array(
			"Flight" => array(),
			"Sniper" => array(),)
	),
  
	"hunter_elite" => array(
		"name" => "Hunter",
		"type" => "unit",
		"class" => "Elite",
		"faction" => "Martian Menace",
		"agenda" => "Invaders",
		"energyType" => "Radioactive",
		"set" => "Rise",
		"rarity" => 3,
		"speed" => 6,
		"defense" => 2,
		"blast" => 3,
		"blastBoost" => 1,
		"blastRange" => "long",
		"cost" => 2,
		"abilities" => array(
			"Flight" => array(),
			"Leadership" => array(),
			"Sniper" => array(),)
	),
  
	"hunter_shadow" => array(
		"name" => "Hunter",
		"type" => "unit",
		"form" => "Shadow",
		"class" => "Elite",
		"faction" => "Martian Menace",
		"agenda" => "Invaders",
		"energyType" => "Radioactive",
		"set" => "Rise",
		"setColor" => "blue",
		"rarity" => 5,
		"speed" => 6,
		"defense" => 3,
		"blast" => 3,
		"blastBoost" => 1,
		"blastRange" => "long",
		"cost" => 3,
		"abilities" => array(
			"Cloak" => array(),
			"Flight" => array(),
			"Leadership" => array(),
			"Sniper" => array(),)
	),
  
	"marauder_grunt" => array(
		"name" => "Marauder",
		"type" => "unit",
		"class" => "Grunt",
		"faction" => "Martian Menace",
		"agenda" => "Invaders",
		"energyType" => "Radioactive",
		"set" => "I Chomp NY",
		"rarity" => 1,
		"speed" => 6,
		"defense" => 2,
		"blast" => 2,
		"blastRange" => "long",
		"cost" => 1,
		"abilities" => array(
			"Explosion" => array("trigger" => "blast", ),
			"Flight" => array(),
			"Indirect Fire" => array(),)
	),
  
	"marauder_elite" => array(
		"name" => "Marauder",
		"type" => "unit",
		"class" => "Elite",
		"faction" => "Martian Menace",
		"agenda" => "Invaders",
		"energyType" => "Radioactive",
		"set" => "I Chomp NY",
		"rarity" => 2,
		"speed" => 6,
		"defense" => 2,
		"blast" => 2,
		"blastBoost" => 1,
		"blastRange" => "long",
		"cost" => 2,
		"abilities" => array(
			"Explosion" => array("trigger" => "blast", ),
			"Flight" => array(),
			"Indirect Fire" => array(),
			"Leadership" => array(),)
	),
  
	"marauder_shadow" => array(
		"name" => "Marauder",
		"type" => "unit",
		"form" => "Shadow",
		"class" => "Grunt",
		"faction" => "Martian Menace",
		"agenda" => "Invaders",
		"energyType" => "Radioactive",
		"set" => "I Chomp NY",
		"setColor" => "blue",
		"rarity" => 4,
		"speed" => 6,
		"defense" => 2,
		"blast" => 2,
		"blastRange" => "long",
		"cost" => 2,
		"abilities" => array(
			"Explosion" => array("trigger" => "blast", ),
			"Cloak" => array(),
			"Flight" => array(),
			"Indirect Fire" => array(),)
	),
  
	"nullifier_pod_grunt" => array(
		"name" => "Nullifier Pod",
		"type" => "unit",
		"class" => "Grunt",
		"faction" => "Martian Menace",
		"agenda" => "Invaders",
		"energyType" => "Radioactive",
		"set" => "All Your Base",
		"rarity" => 3,
		"speed" => 2,
		"defense" => 3,
		"cost" => 1,
		"abilities" => array(
			"Cargo" => array(),
			"Hover" => array(),
			"Mire" => array(),
			"Weaken" => array(),)
	),
  
	"power_pod_grunt" => array(
		"name" => "Power Pod",
		"type" => "unit",
		"class" => "Grunt",
		"faction" => "Martian Menace",
		"agenda" => "Invaders",
		"energyType" => "Radioactive",
		"set" => "Rise",
		"rarity" => 3,
		"speed" => 2,
		"defense" => 2,
		"cost" => 1,
		"abilities" => array(
			"Refuel" => array(),
			"Amplify" => array(),
			"Cargo" => array(),
			"Hover" => array(),)
	),
  
	"reaper_grunt" => array(
		"name" => "Reaper",
		"type" => "unit",
		"class" => "Grunt",
		"faction" => "Martian Menace",
		"agenda" => "Invaders",
		"energyType" => "Radioactive",
		"set" => "I Chomp NY",
		"rarity" => 2,
		"speed" => 5,
		"defense" => 3,
		"brawl" => 2,
		"blast" => 1,
		"blastRange" => "short",
		"cost" => 1,
		"abilities" => array(
			"Energy Cycle" => array("color" => "red",),
			"Climb" => array(),
			"Penetrator" => array(),)
	),
  
	"reaper_elite" => array(
		"name" => "Reaper",
		"type" => "unit",
		"class" => "Elite",
		"faction" => "Martian Menace",
		"agenda" => "Invaders",
		"energyType" => "Radioactive",
		"set" => "I Chomp NY",
		"rarity" => 3,
		"speed" => 5,
		"defense" => 3,
		"brawl" => 2,
		"brawlBoost" => 1,
		"blast" => 1,
		"blastBoost" => 1,
		"blastRange" => "short",
		"cost" => 2,
		"abilities" => array(
			"Energy Cycle" => array("color" => "red",),
			"Climb" => array(),
			"Leadership" => array(),
			"Penetrator" => array(),)
	),
  
	"saucer_grunt" => array(
		"name" => "Saucer",
		"type" => "unit",
		"class" => "Grunt",
		"faction" => "Martian Menace",
		"agenda" => "Invaders",
		"energyType" => "Radioactive",
		"set" => "Rise",
		"rarity" => 1,
		"speed" => 5,
		"defense" => 2,
		"cost" => 1,
		"abilities" => array(
			"Abduct" => array(),
			"Transport" => array(),
			"Flight" => array(),
			"Ground Control" => array(),)
	),
  
	"vanguard_grunt" => array(
		"name" => "Vanguard",
		"type" => "unit",
		"class" => "Grunt",
		"faction" => "Martian Menace",
		"agenda" => "Invaders",
		"energyType" => "Radioactive",
		"set" => "Rise",
		"rarity" => 1,
		"speed" => 6,
		"defense" => 2,
		"blast" => 1,
		"blastBoost" => 1,
		"blastRange" => "short",
		"cost" => 1,
		"abilities" => array(
			"Power Gorge" => array("trigger" => "blast", ),
			"Flight" => array(),)
	),

	"vanguard_elite" => array(
		"name" => "Vanguard",
		"type" => "unit",
		"class" => "Elite",
		"faction" => "Martian Menace",
		"agenda" => "Invaders",
		"energyType" => "Radioactive",
		"set" => "Rise",
		"rarity" => 2,
		"speed" => 6,
		"defense" => 2,
		"blast" => 1,
		"blastBoost" => 2,
		"blastRange" => "short",
		"cost" => 2,
		"abilities" => array(
			"Power Gorge" => array("trigger" => "blast", ),
			"Flight" => array(),
			"Leadership" => array(),)
	),
