


/*    =============    Planet Eaters    =============    */

	"gorghadra_alpha" => array(
		"name" => "Gorghadra",
		"type" => "monster",
		"form" => "Alpha",
		"faction" => "Planet Eaters",
		"agenda" => "Destroyers",
		"energyType" => "Cosmic",
		"set" => "Rise",
		"rarity" => 3,
		"speed" => 6,
		"defense" => 5,
		"brawl" => 8,
		"brawlBoost" => 2,
		"blast" => 4,
		"blastBoost" => 2,
		"blastRange" => "short",
		"power" => 7,
		"powerBoost" => 2,
		"health" => 7,
		"hyper" => 0,
		"abilities" => array(
			"Chain Reaction" => array("trigger" => "brawl", ),
			"Energy Sap" => array("trigger" => "blast", ),
			"Super Rampage" => array(),
			"Riled" => array("color" => "blue", ),)
	),
  
	"gorghadra_ultra" => array(
		"name" => "Gorghadra",
		"type" => "monster",
		"form" => "Ultra",
		"faction" => "Planet Eaters",
		"agenda" => "Destroyers",
		"energyType" => "Cosmic",
		"set" => "Rise",
		"rarity" => 3,
		"speed" => 6,
		"defense" => 7,
		"brawl" => 9,
		"brawlBoost" => 3,
		"blast" => 5,
		"blastBoost" => 3,
		"blastRange" => "short",
		"power" => 8,
		"powerBoost" => 3,
		"health" => 5,
		"hyper" => 5,
		"abilities" => array(
			"Chain Reaction" => array("trigger" => "brawl", ),
			"Power Gorge" => array("trigger" => "blast", ),
			"Annihilate" => array(),
			"Logistics" => array("color" => "blue", ),
			"Riled" => array(),)
	),
  
	"gorghadra_mega" => array(
		"name" => "Gorghadra",
		"type" => "monster",
		"form" => "Mega",
		"faction" => "Planet Eaters",
		"agenda" => "Destroyers",
		"energyType" => "Cosmic",
		"set" => "Rise",
		"setColor" => "blue",
		"rarity" => 5,
		"speed" => 5,
		"defense" => 7,
		"brawl" => 7,
		"brawlBoost" => 2,
		"blast" => 7,
		"blastBoost" => 4,
		"blastRange" => "long",
		"power" => 6,
		"powerBoost" => 2,
		"health" => 9,
		"hyper" => 5,
		"abilities" => array(
			"Energy Cycle" => array(),
			"Chain Reaction" => array("trigger" => "blast", ),
			"Siphon" => array("trigger" => "blast", ),
			"Indirect Fire" => array(),
			"Radar" => array("color" => "blue", ),)
	),
  
	"rogzor_alpha" => array(
		"name" => "Rogzor",
		"type" => "monster",
		"form" => "Alpha",
		"faction" => "Planet Eaters",
		"agenda" => "Destroyers",
		"energyType" => "Cosmic",
		"set" => "Rise",
		"rarity" => 3,
		"speed" => 7,
		"defense" => 6,
		"brawl" => 6,
		"brawlBoost" => 1,
		"blast" => 6,
		"blastBoost" => 2,
		"blastRange" => "long",
		"power" => 5,
		"powerBoost" => 1,
		"health" => 5,
		"hyper" => 0,
		"abilities" => array(
			"Disintegrate" => array("trigger" => "blast", ),
			"Explosion" => array("color" => "blue", "trigger" => "blast", ),
			"Hit and Run" => array("trigger" => "blast", ),
			"High Impact" => array("color" => "blue", ),)
	),
  
	"rogzor_ultra" => array(
		"name" => "Rogzor",
		"type" => "monster",
		"form" => "Ultra",
		"faction" => "Planet Eaters",
		"agenda" => "Destroyers",
		"energyType" => "Cosmic",
		"set" => "Rise",
		"rarity" => 3,
		"speed" => 7,
		"defense" => 6,
		"brawl" => 6,
		"brawlBoost" => 2,
		"blast" => 8,
		"blastBoost" => 4,
		"blastRange" => "long",
		"power" => 5,
		"powerBoost" => 2,
		"health" => 5,
		"hyper" => 3,
		"abilities" => array(
			"Explosion" => array("color" => "red","trigger" => "blast", ),
			"Hit and Run" => array("trigger" => "blast", ),
			"Beat Back" => array("trigger" => "blast", ),
			"Anti-air" => array("color" => "blue", ),
			"High Impact" => array("color" => "blue", ),)
	),
  
	"rogzor_mega" => array(
		"name" => "Rogzor",
		"type" => "monster",
		"form" => "Mega",
		"faction" => "Planet Eaters",
		"agenda" => "Destroyers",
		"energyType" => "Cosmic",
		"set" => "Rise",
		"setColor" => "blue",
		"rarity" => 5,
		"speed" => 7,
		"defense" => 6,
		"brawl" => 6,
		"brawlBoost" => 1,
		"blast" => 7,
		"blastBoost" => 3,
		"blastRange" => "long",
		"power" => 5,
		"powerBoost" => 2,
		"health" => 5,
		"hyper" => 3,
		"abilities" => array(
			"Explosion" => array("trigger" => "blast", ),
			"Overload" => array("trigger" => "blast", ),
			"Armor Piercing" => array(),
			"Indirect Fire" => array(),
			"Sabotage" => array("color" => "blue", ),)
	),
  
	"vorgax_alpha_barreller" => array(
		"name" => "Vorgax",
		"type" => "monster",
		"form" => "Barreller",
		"faction" => "Planet Eaters",
		"agenda" => "Destroyers",
		"energyType" => "Cosmic",
		"set" => "All Your Base",
		"rarity" => 3,
		"speed" => 5,
		"defense" => 6,
		"brawl" => 3,
		"brawlBoost" => 2,
		"blast" => 2,
		"blastRange" => "short",
		"health" => 6,
		"hyper" => 0,
		"abilities" => array(
			"Summon" => array(),
			"Blitz" => array("trigger" => "brawl", ),
			"Jump" => array(),
			"Shelter" => array("color" => "red",),)
	),
  
	"vorgax_alpha_chompapillar" => array(
		"name" => "Vorgax",
		"type" => "monster",
		"form" => "Chompapillar",
		"faction" => "Planet Eaters",
		"agenda" => "Destroyers",
		"energyType" => "Cosmic",
		"set" => "All Your Base",
		"rarity" => 3,
		"speed" => 6,
		"defense" => 5,
		"brawl" => 3,
		"brawlBoost" => 1,
		"blast" => 1,
		"blastBoost" => 1,
		"blastRange" => "short",
		"health" => 6,
		"hyper" => 0,
		"abilities" => array(
			"Berserk" => array("color" => "red",),
			"Distract" => array(),
			"Flank" => array(),
			"Jump" => array(),)
	),
  
	"vorgax_alpha_mastigatapede" => array(
		"name" => "Vorgax",
		"type" => "monster",
		"form" => "Mastigatapede",
		"faction" => "Planet Eaters",
		"agenda" => "Destroyers",
		"energyType" => "Cosmic",
		"set" => "All Your Base",
		"rarity" => 3,
		"speed" => 6,
		"defense" => 5,
		"brawl" => 3,
		"brawlBoost" => 1,
		"blast" => 1,
		"blastBoost" => 1,
		"blastRange" => "short",
		"health" => 6,
		"hyper" => 0,
		"abilities" => array(
			"Crunch" => array("trigger" => "brawl", ),
			"Infiltrate" => array(),
			"Jump" => array(),
			"Riled" => array("color" => "red",),)
	),
  
	"vorgax_alpha_synapsepede" => array(
		"name" => "Vorgax",
		"type" => "monster",
		"form" => "Synapsepede",
		"faction" => "Planet Eaters",
		"agenda" => "Destroyers",
		"energyType" => "Cosmic",
		"set" => "All Your Base",
		"rarity" => 3,
		"speed" => 7,
		"defense" => 4,
		"brawl" => 3,
		"blast" => 2,
		"blastBoost" => 2,
		"blastRange" => "short",
		"health" => 6,
		"hyper" => 0,
		"abilities" => array(
			"Rage" => array(),
			"Disrupt" => array("color" => "red","trigger" => "blast", ),
			"Burrow" => array(),
			"Logistics" => array(),)
	),
  
	"vorgax_ultra" => array(
		"name" => "Vorgax",
		"type" => "monster",
		"form" => "Ultra",
		"faction" => "Planet Eaters",
		"agenda" => "Destroyers",
		"energyType" => "Cosmic",
		"set" => "All Your Base",
		"rarity" => 3,
		"speed" => 7,
		"defense" => 6,
		"brawl" => 8,
		"brawlBoost" => 4,
		"blast" => 7,
		"blastBoost" => 3,
		"blastRange" => "short",
		"power" => 7,
		"powerBoost" => 2,
		"health" => 5,
		"hyper" => 5,
		"abilities" => array(
			"Energy Cycle" => array(),
			"Siphon" => array("color" => "blue", "trigger" => "brawl", ),
			"Flight" => array(),
			"Negation" => array(),)
	),
  
	"vorgax_mega" => array(
		"name" => "Vorgax",
		"type" => "monster",
		"form" => "Mega",
		"faction" => "Planet Eaters",
		"agenda" => "Destroyers",
		"energyType" => "Cosmic",
		"set" => "All Your Base",
		"setColor" => "blue",
		"rarity" => 4,
		"speed" => 7,
		"defense" => 7,
		"brawl" => 7,
		"brawlBoost" => 3,
		"power" => 7,
		"powerBoost" => 3,
		"health" => 5,
		"hyper" => 4,
		"abilities" => array(
			"Fission" => array(),
			"Leach" => array(),
			"Lightning Attack" => array("trigger" => "brawl", ),
			"Flight" => array(),)
	),
  
	"xaxor_alpha" => array(
		"name" => "Xaxor",
		"type" => "monster",
		"form" => "Alpha",
		"faction" => "Planet Eaters",
		"agenda" => "Destroyers",
		"energyType" => "Cosmic",
		"set" => "I Chomp NY",
		"rarity" => 3,
		"speed" => 6,
		"defense" => 7,
		"brawl" => 6,
		"brawlBoost" => 2,
		"blast" => 7,
		"blastBoost" => 2,
		"blastRange" => "long",
		"power" => 6,
		"powerBoost" => 3,
		"health" => 5,
		"hyper" => 0,
		"abilities" => array(
			"Siphon" => array("trigger" => "brawl", ),
			"Charge" => array("color" => "blue", ),
			"Jump" => array("color" => "blue", ),
			"Super Stomp" => array(),)
	),
  
	"xaxor_ultra" => array(
		"name" => "Xaxor",
		"type" => "monster",
		"form" => "Ultra",
		"faction" => "Planet Eaters",
		"agenda" => "Destroyers",
		"energyType" => "Cosmic",
		"set" => "I Chomp NY",
		"rarity" => 3,
		"speed" => 7,
		"defense" => 5,
		"brawl" => 7,
		"brawlBoost" => 3,
		"blast" => 8,
		"blastBoost" => 3,
		"blastRange" => "long",
		"power" => 6,
		"powerBoost" => 2,
		"health" => 7,
		"hyper" => 3,
		"abilities" => array(
			"Following Fire" => array("trigger" => "brawl", ),
			"Siphon" => array("trigger" => "blast", ),
			"Weapon Master" => array("trigger" => "blast", ),
			"Charge" => array("color" => "blue", ),
			"Jump" => array("color" => "blue", ),
			"Steady" => array(),)
	),
  
	"xaxor_mega" => array(
		"name" => "Xaxor",
		"type" => "monster",
		"form" => "Mega",
		"faction" => "Planet Eaters",
		"agenda" => "Destroyers",
		"energyType" => "Cosmic",
		"set" => "I Chomp NY",
		"setColor" => "blue",
		"rarity" => 4,
		"speed" => 7,
		"defense" => 5,
		"brawl" => 7,
		"brawlBoost" => 2,
		"blast" => 7,
		"blastBoost" => 2,
		"blastRange" => "short",
		"power" => 6,
		"powerBoost" => 4,
		"health" => 7,
		"hyper" => 4,
		"abilities" => array(
			"Chain Attack" => array("trigger" => "brawl", ),
			"Chain Attack " => array("trigger" => "blast", ),
			"Siphon" => array("trigger" => "power", ),
			"Charge" => array("color" => "blue", ),
			"Jump" => array("color" => "blue", ),)
	),
  
	"zorog_alpha" => array(
		"name" => "Zorog",
		"type" => "monster",
		"form" => "Alpha",
		"faction" => "Planet Eaters",
		"agenda" => "Destroyers",
		"energyType" => "Cosmic",
		"set" => "I Chomp NY",
		"rarity" => 3,
		"speed" => 6,
		"defense" => 6,
		"brawl" => 7,
		"brawlBoost" => 2,
		"power" => 6,
		"powerBoost" => 2,
		"health" => 6,
		"hyper" => 0,
		"abilities" => array(
			"Energy Drain" => array("trigger" => "brawl", ),
			"Climb" => array("color" => "blue", ),
			"Gang" => array("color" => "blue", ),
			"Weaken" => array(),)
	),
  
	"zorog_ultra" => array(
		"name" => "Zorog",
		"type" => "monster",
		"form" => "Ultra",
		"faction" => "Planet Eaters",
		"agenda" => "Destroyers",
		"energyType" => "Cosmic",
		"set" => "I Chomp NY",
		"rarity" => 3,
		"speed" => 6,
		"defense" => 6,
		"brawl" => 8,
		"brawlBoost" => 3,
		"blast" => 4,
		"blastBoost" => 1,
		"blastRange" => "long",
		"power" => 7,
		"powerBoost" => 3,
		"health" => 7,
		"hyper" => 5,
		"abilities" => array(
			"Crunch" => array("trigger" => "brawl", ),
			"Energy Drain" => array("trigger" => "brawl", ),
			"Climb" => array("color" => "blue", ),
			"Gang" => array("color" => "blue", ),
			"Weaken" => array(),
			"Riled" => array("color" => "blue", ),)
	),
  
	"zorog_mega" => array(
		"name" => "Zorog",
		"type" => "monster",
		"form" => "Mega",
		"faction" => "Planet Eaters",
		"agenda" => "Destroyers",
		"energyType" => "Cosmic",
		"set" => "I Chomp NY",
		"setColor" => "blue",
		"rarity" => 4,
		"speed" => 6,
		"defense" => 6,
		"brawl" => 8,
		"brawlBoost" => 2,
		"blast" => 6,
		"blastBoost" => 2,
		"blastRange" => "short",
		"power" => 7,
		"powerBoost" => 4,
		"health" => 6,
		"hyper" => 6,
		"abilities" => array(
			"Energy Cycle" => array(),
			"Siphon" => array("trigger" => "power", ),
			"Climb" => array("color" => "blue", ),
			"Gang" => array("color" => "blue", ),)
	),
  
	"harbinger_comet_shard" => array(
		"name" => "Harbinger Comet Shard",
		"type" => "building",
		"hazard" => "rubble",
		"faction" => "Planet Eaters",
		"agenda" => "Destroyers",
		"set" => "All Your Base",
		"rarity" => 3,
		"defense" => 5,
		"energy" => 4,
		"abilities" => array(
			"Attraction" => array(),
			"Leadership" => array("color" => "red",),
			"Shuffle" => array(),
			"Spire" => array(),)
	),
  
	"belcher_grunt" => array(
		"name" => "Belcher",
		"type" => "unit",
		"class" => "Grunt",
		"faction" => "Planet Eaters",
		"agenda" => "Destroyers",
		"energyType" => "Cosmic",
		"set" => "Rise",
		"rarity" => 1,
		"speed" => 4,
		"defense" => 2,
		"brawl" => 1,
		"blast" => 2,
		"blastRange" => "long",
		"cost" => 1,
		"abilities" => array(
			"Indirect Fire" => array(),)
	),
  
	"belcher_elite" => array(
		"name" => "Belcher",
		"type" => "unit",
		"class" => "Elite",
		"faction" => "Planet Eaters",
		"agenda" => "Destroyers",
		"energyType" => "Cosmic",
		"set" => "Rise",
		"rarity" => 2,
		"speed" => 4,
		"defense" => 2,
		"brawl" => 1,
		"brawlBoost" => 1,
		"blast" => 2,
		"blastBoost" => 1,
		"blastRange" => "long",
		"cost" => 2,
		"abilities" => array(
			"Indirect Fire" => array(),
			"Leadership" => array(),)
	),
  
	"chomper_grunt" => array(
		"name" => "Chomper",
		"type" => "unit",
		"class" => "Grunt",
		"faction" => "Planet Eaters",
		"agenda" => "Destroyers",
		"energyType" => "Cosmic",
		"set" => "I Chomp NY",
		"rarity" => 1,
		"speed" => 5,
		"defense" => 3,
		"brawl" => 2,
		"brawlBoost" => 1,
		"cost" => 1,
		"abilities" => array(
			"Energy Cycle" => array("color" => "red",),
			"Energy Sap" => array("trigger" => "brawl", ),
			"Feeding Frenzy" => array("color" => "red","trigger" => "brawl", ),)
	),
  
	"chomper_elite" => array(
		"name" => "Chomper",
		"type" => "unit",
		"class" => "Elite",
		"faction" => "Planet Eaters",
		"agenda" => "Destroyers",
		"energyType" => "Cosmic",
		"set" => "I Chomp NY",
		"rarity" => 3,
		"speed" => 5,
		"defense" => 3,
		"brawl" => 2,
		"brawlBoost" => 2,
		"cost" => 2,
		"abilities" => array(
			"Energy Cycle" => array("color" => "red",),
			"Energy Sap" => array("trigger" => "brawl", ),
			"Feeding Frenzy" => array("color" => "red","trigger" => "brawl", ),
			"Leadership" => array(),)
	),
  
	"constrictor_grunt" => array(
		"name" => "Constrictor",
		"type" => "unit",
		"class" => "Grunt",
		"faction" => "Planet Eaters",
		"agenda" => "Destroyers",
		"energyType" => "Cosmic",
		"set" => "All Your Base",
		"rarity" => 1,
		"speed" => 5,
		"defense" => 2,
		"brawl" => 2,
		"cost" => 1,
		"abilities" => array(
			"Halt" => array(),
			"Penetrator" => array(),)
	),
  
	"constrictor_elite" => array(
		"name" => "Constrictor",
		"type" => "unit",
		"class" => "Elite",
		"faction" => "Planet Eaters",
		"agenda" => "Destroyers",
		"energyType" => "Cosmic",
		"set" => "All Your Base",
		"rarity" => 2,
		"speed" => 5,
		"defense" => 2,
		"brawl" => 2,
		"brawlBoost" => 1,
		"cost" => 2,
		"abilities" => array(
			"Halt" => array(),
			"Leadership" => array(),
			"Penetrator" => array(),)
	),
  
	"constrictor_shadow" => array(
		"name" => "Constrictor",
		"type" => "unit",
		"form" => "Shadow",
		"class" => "Elite",
		"faction" => "Planet Eaters",
		"agenda" => "Destroyers",
		"energyType" => "Cosmic",
		"set" => "All Your Base",
		"setColor" => "blue",
		"rarity" => 4,
		"speed" => 5,
		"defense" => 2,
		"brawl" => 2,
		"brawlBoost" => 1,
		"cost" => 3,
		"abilities" => array(
			"Cloak" => array(),
			"Halt" => array(),
			"Leadership" => array(),
			"Penetrator" => array(),)
	),
  
	"crawler_grunt" => array(
		"name" => "Crawler",
		"type" => "unit",
		"class" => "Grunt",
		"faction" => "Planet Eaters",
		"agenda" => "Destroyers",
		"energyType" => "Cosmic",
		"set" => "Rise",
		"rarity" => 3,
		"speed" => 4,
		"defense" => 4,
		"cost" => 2,
		"abilities" => array(
			"All Terrain" => array(),
			"Dig In" => array(),
			"Weaken" => array(),
			"Unstable" => array(),)
	),
  
	"destructomite_grunt" => array(
		"name" => "Destructomite",
		"type" => "unit",
		"class" => "Grunt",
		"faction" => "Planet Eaters",
		"agenda" => "Destroyers",
		"energyType" => "Cosmic",
		"set" => "Rise",
		"rarity" => 1,
		"speed" => 6,
		"defense" => 2,
		"brawl" => 3,
		"cost" => 1,
		"abilities" => array(
			"All Terrain" => array(),
			"Flank" => array(),)
	),
  
	"destructomite_elite" => array(
		"name" => "Destructomite",
		"type" => "unit",
		"class" => "Elite",
		"faction" => "Planet Eaters",
		"agenda" => "Destroyers",
		"energyType" => "Cosmic",
		"set" => "Rise",
		"rarity" => 3,
		"speed" => 6,
		"defense" => 2,
		"brawl" => 3,
		"brawlBoost" => 1,
		"cost" => 2,
		"abilities" => array(
			"All Terrain" => array(),
			"Flank" => array(),
			"Leadership" => array(),)
	),
  
	"explodohawk_grunt" => array(
		"name" => "Explodohawk",
		"type" => "unit",
		"class" => "Grunt",
		"faction" => "Planet Eaters",
		"agenda" => "Destroyers",
		"energyType" => "Cosmic",
		"set" => "Rise",
		"rarity" => 1,
		"speed" => 6,
		"defense" => 2,
		"brawl" => 6,
		"brawlBoost" => 3,
		"cost" => 1,
		"abilities" => array(
			"Self Destruct" => array("trigger" => "brawl", ),
			"Flight" => array(),
			"Solo Brawler" => array(),)
	),
  
	"explodohawk_shadow" => array(
		"name" => "Explodohawk",
		"type" => "unit",
		"form" => "Shadow",
		"class" => "Grunt",
		"faction" => "Planet Eaters",
		"agenda" => "Destroyers",
		"energyType" => "Cosmic",
		"set" => "Rise",
		"setColor" => "blue",
		"rarity" => 5,
		"speed" => 6,
		"defense" => 2,
		"brawl" => 6,
		"brawlBoost" => 3,
		"cost" => 2,
		"abilities" => array(
			"Self Destruct" => array("trigger" => "brawl", ),
			"Cloak" => array(),
			"Flight" => array(),
			"Solo Brawler" => array(),)
	),
  
	"explodomite_grunt" => array(
		"name" => "Explodomite",
		"type" => "unit",
		"class" => "Grunt",
		"faction" => "Planet Eaters",
		"agenda" => "Destroyers",
		"energyType" => "Cosmic",
		"set" => "All Your Base",
		"rarity" => 3,
		"speed" => 5,
		"defense" => 4,
		"brawl" => 3,
		"brawlBoost" => 2,
		"cost" => 1,
		"abilities" => array(
			"Explosion" => array("trigger" => "brawl", ),
			"Self Destruct" => array("trigger" => "brawl", ),
			"All Terrain" => array(),)
	),
  
	"scorcher_grunt" => array(
		"name" => "Scorcher",
		"type" => "unit",
		"class" => "Grunt",
		"faction" => "Planet Eaters",
		"agenda" => "Destroyers",
		"energyType" => "Cosmic",
		"set" => "I Chomp NY",
		"rarity" => 1,
		"speed" => 5,
		"defense" => 3,
		"brawl" => 2,
		"blast" => 2,
		"blastRange" => "short",
		"cost" => 1,
		"abilities" => array(
			"Chain Reaction" => array("trigger" => "blast", ),
			"Flight" => array(),)
	),
  
	"scorcher_elite" => array(
		"name" => "Scorcher",
		"type" => "unit",
		"class" => "Elite",
		"faction" => "Planet Eaters",
		"agenda" => "Destroyers",
		"energyType" => "Cosmic",
		"set" => "I Chomp NY",
		"rarity" => 2,
		"speed" => 5,
		"defense" => 3,
		"brawl" => 2,
		"brawlBoost" => 1,
		"blast" => 2,
		"blastBoost" => 1,
		"blastRange" => "short",
		"cost" => 2,
		"abilities" => array(
			"Power Cycle" => array("color" => "red",),
			"Chain Reaction" => array("trigger" => "blast", ),
			"Flight" => array(),
			"Leadership" => array(),)
	),
  
	"scorcher_shadow" => array(
		"name" => "Scorcher",
		"type" => "unit",
		"form" => "Shadow",
		"class" => "Grunt",
		"faction" => "Planet Eaters",
		"agenda" => "Destroyers",
		"energyType" => "Cosmic",
		"set" => "I Chomp NY",
		"setColor" => "blue",
		"rarity" => 4,
		"speed" => 5,
		"defense" => 3,
		"brawl" => 2,
		"blast" => 2,
		"blastRange" => "short",
		"cost" => 2,
		"abilities" => array(
			"Chain Reaction" => array("trigger" => "blast", ),
			"Cloak" => array(),
			"Flight" => array(),)
	),
  
