


/*    =============    Planet Doom    =============    */

	"lo-tron_alpha_armadillo_robeast" => array(
		"name" => "Lo-Tron",
		"type" => "monster",
		"form" => "Armadillo Robeast",
		"faction" => "Planet Doom",
		"agenda" => "Fiends",
		"energyType" => "Mechanical",
		"set" => "Voltron Box Set",
		"rarity" => 3,
		"speed" => 5,
		"defense" => 5,
		"brawl" => 4,
		"brawlBoost" => 2,
		"blast" => 3,
		"blastRange" => "short",
		"health" => 5,
		"hyper" => 0,
		"abilities" => array(
			"Radial Attack" => array("trigger" => "brawl", ),
			"Flight" => array(),)
	),
  
	"lo-tron_alpha_beetle_robeast" => array(
		"name" => "Lo-Tron",
		"type" => "monster",
		"form" => "Beetle Robeast",
		"faction" => "Planet Doom",
		"agenda" => "Fiends",
		"energyType" => "Mechanical",
		"set" => "Voltron Box Set",
		"rarity" => 3,
		"speed" => 6,
		"defense" => 5,
		"brawl" => 3,
		"brawlBoost" => 1,
		"blast" => 3,
		"blastBoost" => 1,
		"blastRange" => "short",
		"health" => 5,
		"hyper" => 0,
		"abilities" => array(
			"Power Gorge" => array("trigger" => "blast", ),
			"Flight" => array(),)
	),
  
	"lo-tron_alpha_lotor's_command_ship" => array(
		"name" => "Lo-Tron",
		"type" => "monster",
		"form" => "Lotor's Command Ship",
		"faction" => "Planet Doom",
		"agenda" => "Fiends",
		"energyType" => "Mechanical",
		"set" => "Voltron Box Set",
		"rarity" => 3,
		"speed" => 5,
		"defense" => 5,
		"blast" => 5,
		"blastBoost" => 1,
		"blastRange" => "short",
		"health" => 5,
		"hyper" => 0,
		"abilities" => array(
			"Siphon" => array("trigger" => "blast", ),
			"Synchronized Move" => array("trigger" => "blast", ),
			"Flight" => array(),
			"Motivator" => array(),)
	),
  
	"lo-tron_alpha_rhino_robeast" => array(
		"name" => "Lo-Tron",
		"type" => "monster",
		"form" => "Rhino Robeast",
		"faction" => "Planet Doom",
		"agenda" => "Fiends",
		"energyType" => "Mechanical",
		"set" => "Voltron Box Set",
		"rarity" => 3,
		"speed" => 5,
		"defense" => 5,
		"brawl" => 4,
		"brawlBoost" => 1,
		"blast" => 3,
		"blastRange" => "short",
		"health" => 5,
		"hyper" => 0,
		"abilities" => array(
			"Toss" => array("trigger" => "brawl", ),
			"Lightning Attack" => array("trigger" => "blast", ),
			"Flight" => array(),)
	),
  
	"lo-tron_alpha_scorpion_robeast" => array(
		"name" => "Lo-Tron",
		"type" => "monster",
		"form" => "Scorpion Robeast",
		"faction" => "Planet Doom",
		"agenda" => "Fiends",
		"energyType" => "Mechanical",
		"set" => "Voltron Box Set",
		"rarity" => 3,
		"speed" => 6,
		"defense" => 5,
		"brawl" => 3,
		"blast" => 3,
		"blastBoost" => 2,
		"blastRange" => "short",
		"health" => 5,
		"hyper" => 0,
		"abilities" => array(
			"Hit and Run" => array("trigger" => "blast", ),
			"Flight" => array(),
			"Quick" => array(),)
	),
  
	"lo-tron_ultra" => array(
		"name" => "Lo-Tron",
		"type" => "monster",
		"form" => "Ultra",
		"faction" => "Planet Doom",
		"agenda" => "Fiends",
		"energyType" => "Mechanical",
		"set" => "Voltron Box Set",
		"rarity" => 3,
		"speed" => 7,
		"defense" => 6,
		"brawl" => 7,
		"brawlBoost" => 3,
		"blast" => 6,
		"blastBoost" => 3,
		"blastRange" => "short",
		"power" => 8,
		"powerBoost" => 4,
		"health" => 6,
		"hyper" => 4,
		"abilities" => array(
			"Crunch" => array("trigger" => "brawl", ),
			"Hit and Run" => array("trigger" => "power", ),
			"Adaptable" => array(),
			"Flight" => array(),
			"Reach" => array(),)
	),
  
	"lo-tron_mega" => array(
		"name" => "Lo-Tron",
		"type" => "monster",
		"form" => "Mega",
		"faction" => "Planet Doom",
		"agenda" => "Fiends",
		"energyType" => "Mechanical",
		"set" => "Voltron Box Set",
		"setColor" => "black",
		"rarity" => 4,
		"speed" => 6,
		"defense" => 7,
		"brawl" => 8,
		"brawlBoost" => 3,
		"blast" => 7,
		"blastBoost" => 3,
		"blastRange" => "short",
		"power" => 7,
		"powerBoost" => 3,
		"health" => 6,
		"hyper" => 4,
		"abilities" => array(
			"Power Strike" => array("trigger" => "brawl", ),
			"Weapon Master" => array("trigger" => "brawl", ),
			"Juggernaut_short" => array(),
			"Flight_short" => array(),
			"Reach" => array(),)
	),

	"skull_ship_grunt" => array(
		"name" => "Skull Ship",
		"type" => "unit",
		"class" => "Grunt",
		"faction" => "Planet Doom",
		"agenda" => "Fiends",
		"energyType" => "Mechanical",
		"set" => "Voltron Box Set",
		"rarity" => 1,
		"speed" => 5,
		"defense" => 2,
		"blast" => 3,
		"blastBoost" => 1,
		"blastRange" => "short",
		"cost" => 1,
		"abilities" => array(
			"Hit and Run" => array("trigger" => "blast", ),
			"Flight" => array(),)
	),
  
