


/*    =============    Savage Swarm    =============    */

	"dynastavus_alpha" => array(
		"name" => "Dynastavus",
		"type" => "monster",
		"form" => "Alpha",
		"faction" => "Savage Swarm",
		"agenda" => "Destroyers",
		"energyType" => "Radioactive",
		"set" => "Big in Japan",
		"rarity" => 3,
		"speed" => 7,
		"defense" => 6,
		"brawl" => 7,
		"brawlBoost" => 3,
		"power" => 6,
		"powerBoost" => 1,
		"health" => 5,
		"hyper" => 0,
		"abilities" => array(
			"Command" => array(),
			"Power Drain" => array("trigger" => "brawl", ),
			"Weapon Master" => array("trigger" => "brawl", ),
			"Charge" => array(),
			"Flight" => array(),)
	),
  
	"dynastavus_ultra" => array(
		"name" => "Dynastavus",
		"type" => "monster",
		"form" => "Ultra",
		"faction" => "Savage Swarm",
		"agenda" => "Destroyers",
		"energyType" => "Radioactive",
		"set" => "Big in Japan",
		"rarity" => 3,
		"speed" => 7,
		"defense" => 6,
		"brawl" => 8,
		"brawlBoost" => 3,
		"power" => 7,
		"powerBoost" => 2,
		"health" => 6,
		"hyper" => 4,
		"abilities" => array(
			"Hit and Run" => array("trigger" => "brawl", ),
			"Siphon" => array("trigger" => "brawl", ),
			"Synchronized Move" => array("trigger" => "brawl", ),
			"Weapon Master" => array("trigger" => "brawl", ),
			"Charge" => array(),
			"Flight" => array(),)
	),
  
	"dynastavus_mega" => array(
		"name" => "Dynastavus",
		"type" => "monster",
		"form" => "Mega",
		"faction" => "Savage Swarm",
		"agenda" => "Destroyers",
		"energyType" => "Radioactive",
		"set" => "Big in Japan",
		"setColor" => "blue",
		"rarity" => 4,
		"speed" => 6,
		"defense" => 5,
		"brawl" => 6,
		"brawlBoost" => 2,
		"blast" => 6,
		"blastBoost" => 2,
		"blastRange" => "short",
		"power" => 6,
		"powerBoost" => 3,
		"health" => 5,
		"hyper" => 4,
		"abilities" => array(
			"Lightning Attack" => array("trigger" => "brawl", ),
			"Synchronized Move" => array("trigger" => "power", ),
			"Charge" => array(),
			"Drain Life" => array(),
			"Flight" => array(),)
	),
  
	"mantacon_alpha" => array(
		"name" => "Mantacon",
		"type" => "monster",
		"form" => "Alpha",
		"faction" => "Savage Swarm",
		"agenda" => "Destroyers",
		"energyType" => "Radioactive",
		"set" => "Now",
		"rarity" => 3,
		"speed" => 7,
		"defense" => 7,
		"brawl" => 7,
		"brawlBoost" => 3,
		"power" => 5,
		"powerBoost" => 2,
		"health" => 5,
		"hyper" => 0,
		"abilities" => array(
			"Hit and Run" => array("trigger" => "brawl", ),
			"Lightning Attack" => array("trigger" => "brawl", ),
			"Cloak" => array("color" => "red",),
			"Jump" => array(),)
	),
  
	"mantacon_ultra" => array(
		"name" => "Mantacon",
		"type" => "monster",
		"form" => "Ultra",
		"faction" => "Savage Swarm",
		"agenda" => "Destroyers",
		"energyType" => "Radioactive",
		"set" => "Now",
		"rarity" => 3,
		"speed" => 8,
		"defense" => 7,
		"brawl" => 8,
		"brawlBoost" => 3,
		"blast" => 6,
		"blastBoost" => 2,
		"blastRange" => "short",
		"power" => 7,
		"powerBoost" => 2,
		"health" => 5,
		"hyper" => 4,
		"abilities" => array(
			"Chain Attack" => array("trigger" => "brawl", ),
			"Hit and Run" => array("trigger" => "power", ),
			"Cloak" => array("color" => "blue", ),
			"Jump" => array(),)
	),
  
	"mantacon_mega" => array(
		"name" => "Mantacon",
		"type" => "monster",
		"form" => "Mega",
		"faction" => "Savage Swarm",
		"agenda" => "Destroyers",
		"energyType" => "Radioactive",
		"set" => "Now",
		"setColor" => "blue",
		"rarity" => 4,
		"speed" => 6,
		"defense" => 7,
		"brawl" => 8,
		"brawlBoost" => 3,
		"blast" => 9,
		"blastRange" => "short",
		"power" => 7,
		"powerBoost" => 3,
		"health" => 6,
		"hyper" => 4,
		"abilities" => array(
			"Sacrifice" => array(),
			"Hit and Run" => array("trigger" => "brawl", ),
			"Lightning Attack" => array("trigger" => "brawl", ),
			"Cloak" => array("color" => "red",),
			"Jump_short" => array(),
			"Quick" => array(),)
	),
  
	"mucustos_alpha" => array(
		"name" => "Mucustos",
		"type" => "monster",
		"form" => "Alpha",
		"faction" => "Savage Swarm",
		"agenda" => "Destroyers",
		"energyType" => "Radioactive",
		"set" => "Now",
		"rarity" => 3,
		"speed" => 5,
		"defense" => 6,
		"brawl" => 6,
		"brawlBoost" => 2,
		"blast" => 7,
		"blastBoost" => 3,
		"blastRange" => "long",
		"power" => 5,
		"powerBoost" => 1,
		"health" => 7,
		"hyper" => 0,
		"abilities" => array(
			"Summon" => array(),
			"Crunch" => array("trigger" => "blast", ),
			"Energy Sap" => array("trigger" => "blast", ),
			"Burrow" => array(),)
	),
  
	"mucustos_ultra" => array(
		"name" => "Mucustos",
		"type" => "monster",
		"form" => "Ultra",
		"faction" => "Savage Swarm",
		"agenda" => "Destroyers",
		"energyType" => "Radioactive",
		"set" => "Now",
		"rarity" => 3,
		"speed" => 5,
		"defense" => 6,
		"brawl" => 7,
		"brawlBoost" => 2,
		"blast" => 8,
		"blastBoost" => 4,
		"blastRange" => "short",
		"power" => 6,
		"powerBoost" => 2,
		"health" => 6,
		"hyper" => 4,
		"abilities" => array(
			"Extinguish" => array(),
			"Crunch" => array("trigger" => "blast", ),
			"Energy Sap" => array("trigger" => "blast", ),
			"Burrow" => array(),
			"Radar" => array("color" => "blue", ),)
	),
  
	"mucustos_mega" => array(
		"name" => "Mucustos",
		"type" => "monster",
		"form" => "Mega",
		"faction" => "Savage Swarm",
		"agenda" => "Destroyers",
		"energyType" => "Radioactive",
		"set" => "Now",
		"setColor" => "blue",
		"rarity" => 4,
		"speed" => 5,
		"defense" => 6,
		"brawl" => 6,
		"brawlBoost" => 2,
		"blast" => 6,
		"blastBoost" => 4,
		"blastRange" => "short",
		"power" => 7,
		"powerBoost" => 3,
		"health" => 5,
		"hyper" => 3,
		"abilities" => array(
			"Summon" => array(),
			"Grind" => array("trigger" => "blast", ),
			"Power Strike" => array("trigger" => "blast", ),
			"Burrow" => array(),)
	),
  
	"xixorax_alpha" => array(
		"name" => "Xixorax",
		"type" => "monster",
		"form" => "Alpha",
		"faction" => "Savage Swarm",
		"agenda" => "Destroyers",
		"energyType" => "Radioactive",
		"set" => "Big in Japan",
		"rarity" => 3,
		"speed" => 5,
		"defense" => 5,
		"brawl" => 7,
		"brawlBoost" => 2,
		"power" => 8,
		"powerBoost" => 2,
		"health" => 6,
		"hyper" => 0,
		"abilities" => array(
			"Sprint" => array(),
			"Juggernaut" => array(),
			"Super Rampage" => array(),
			"Spire" => array(),)
	),
  
	"xixorax_ultra" => array(
		"name" => "Xixorax",
		"type" => "monster",
		"form" => "Ultra",
		"faction" => "Savage Swarm",
		"agenda" => "Destroyers",
		"energyType" => "Radioactive",
		"set" => "Big in Japan",
		"rarity" => 3,
		"speed" => 7,
		"defense" => 6,
		"brawl" => 8,
		"brawlBoost" => 2,
		"blast" => 5,
		"blastBoost" => 1,
		"blastRange" => "short",
		"power" => 9,
		"powerBoost" => 3,
		"health" => 6,
		"hyper" => 3,
		"abilities" => array(
			"Beat Back_short" => array("trigger" => "brawl", ),
			"Blitz_short" => array("trigger" => "brawl", ),
			"Charge" => array(),
			"Juggernaut_short" => array(),
			"Super Rampage" => array(),
			"Spire" => array(),)
	),
  
	"xixorax_mega" => array(
		"name" => "Xixorax",
		"type" => "monster",
		"form" => "Mega",
		"faction" => "Savage Swarm",
		"agenda" => "Destroyers",
		"energyType" => "Radioactive",
		"set" => "Big in Japan",
		"setColor" => "blue",
		"rarity" => 4,
		"speed" => 6,
		"defense" => 7,
		"brawl" => 6,
		"brawlBoost" => 3,
		"power" => 6,
		"powerBoost" => 3,
		"health" => 5,
		"hyper" => 3,
		"abilities" => array(
			"Charge" => array(),
			"Juggernaut" => array(),
			"Super Rampage" => array(),
			"Super Smash" => array(),
			"Spire" => array(),)
	),
  
	"warlord_rifa" => array(
		"name" => "Warlord Rifa",
		"type" => "character",
		"form" => "Dire Ant Warrior",
		"class" => "Elite",
		"faction" => "Savage Swarm",
		"agenda" => "Destroyers",
		"energyType" => "Radioactive",
		"set" => "Big in Japan",
		"rarity" => 4,
		"speed" => 6,
		"defense" => 3,
		"brawl" => 1,
		"brawlBoost" => 2,
		"cost" => 2,
		"abilities" => array(
			"Fireproof" => array(),
			"Limited" => array(),
			"Motivator" => array(),
			"Penetrator" => array(),)
	),

	"cliff_hopper_grunt" => array(
		"name" => "Cliff Hopper",
		"type" => "unit",
		"class" => "Grunt",
		"faction" => "Savage Swarm",
		"agenda" => "Destroyers",
		"energyType" => "Radioactive",
		"set" => "Now",
		"rarity" => 1,
		"speed" => 6,
		"defense" => 2,
		"brawl" => 1,
		"blast" => 1,
		"blastBoost" => 1,
		"blastRange" => "short",
		"cost" => 1,
		"abilities" => array(
			"Power Gorge" => array("trigger" => "blast", ),
			"Flight" => array(),)
	),
  
	"cliff_hopper_elite" => array(
		"name" => "Cliff Hopper",
		"type" => "unit",
		"class" => "Elite",
		"faction" => "Savage Swarm",
		"agenda" => "Destroyers",
		"energyType" => "Radioactive",
		"set" => "Now",
		"rarity" => 3,
		"speed" => 6,
		"defense" => 2,
		"brawl" => 1,
		"brawlBoost" => 1,
		"blast" => 1,
		"blastBoost" => 2,
		"blastRange" => "short",
		"cost" => 2,
		"abilities" => array(
			"Power Gorge" => array("trigger" => "blast", ),
			"Flight" => array(),
			"Leadership" => array(),)
	),
  
	"dire_ant_warrior_grunt" => array(
		"name" => "Dire Ant Warrior",
		"type" => "unit",
		"class" => "Grunt",
		"faction" => "Savage Swarm",
		"agenda" => "Destroyers",
		"energyType" => "Radioactive",
		"set" => "Big in Japan",
		"rarity" => 1,
		"speed" => 4,
		"defense" => 3,
		"brawl" => 1,
		"cost" => 1,
		"abilities" => array(
			"Countermeasures" => array(),
			"Gang" => array(),)
	),
  
	"dire_ant_warrior_elite" => array(
		"name" => "Dire Ant Warrior",
		"type" => "unit",
		"class" => "Elite",
		"faction" => "Savage Swarm",
		"agenda" => "Destroyers",
		"energyType" => "Radioactive",
		"set" => "Big in Japan",
		"rarity" => 2,
		"speed" => 4,
		"defense" => 3,
		"brawl" => 1,
		"brawlBoost" => 1,
		"cost" => 2,
		"abilities" => array(
			"Coordinate" => array(),
			"Countermeasures" => array(),
			"Gang" => array(),
			"Leadership" => array(),)
	),
  
	"razor_beetle_grunt" => array(
		"name" => "Razor Beetle",
		"type" => "unit",
		"class" => "Grunt",
		"faction" => "Savage Swarm",
		"agenda" => "Destroyers",
		"energyType" => "Radioactive",
		"set" => "Now",
		"rarity" => 1,
		"speed" => 5,
		"defense" => 4,
		"brawl" => 3,
		"cost" => 1,
		"abilities" => array(
			"Blitz" => array("trigger" => "brawl", ),
			"Burrow" => array(),
			"Hazardous" => array(),)
	),
  
	"razor_beetle_elite" => array(
		"name" => "Razor Beetle",
		"type" => "unit",
		"class" => "Elite",
		"faction" => "Savage Swarm",
		"agenda" => "Destroyers",
		"energyType" => "Radioactive",
		"set" => "Now",
		"rarity" => 3,
		"speed" => 5,
		"defense" => 4,
		"brawl" => 3,
		"brawlBoost" => 1,
		"cost" => 2,
		"abilities" => array(
			"Blitz" => array("trigger" => "brawl", ),
			"Burrow" => array(),
			"Hazardous" => array(),
			"Leadership" => array(),)
	),
  
	"spy_fly_grunt" => array(
		"name" => "Spy Fly",
		"type" => "unit",
		"class" => "Grunt",
		"faction" => "Savage Swarm",
		"agenda" => "Destroyers",
		"energyType" => "Radioactive",
		"set" => "Now",
		"rarity" => 2,
		"speed" => 5,
		"defense" => 2,
		"cost" => 1,
		"abilities" => array(
			"Flight" => array(),
			"Quick" => array(),
			"Spotter" => array(),)
	),
  
	"spy_fly_glass" => array(
		"name" => "Spy Fly",
		"type" => "unit",
		"form" => "Glass",
		"class" => "Grunt",
		"faction" => "Savage Swarm",
		"agenda" => "Destroyers",
		"energyType" => "Radioactive",
		"set" => "Now",
		"setColor" => "blue",
		"rarity" => 4,
		"speed" => 5,
		"defense" => 2,
		"blast" => 1,
		"blastBoost" => 1,
		"blastRange" => "short",
		"cost" => 1,
		"abilities" => array(
			"Cloak" => array(),
			"Flight" => array(),
			"Fragile" => array(),
			"Quick" => array(),)
	),
  
	"steel_back_roach_grunt" => array(
		"name" => "Steel Back Roach",
		"type" => "unit",
		"class" => "Grunt",
		"faction" => "Savage Swarm",
		"agenda" => "Destroyers",
		"energyType" => "Radioactive",
		"set" => "Now",
		"rarity" => 1,
		"speed" => 5,
		"defense" => 2,
		"brawl" => 1,
		"cost" => 1,
		"abilities" => array(
			"Pathfinder" => array("color" => "red",),
			"Force Field" => array("color" => "red",),
			"Jump" => array(),
			"Shelter" => array("color" => "red",),)
	),
  
	"vice_pincher_grunt" => array(
		"name" => "Vice Pincher",
		"type" => "unit",
		"class" => "Grunt",
		"faction" => "Savage Swarm",
		"agenda" => "Destroyers",
		"energyType" => "Radioactive",
		"set" => "Big in Japan",
		"rarity" => 1,
		"speed" => 6,
		"defense" => 2,
		"brawl" => 3,
		"cost" => 1,
		"abilities" => array(
			"Burrow" => array(),
			"Flank" => array(),
			"Halt" => array(),)
	),
  
	"vice_pincher_elite" => array(
		"name" => "Vice Pincher",
		"type" => "unit",
		"class" => "Elite",
		"faction" => "Savage Swarm",
		"agenda" => "Destroyers",
		"energyType" => "Radioactive",
		"set" => "Big in Japan",
		"rarity" => 3,
		"speed" => 6,
		"defense" => 2,
		"brawl" => 3,
		"brawlBoost" => 1,
		"cost" => 2,
		"abilities" => array(
			"Burrow" => array(),
			"Flank" => array(),
			"Halt" => array(),
			"Leadership" => array(),)
	),

	"vice_pincher_glass" => array(
		"name" => "Vice Pincher",
		"type" => "unit",
		"form" => "Glass",
		"class" => "Grunt",
		"faction" => "Savage Swarm",
		"agenda" => "Destroyers",
		"energyType" => "Radioactive",
		"set" => "Big in Japan",
		"setColor" => "blue",
		"rarity" => 4,
		"speed" => 6,
		"defense" => 2,
		"brawl" => 3,
		"brawlBoost" => 1,
		"blast" => 2,
		"blastRange" => "short",
		"cost" => 1,
		"abilities" => array(
			"Burrow" => array(),
			"Flank" => array("color" => "red",),
			"Fragile" => array(),
			"Halt" => array(),)
	),

