


/*    =============    Shadow Sun Syndicate    =============    */

	"zor-macros_alpha_zor-decius" => array(
		"name" => "Zor-Macros",
		"type" => "monster",
		"form" => "Zor-Decius",
		"faction" => "Shadow Sun Syndicate",
		"agenda" => "Collaborators",
		"energyType" => "Biotech",
		"set" => "All Your Base",
		"rarity" => 3,
		"speed" => 7,
		"defense" => 5,
		"brawl" => 3,
		"blast" => 3,
		"blastBoost" => 2,
		"blastRange" => "long",
		"health" => 5,
		"hyper" => 0,
		"abilities" => array(
			"Energy Drain" => array("color" => "red","trigger" => "blast", ),
			"Power Gorge" => array("color" => "red","trigger" => "blast", ),
			"Jump" => array(),
			"Sniper" => array("color" => "red",),)
	),
  
	"zor-macros_alpha_zor-fractus" => array(
		"name" => "Zor-Macros",
		"type" => "monster",
		"form" => "Zor-Fractus",
		"faction" => "Shadow Sun Syndicate",
		"agenda" => "Collaborators",
		"energyType" => "Biotech",
		"set" => "All Your Base",
		"rarity" => 3,
		"speed" => 7,
		"defense" => 5,
		"brawl" => 3,
		"brawlBoost" => 1,
		"blast" => 3,
		"blastBoost" => 1,
		"blastRange" => "short",
		"health" => 5,
		"hyper" => 0,
		"abilities" => array(
			"Lightning Attack" => array("trigger" => "brawl", ),
			"Disable" => array(),
			"Gang" => array("color" => "red",),
			"Jump" => array(),)
	),
  
	"zor-macros_alpha_zor-quanta" => array(
		"name" => "Zor-Macros",
		"type" => "monster",
		"form" => "Zor-Quanta",
		"faction" => "Shadow Sun Syndicate",
		"agenda" => "Collaborators",
		"energyType" => "Biotech",
		"set" => "All Your Base",
		"rarity" => 3,
		"speed" => 7,
		"defense" => 5,
		"brawl" => 3,
		"brawlBoost" => 2,
		"blast" => 2,
		"blastRange" => "short",
		"health" => 5,
		"hyper" => 0,
		"abilities" => array(
			"Cloak" => array("color" => "red",),
			"Force Field" => array("color" => "red",),
			"Jump" => array(),)
	),
  
	"zor-macros_alpha_zor-sectus" => array(
		"name" => "Zor-Macros",
		"type" => "monster",
		"form" => "Zor-Sectus",
		"faction" => "Shadow Sun Syndicate",
		"agenda" => "Collaborators",
		"energyType" => "Biotech",
		"set" => "All Your Base",
		"rarity" => 3,
		"speed" => 7,
		"defense" => 5,
		"brawl" => 3,
		"brawlBoost" => 1,
		"blast" => 3,
		"blastBoost" => 1,
		"blastRange" => "short",
		"health" => 5,
		"hyper" => 0,
		"abilities" => array(
			"Sprint" => array("color" => "red",),
			"Chain Reaction" => array("trigger" => "brawl", ),
			"Jump" => array(),
			"Power Sink" => array(),)
	),
  
	"zor-macros_ultra" => array(
		"name" => "Zor-Macros",
		"type" => "monster",
		"form" => "Ultra",
		"faction" => "Shadow Sun Syndicate",
		"agenda" => "Collaborators",
		"energyType" => "Biotech",
		"set" => "All Your Base",
		"rarity" => 3,
		"speed" => 8,
		"defense" => 7,
		"brawl" => 8,
		"brawlBoost" => 3,
		"blast" => 6,
		"blastBoost" => 3,
		"blastRange" => "long",
		"power" => 7,
		"powerBoost" => 3,
		"health" => 5,
		"hyper" => 3,
		"abilities" => array(
			"Energy Cycle" => array(),
			"Lightning Attack" => array("trigger" => "brawl", ),
			"Weapon Master" => array("trigger" => "power", ),
			"Cloak" => array(),
			"Jump_short" => array(),)
	),
  
	"zor-macros_mega" => array(
		"name" => "Zor-Macros",
		"type" => "monster",
		"form" => "Mega",
		"faction" => "Shadow Sun Syndicate",
		"agenda" => "Collaborators",
		"energyType" => "Biotech",
		"set" => "All Your Base",
		"setColor" => "blue",
		"rarity" => 4,
		"speed" => 7,
		"defense" => 7,
		"brawl" => 7,
		"brawlBoost" => 3,
		"blast" => 7,
		"blastBoost" => 3,
		"blastRange" => "short",
		"power" => 6,
		"powerBoost" => 3,
		"health" => 5,
		"hyper" => 3,
		"abilities" => array(
			"Sprint" => array(),
			"Crunch" => array("trigger" => "brawl", ),
			"Weapon Master" => array("trigger" => "power", ),
			"Jump" => array(),
			"Martial Artist" => array(),)
	),
  
	"zor-magna_alpha" => array(
		"name" => "Zor-Magna",
		"type" => "monster",
		"form" => "Alpha",
		"faction" => "Shadow Sun Syndicate",
		"agenda" => "Collaborators",
		"energyType" => "Biotech",
		"set" => "I Chomp NY",
		"rarity" => 3,
		"speed" => 7,
		"defense" => 7,
		"brawl" => 6,
		"brawlBoost" => 2,
		"blast" => 7,
		"blastBoost" => 2,
		"blastRange" => "long",
		"power" => 6,
		"powerBoost" => 1,
		"health" => 5,
		"hyper" => 0,
		"abilities" => array(
			"Fission" => array(),
			"Multi-shot" => array("trigger" => "blast", ),
			"Jump" => array(),
			"Sniper" => array("color" => "red",),)
	),
  
	"zor-magna_ultra" => array(
		"name" => "Zor-Magna",
		"type" => "monster",
		"form" => "Ultra",
		"faction" => "Shadow Sun Syndicate",
		"agenda" => "Collaborators",
		"energyType" => "Biotech",
		"set" => "I Chomp NY",
		"rarity" => 3,
		"speed" => 8,
		"defense" => 7,
		"brawl" => 7,
		"brawlBoost" => 2,
		"blast" => 7,
		"blastBoost" => 3,
		"blastRange" => "long",
		"power" => 8,
		"powerBoost" => 2,
		"health" => 5,
		"hyper" => 3,
		"abilities" => array(
			"Fission" => array(),
			"Fling" => array("trigger" => "blast", ),
			"Following Fire" => array("trigger" => "power", ),
			"Jump_short" => array(),
			"Sniper" => array("color" => "blue", ),)
	),
  
	"zor-magna_mega" => array(
		"name" => "Zor-Magna",
		"type" => "monster",
		"form" => "Mega",
		"faction" => "Shadow Sun Syndicate",
		"agenda" => "Collaborators",
		"energyType" => "Biotech",
		"set" => "I Chomp NY",
		"setColor" => "blue",
		"rarity" => 4,
		"speed" => 7,
		"defense" => 7,
		"brawl" => 6,
		"brawlBoost" => 3,
		"blast" => 7,
		"blastBoost" => 3,
		"blastRange" => "short",
		"power" => 6,
		"powerBoost" => 3,
		"health" => 5,
		"hyper" => 2,
		"abilities" => array(
			"Fission" => array(),
			"Chain Attack" => array("trigger" => "brawl", ),
			"Chain Reaction" => array("trigger" => "blast", ),
			"Jump_short" => array(),
			"Sniper" => array("color" => "blue", ),)
	),
  
	"zor-maxim_alpha" => array(
		"name" => "Zor-Maxim",
		"type" => "monster",
		"form" => "Alpha",
		"faction" => "Shadow Sun Syndicate",
		"agenda" => "Collaborators",
		"energyType" => "Biotech",
		"set" => "Rise",
		"rarity" => 3,
		"speed" => 7,
		"defense" => 7,
		"brawl" => 7,
		"brawlBoost" => 2,
		"power" => 7,
		"powerBoost" => 3,
		"health" => 5,
		"hyper" => 0,
		"abilities" => array(
			"Siphon" => array("trigger" => "brawl", ),
			"Infiltrate" => array("color" => "blue", ),
			"Jump" => array(),
			"Motivator" => array(),)
	),
  
	"zor-maxim_ultra" => array(
		"name" => "Zor-Maxim",
		"type" => "monster",
		"form" => "Ultra",
		"faction" => "Shadow Sun Syndicate",
		"agenda" => "Collaborators",
		"energyType" => "Biotech",
		"set" => "Rise",
		"rarity" => 3,
		"speed" => 7,
		"defense" => 8,
		"brawl" => 7,
		"brawlBoost" => 3,
		"blast" => 4,
		"blastBoost" => 3,
		"blastRange" => "short",
		"power" => 8,
		"powerBoost" => 4,
		"health" => 5,
		"hyper" => 4,
		"abilities" => array(
			"Siphon" => array("trigger" => "brawl", ),
			"Weapon Master" => array("trigger" => "power", ),
			"Armor Piercing" => array(),
			"Infiltrate" => array("color" => "blue", ),
			"Jump" => array(),)
	),
  
	"zor-maxim_mega" => array(
		"name" => "Zor-Maxim",
		"type" => "monster",
		"form" => "Mega",
		"faction" => "Shadow Sun Syndicate",
		"agenda" => "Collaborators",
		"energyType" => "Biotech",
		"set" => "Rise",
		"setColor" => "blue",
		"rarity" => 5,
		"speed" => 7,
		"defense" => 7,
		"brawl" => 6,
		"brawlBoost" => 1,
		"blast" => 7,
		"blastBoost" => 4,
		"blastRange" => "long",
		"power" => 6,
		"powerBoost" => 2,
		"health" => 5,
		"hyper" => 6,
		"abilities" => array(
			"Beat Back" => array("trigger" => "blast", ),
			"Weapon Master" => array("trigger" => "blast", ),
			"Infiltrate" => array("color" => "blue", ),
			"Jump" => array(),
			"Radar" => array(),)
	),
  
	"zor-raiden_alpha" => array(
		"name" => "Zor-Raiden",
		"type" => "monster",
		"form" => "Alpha",
		"faction" => "Shadow Sun Syndicate",
		"agenda" => "Collaborators",
		"energyType" => "Biotech",
		"set" => "Rise",
		"rarity" => 3,
		"speed" => 7,
		"defense" => 7,
		"brawl" => 8,
		"brawlBoost" => 2,
		"power" => 6,
		"powerBoost" => 2,
		"health" => 5,
		"hyper" => 0,
		"abilities" => array(
			"Lightning Attack" => array("trigger" => "brawl", ),
			"Charge" => array("color" => "blue", ),
			"Disable" => array(),
			"Jump" => array(),)
	),
  
	"zor-raiden_ultra" => array(
		"name" => "Zor-Raiden",
		"type" => "monster",
		"form" => "Ultra",
		"faction" => "Shadow Sun Syndicate",
		"agenda" => "Collaborators",
		"energyType" => "Biotech",
		"set" => "Rise",
		"rarity" => 3,
		"speed" => 7,
		"defense" => 7,
		"brawl" => 8,
		"brawlBoost" => 3,
		"blast" => 4,
		"blastBoost" => 2,
		"blastRange" => "short",
		"power" => 7,
		"powerBoost" => 2,
		"health" => 5,
		"hyper" => 3,
		"abilities" => array(
			"Power Cycle" => array(),
			"Lightning Attack" => array("trigger" => "brawl", ),
			"Charge" => array("color" => "blue", ),
			"Cloak" => array(),
			"Side Step" => array(),)
	),
  
	"zor-raiden_mega" => array(
		"name" => "Zor-Raiden",
		"type" => "monster",
		"form" => "Mega",
		"faction" => "Shadow Sun Syndicate",
		"agenda" => "Collaborators",
		"energyType" => "Biotech",
		"set" => "Rise",
		"setColor" => "blue",
		"rarity" => 5,
		"speed" => 8,
		"defense" => 7,
		"brawl" => 6,
		"brawlBoost" => 2,
		"blast" => 7,
		"blastBoost" => 3,
		"blastRange" => "short",
		"power" => 6,
		"powerBoost" => 2,
		"health" => 5,
		"hyper" => 5,
		"abilities" => array(
			"Chain Attack" => array("trigger" => "brawl", ),
			"Hit and Run" => array("trigger" => "brawl", ),
			"Fling_short" => array("trigger" => "blast", ),
			"Distract" => array(),
			"Jump_short" => array(),
			"Riled" => array(),)
	),
  
	"zor-voltis_alpha" => array(
		"name" => "Zor-Voltis",
		"type" => "monster",
		"form" => "Alpha",
		"faction" => "Shadow Sun Syndicate",
		"agenda" => "Collaborators",
		"energyType" => "Biotech",
		"set" => "I Chomp NY",
		"rarity" => 3,
		"speed" => 8,
		"defense" => 6,
		"brawl" => 7,
		"brawlBoost" => 1,
		"blast" => 6,
		"blastBoost" => 2,
		"blastRange" => "short",
		"power" => 7,
		"powerBoost" => 2,
		"health" => 6,
		"hyper" => 0,
		"abilities" => array(
			"Marker" => array("color" => "red",),
			"Hit and Run" => array("color" => "blue", "trigger" => "blast", ),
			"Hit and Run " => array("trigger" => "power", ),
			"Jump" => array(),)
	),
  
	"zor-voltis_ultra" => array(
		"name" => "Zor-Voltis",
		"type" => "monster",
		"form" => "Ultra",
		"faction" => "Shadow Sun Syndicate",
		"agenda" => "Collaborators",
		"energyType" => "Biotech",
		"set" => "I Chomp NY",
		"rarity" => 3,
		"speed" => 7,
		"defense" => 7,
		"brawl" => 7,
		"brawlBoost" => 1,
		"blast" => 6,
		"blastBoost" => 4,
		"blastRange" => "long",
		"power" => 7,
		"powerBoost" => 3,
		"health" => 5,
		"hyper" => 3,
		"abilities" => array(
			"Hit and Run" => array("color" => "blue", "trigger" => "blast", ),
			"Power Gorge" => array("trigger" => "blast", ),
			"Hit and Run " => array("trigger" => "power", ),
			"Annihilate" => array(),
			"Jump" => array(),)
	),
  
	"zor-voltis_mega" => array(
		"name" => "Zor-Voltis",
		"type" => "monster",
		"form" => "Mega",
		"faction" => "Shadow Sun Syndicate",
		"agenda" => "Collaborators",
		"energyType" => "Biotech",
		"set" => "I Chomp NY",
		"setColor" => "blue",
		"rarity" => 4,
		"speed" => 7,
		"defense" => 7,
		"brawl" => 8,
		"brawlBoost" => 2,
		"blast" => 8,
		"blastBoost" => 3,
		"blastRange" => "short",
		"power" => 8,
		"powerBoost" => 2,
		"health" => 5,
		"hyper" => 5,
		"abilities" => array(
			"Chain Attack" => array("trigger" => "brawl", ),
			"Following Fire" => array("trigger" => "power", ),
			"Hit and Run" => array("trigger" => "power", ),
			"Cloak" => array("color" => "red",),
			"Jump" => array(),)
	),
  
	"sun_industries" => array(
		"name" => "Sun Industries",
		"type" => "building",
		"hazard" => "rubble",
		"faction" => "Shadow Sun Syndicate",
		"agenda" => "Collaborators",
		"set" => "All Your Base",
		"rarity" => 3,
		"defense" => 5,
		"energy" => 5,
		"abilities" => array(
			"Business Center" => array(),
			"Power Gorge" => array("trigger" => "blast", "color" => "red",),
			"Discount" => array(),
			"Force Field" => array("color" => "red",),
			"Shuffle" => array(),)
	),
  
	"c-type_shinobi_grunt" => array(
		"name" => "C-Type Shinobi",
		"type" => "unit",
		"class" => "Grunt",
		"faction" => "Shadow Sun Syndicate",
		"agenda" => "Collaborators",
		"energyType" => "Biotech",
		"set" => "I Chomp NY",
		"rarity" => 1,
		"speed" => 5,
		"defense" => 3,
		"brawl" => 1,
		"blast" => 1,
		"blastBoost" => 1,
		"blastRange" => "short",
		"cost" => 1,
		"abilities" => array(
			"Disrupt" => array("trigger" => "blast", ),
			"Power Drain" => array("trigger" => "blast", ),
			"Cargo" => array(),)
	),
  
	"c-type_shinobi_elite" => array(
		"name" => "C-Type Shinobi",
		"type" => "unit",
		"class" => "Elite",
		"faction" => "Shadow Sun Syndicate",
		"agenda" => "Collaborators",
		"energyType" => "Biotech",
		"set" => "I Chomp NY",
		"rarity" => 2,
		"speed" => 5,
		"defense" => 3,
		"brawl" => 1,
		"brawlBoost" => 1,
		"blast" => 1,
		"blastBoost" => 2,
		"blastRange" => "short",
		"cost" => 2,
		"abilities" => array(
			"Disrupt" => array("trigger" => "blast", ),
			"Power Drain" => array("trigger" => "blast", ),
			"Cargo" => array(),
			"Leadership" => array(),)
	),
  
	"c-type_shinobi_shadow" => array(
		"name" => "C-Type Shinobi",
		"type" => "unit",
		"form" => "Shadow",
		"class" => "Grunt",
		"faction" => "Shadow Sun Syndicate",
		"agenda" => "Collaborators",
		"energyType" => "Biotech",
		"set" => "I Chomp NY",
		"setColor" => "blue",
		"rarity" => 4,
		"speed" => 5,
		"defense" => 3,
		"brawl" => 1,
		"blast" => 1,
		"blastBoost" => 1,
		"blastRange" => "short",
		"cost" => 2,
		"abilities" => array(
			"Disrupt" => array("trigger" => "blast", ),
			"Power Drain" => array("trigger" => "blast", ),
			"Cargo" => array(),
			"Cloak" => array(),)
	),
  
	"interceptor_grunt" => array(
		"name" => "Interceptor",
		"type" => "unit",
		"class" => "Grunt",
		"faction" => "Shadow Sun Syndicate",
		"agenda" => "Collaborators",
		"energyType" => "Mechanical",
		"set" => "Rise",
		"rarity" => 3,
		"speed" => 7,
		"defense" => 3,
		"blast" => 1,
		"blastRange" => "short",
		"cost" => 1,
		"abilities" => array(
			"Transport" => array(),
			"Hover" => array(),)
	),
  
	"katana_grunt" => array(
		"name" => "Katana",
		"type" => "unit",
		"class" => "Grunt",
		"faction" => "Shadow Sun Syndicate",
		"agenda" => "Collaborators",
		"energyType" => "Mechanical",
		"set" => "I Chomp NY",
		"rarity" => 1,
		"speed" => 7,
		"defense" => 3,
		"blast" => 1,
		"blastRange" => "long",
		"cost" => 1,
		"abilities" => array(
			"Chain Reaction" => array("trigger" => "blast", ),
			"High Impact" => array("color" => "red",),
			"Hover" => array(),)
	),
  
	"katana_elite" => array(
		"name" => "Katana",
		"type" => "unit",
		"class" => "Elite",
		"faction" => "Shadow Sun Syndicate",
		"agenda" => "Collaborators",
		"energyType" => "Mechanical",
		"set" => "I Chomp NY",
		"rarity" => 3,
		"speed" => 7,
		"defense" => 3,
		"blast" => 1,
		"blastBoost" => 1,
		"blastRange" => "long",
		"cost" => 2,
		"abilities" => array(
			"Chain Reaction" => array("trigger" => "blast", ),
			"High Impact" => array("color" => "red",),
			"Hover" => array(),
			"Leadership" => array(),)
	),
  
	"s-type_shinobi_grunt" => array(
		"name" => "S-Type Shinobi",
		"type" => "unit",
		"class" => "Grunt",
		"faction" => "Shadow Sun Syndicate",
		"agenda" => "Collaborators",
		"energyType" => "Biotech",
		"set" => "Rise",
		"rarity" => 1,
		"speed" => 6,
		"defense" => 3,
		"brawl" => 2,
		"cost" => 1,
		"abilities" => array(
			"Cloak" => array(),
			"Flank" => array(),
			"Jump" => array(),)
	),
  
	"s-type_shinobi_elite" => array(
		"name" => "S-Type Shinobi",
		"type" => "unit",
		"class" => "Elite",
		"faction" => "Shadow Sun Syndicate",
		"agenda" => "Collaborators",
		"energyType" => "Biotech",
		"set" => "Rise",
		"rarity" => 2,
		"speed" => 6,
		"defense" => 3,
		"brawl" => 2,
		"brawlBoost" => 1,
		"cost" => 2,
		"abilities" => array(
			"Cloak" => array(),
			"Flank" => array(),
			"Jump" => array(),
			"Leadership" => array(),)
	),
  
	"shadow_gate_grunt" => array(
		"name" => "Shadow Gate",
		"type" => "unit",
		"class" => "Grunt",
		"faction" => "Shadow Sun Syndicate",
		"agenda" => "Collaborators",
		"energyType" => "Mechanical",
		"set" => "Rise",
		"rarity" => 3,
		"speed" => 3,
		"defense" => 2,
		"cost" => 1,
		"abilities" => array(
			"Teleport" => array(),
			"Cargo" => array(),
			"Cloak" => array("color" => "red",),
			"Hover" => array(),)
	),
  
	"shadow_raider_grunt" => array(
		"name" => "Shadow Raider",
		"type" => "unit",
		"class" => "Grunt",
		"faction" => "Shadow Sun Syndicate",
		"agenda" => "Collaborators",
		"energyType" => "Mechanical",
		"set" => "All Your Base",
		"rarity" => 1,
		"speed" => 5,
		"defense" => 3,
		"blast" => 2,
		"blastRange" => "short",
		"cost" => 1,
		"abilities" => array(
			"Bomber" => array(),
			"Flight" => array(),
			"High Impact" => array(),)
	),
  
	"shadow_raider_elite" => array(
		"name" => "Shadow Raider",
		"type" => "unit",
		"class" => "Elite",
		"faction" => "Shadow Sun Syndicate",
		"agenda" => "Collaborators",
		"energyType" => "Mechanical",
		"set" => "All Your Base",
		"rarity" => 1,
		"speed" => 5,
		"defense" => 3,
		"blast" => 2,
		"blastBoost" => 1,
		"blastRange" => "short",
		"cost" => 2,
		"abilities" => array(
			"Bomber" => array(),
			"Flight" => array(),
			"High Impact" => array(),
			"Leadership" => array(),)
	),
  
	"shadow_raider_shadow" => array(
		"name" => "Shadow Raider",
		"type" => "unit",
		"form" => "Shadow",
		"class" => "Grunt",
		"faction" => "Shadow Sun Syndicate",
		"agenda" => "Collaborators",
		"energyType" => "Mechanical",
		"set" => "All Your Base",
		"setColor" => "blue",
		"rarity" => 4,
		"speed" => 5,
		"defense" => 3,
		"blast" => 2,
		"blastRange" => "short",
		"cost" => 2,
		"abilities" => array(
			"Bomber" => array(),
			"Cloak" => array(),
			"Flight" => array(),
			"High Impact" => array(),)
	),
  
	"sun_drone_grunt" => array(
		"name" => "Sun Drone",
		"type" => "unit",
		"class" => "Grunt",
		"faction" => "Shadow Sun Syndicate",
		"agenda" => "Collaborators",
		"energyType" => "Mechanical",
		"set" => "All Your Base",
		"rarity" => 3,
		"speed" => 3,
		"defense" => 3,
		"brawl" => 2,
		"cost" => 1,
		"abilities" => array(
			"Cargo" => array(),
			"Hover" => array(),
			"No-Fly Zone" => array(),
			"Satellite Support" => array(),)
	),
  
	"sun_fighter_grunt" => array(
		"name" => "Sun Fighter",
		"type" => "unit",
		"class" => "Grunt",
		"faction" => "Shadow Sun Syndicate",
		"agenda" => "Collaborators",
		"energyType" => "Mechanical",
		"set" => "Rise",
		"rarity" => 1,
		"speed" => 6,
		"defense" => 3,
		"blast" => 2,
		"blastRange" => "long",
		"cost" => 1,
		"abilities" => array(
			"Anti-air" => array(),
			"Flight" => array(),)
	),
  
	"sun_fighter_elite" => array(
		"name" => "Sun Fighter",
		"type" => "unit",
		"class" => "Elite",
		"faction" => "Shadow Sun Syndicate",
		"agenda" => "Collaborators",
		"energyType" => "Mechanical",
		"set" => "Rise",
		"rarity" => 2,
		"speed" => 6,
		"defense" => 3,
		"blast" => 2,
		"blastBoost" => 1,
		"blastRange" => "long",
		"cost" => 2,
		"abilities" => array(
			"Anti-air" => array(),
			"Flight" => array(),
			"Leadership" => array(),)
	),

	"sun_fighter_shadow" => array(
		"name" => "Sun Fighter",
		"type" => "unit",
		"form" => "Shadow",
		"class" => "Elite",
		"faction" => "Shadow Sun Syndicate",
		"agenda" => "Collaborators",
		"energyType" => "Mechanical",
		"set" => "Rise",
		"setColor" => "blue",
		"rarity" => 5,
		"speed" => 6,
		"defense" => 3,
		"blast" => 2,
		"blastBoost" => 1,
		"blastRange" => "long",
		"cost" => 3,
		"abilities" => array(
			"Anti-air" => array(),
			"Cloak" => array(),
			"Flight" => array(),
			"Leadership" => array(),)
	),

