


/*    =============    Subterran Uprising    =============    */

	"blastik-rukivall_alpha" => array(
		"name" => "Blastik-Rukivall",
		"type" => "monster",
		"form" => "Alpha",
		"faction" => "Subterran Uprising",
		"agenda" => "Fiends",
		"energyType" => "Biotech",
		"set" => "Big in Japan",
		"rarity" => 3,
		"speed" => 5,
		"defense" => 6,
		"brawl" => 6,
		"brawlBoost" => 1,
		"blast" => 6,
		"blastBoost" => 3,
		"blastRange" => "long",
		"power" => 7,
		"powerBoost" => 1,
		"health" => 5,
		"hyper" => 0,
		"abilities" => array(
			"Energy Cycle" => array(),
			"Blitz" => array("trigger" => "blast", ),
			"Siphon" => array("trigger" => "blast", ),
			"Shelter" => array("color" => "blue", ),)
	),
  
	"blastik-rukivall_ultra" => array(
		"name" => "Blastik-Rukivall",
		"type" => "monster",
		"form" => "Ultra",
		"faction" => "Subterran Uprising",
		"agenda" => "Fiends",
		"energyType" => "Biotech",
		"set" => "Big in Japan",
		"rarity" => 3,
		"speed" => 6,
		"defense" => 7,
		"brawl" => 6,
		"brawlBoost" => 2,
		"blast" => 9,
		"blastBoost" => 4,
		"blastRange" => "long",
		"power" => 8,
		"powerBoost" => 2,
		"health" => 5,
		"hyper" => 4,
		"abilities" => array(
			"Beat Back" => array("trigger" => "blast", ),
			"Demolish" => array("trigger" => "blast", ),
			"Power Strike" => array("trigger" => "blast", ),
			"Force Field" => array("color" => "blue", ),)
	),
  
	"blastik-rukivall_mega" => array(
		"name" => "Blastik-Rukivall",
		"type" => "monster",
		"form" => "Mega",
		"faction" => "Subterran Uprising",
		"agenda" => "Fiends",
		"energyType" => "Biotech",
		"set" => "Big in Japan",
		"setColor" => "blue",
		"rarity" => 4,
		"speed" => 7,
		"defense" => 5,
		"brawl" => 6,
		"brawlBoost" => 1,
		"blast" => 9,
		"blastBoost" => 4,
		"blastRange" => "long",
		"power" => 7,
		"powerBoost" => 3,
		"health" => 5,
		"hyper" => 4,
		"abilities" => array(
			"Energy Cycle" => array(),
			"Power Cycle" => array(),
			"Disrupt" => array("trigger" => "blast", ),
			"Following Fire" => array("trigger" => "power", ),
			"Super Smash" => array(),)
	),
  
	"drillcon-vorionnik_alpha" => array(
		"name" => "Drillcon-Vorionnik",
		"type" => "monster",
		"form" => "Alpha",
		"faction" => "Subterran Uprising",
		"agenda" => "Fiends",
		"energyType" => "Biotech",
		"set" => "Now",
		"rarity" => 3,
		"speed" => 5,
		"defense" => 6,
		"brawl" => 6,
		"brawlBoost" => 2,
		"blast" => 5,
		"blastBoost" => 1,
		"blastRange" => "short",
		"power" => 7,
		"powerBoost" => 2,
		"health" => 6,
		"hyper" => 0,
		"abilities" => array(
			"Multi-shot" => array("trigger" => "brawl", ),
			"Burrow" => array(),
			"Dig In" => array("color" => "blue", ),
			"Riled" => array(),)
	),
  
	"drillcon-vorionnik_ultra" => array(
		"name" => "Drillcon-Vorionnik",
		"type" => "monster",
		"form" => "Ultra",
		"faction" => "Subterran Uprising",
		"agenda" => "Fiends",
		"energyType" => "Biotech",
		"set" => "Now",
		"rarity" => 3,
		"speed" => 6,
		"defense" => 7,
		"brawl" => 7,
		"brawlBoost" => 3,
		"blast" => 5,
		"blastBoost" => 1,
		"blastRange" => "short",
		"power" => 7,
		"powerBoost" => 3,
		"health" => 5,
		"hyper" => 3,
		"abilities" => array(
			"Multi-shot" => array("trigger" => "brawl", ),
			"Weapon Master" => array("trigger" => "brawl", ),
			"Burrow" => array(),
			"Dig In" => array("color" => "blue", ),
			"Fortified" => array("color" => "blue", ),)
	),
  
	"drillcon-vorionnik_mega" => array(
		"name" => "Drillcon-Vorionnik",
		"type" => "monster",
		"form" => "Mega",
		"faction" => "Subterran Uprising",
		"agenda" => "Fiends",
		"energyType" => "Biotech",
		"set" => "Now",
		"setColor" => "blue",
		"rarity" => 4,
		"speed" => 6,
		"defense" => 5,
		"brawl" => 6,
		"brawlBoost" => 3,
		"blast" => 7,
		"blastBoost" => 3,
		"blastRange" => "long",
		"power" => 7,
		"powerBoost" => 2,
		"health" => 6,
		"hyper" => 4,
		"abilities" => array(
			"Crunch" => array("trigger" => "brawl", ),
			"Following Fire" => array("trigger" => "brawl", ),
			"Demolish" => array("trigger" => "blast", ),
			"Explosion" => array("trigger" => "blast", ),
			"Burrow" => array(),)
	),
  
	"grindix-birvikaan_alpha" => array(
		"name" => "Grindix-Birvikaan",
		"type" => "monster",
		"form" => "Alpha",
		"faction" => "Subterran Uprising",
		"agenda" => "Fiends",
		"energyType" => "Biotech",
		"set" => "Now",
		"rarity" => 3,
		"speed" => 6,
		"defense" => 6,
		"brawl" => 7,
		"brawlBoost" => 3,
		"power" => 6,
		"powerBoost" => 2,
		"health" => 6,
		"hyper" => 0,
		"abilities" => array(
			"Lightning Attack" => array("trigger" => "brawl", ),
			"Power Drain" => array("trigger" => "brawl", ),
			"Synchronized Move" => array("trigger" => "brawl", ),
			"Burrow" => array(),
			"Distract" => array("color" => "red",),
			"Super Stomp" => array(),)
	),
  
	"grindix-birvikaan_ultra" => array(
		"name" => "Grindix-Birvikaan",
		"type" => "monster",
		"form" => "Ultra",
		"faction" => "Subterran Uprising",
		"agenda" => "Fiends",
		"energyType" => "Biotech",
		"set" => "Now",
		"rarity" => 3,
		"speed" => 7,
		"defense" => 6,
		"brawl" => 8,
		"brawlBoost" => 4,
		"power" => 7,
		"powerBoost" => 3,
		"health" => 5,
		"hyper" => 4,
		"abilities" => array(
			"Energy Sap" => array("trigger" => "brawl", ),
			"Grind" => array("trigger" => "brawl", ),
			"Burrow" => array(),
			"Distract" => array("color" => "red",),
			"Super Stomp" => array(),)
	),
  
	"grindix-birvikaan_mega" => array(
		"name" => "Grindix-Birvikaan",
		"type" => "monster",
		"form" => "Mega",
		"faction" => "Subterran Uprising",
		"agenda" => "Fiends",
		"energyType" => "Biotech",
		"set" => "Now",
		"setColor" => "blue",
		"rarity" => 4,
		"speed" => 7,
		"defense" => 7,
		"brawl" => 8,
		"brawlBoost" => 3,
		"power" => 6,
		"powerBoost" => 3,
		"health" => 5,
		"hyper" => 4,
		"abilities" => array(
			"Crunch" => array("trigger" => "power", ),
			"Burrow" => array(),
			"Distract" => array("color" => "red",),
			"Jam" => array(),
			"Super Smash" => array(),)
	),
  
	"hammerklak-korvissik_alpha" => array(
		"name" => "Hammerklak-Korvissik",
		"type" => "monster",
		"form" => "Alpha",
		"faction" => "Subterran Uprising",
		"agenda" => "Fiends",
		"energyType" => "Biotech",
		"set" => "Big in Japan",
		"rarity" => 3,
		"speed" => 6,
		"defense" => 5,
		"brawl" => 6,
		"brawlBoost" => 2,
		"power" => 6,
		"powerBoost" => 2,
		"health" => 5,
		"hyper" => 0,
		"abilities" => array(
			"Crunch" => array("trigger" => "brawl", ),
			"Burrow" => array(),
			"Super Stomp" => array(),
			"Super Strength" => array(),)
	),
  
	"hammerklak-korvissik_ultra" => array(
		"name" => "Hammerklak-Korvissik",
		"type" => "monster",
		"form" => "Ultra",
		"faction" => "Subterran Uprising",
		"agenda" => "Fiends",
		"energyType" => "Biotech",
		"set" => "Big in Japan",
		"rarity" => 3,
		"speed" => 6,
		"defense" => 6,
		"brawl" => 7,
		"brawlBoost" => 3,
		"blast" => 4,
		"blastBoost" => 1,
		"blastRange" => "short",
		"power" => 6,
		"powerBoost" => 2,
		"health" => 5,
		"hyper" => 4,
		"abilities" => array(
			"Sprint" => array(),
			"Follow Through" => array("trigger" => "brawl", ),
			"Burrow" => array(),
			"Super Strength" => array(),
			"Side Step" => array(),)
	),
  
	"hammerklak-korvissik_mega" => array(
		"name" => "Hammerklak-Korvissik",
		"type" => "monster",
		"form" => "Mega",
		"faction" => "Subterran Uprising",
		"agenda" => "Fiends",
		"energyType" => "Biotech",
		"set" => "Big in Japan",
		"setColor" => "blue",
		"rarity" => 4,
		"speed" => 6,
		"defense" => 6,
		"brawl" => 8,
		"brawlBoost" => 4,
		"blast" => 5,
		"blastBoost" => 1,
		"blastRange" => "short",
		"power" => 7,
		"powerBoost" => 3,
		"health" => 5,
		"hyper" => 4,
		"abilities" => array(
			"Lightning Attack" => array("trigger" => "brawl", ),
			"Power Gorge" => array("trigger" => "brawl", ),
			"Follow Through" => array("trigger" => "blast", ),
			"Burrow" => array(),
			"Super Strength" => array(),)
	),
  
	"ral_kurrilik" => array(
		"name" => "Ral Kurrilik",
		"type" => "character",
		"form" => "Grinder Tank",
		"class" => "Elite",
		"faction" => "Subterran Uprising",
		"agenda" => "Fiends",
		"energyType" => "Mechanical",
		"set" => "Big in Japan",
		"rarity" => 4,
		"speed" => 5,
		"defense" => 4,
		"brawl" => 3,
		"brawlBoost" => 1,
		"blast" => 3,
		"blastBoost" => 1,
		"blastRange" => "short",
		"cost" => 2,
		"abilities" => array(
			"Rage" => array("color" => "red",),
			"Burrow" => array(),
			"Limited" => array(),
			"Side Step" => array(),)
	),

	"grinder_tank_grunt" => array(
		"name" => "Grinder Tank",
		"type" => "unit",
		"class" => "Grunt",
		"faction" => "Subterran Uprising",
		"agenda" => "Fiends",
		"energyType" => "Mechanical",
		"set" => "Big in Japan",
		"rarity" => 1,
		"speed" => 5,
		"defense" => 4,
		"brawl" => 3,
		"blast" => 3,
		"blastRange" => "short",
		"cost" => 1,
		"abilities" => array(
			"Marker" => array(),
			"Flak" => array("trigger" => "blast", ),
			"Burrow" => array(),)
	),
  
	"grinder_tank_elite" => array(
		"name" => "Grinder Tank",
		"type" => "unit",
		"class" => "Elite",
		"faction" => "Subterran Uprising",
		"agenda" => "Fiends",
		"energyType" => "Mechanical",
		"set" => "Big in Japan",
		"rarity" => 3,
		"speed" => 5,
		"defense" => 4,
		"brawl" => 3,
		"brawlBoost" => 1,
		"blast" => 3,
		"blastBoost" => 1,
		"blastRange" => "short",
		"cost" => 2,
		"abilities" => array(
			"Marker" => array(),
			"Flak" => array("trigger" => "blast", ),
			"Burrow" => array(),
			"Leadership" => array(),)
	),
  
	"groundbreaker_grunt" => array(
		"name" => "Groundbreaker",
		"type" => "unit",
		"class" => "Grunt",
		"faction" => "Subterran Uprising",
		"agenda" => "Fiends",
		"energyType" => "Biotech",
		"set" => "Now",
		"rarity" => 1,
		"speed" => 6,
		"defense" => 2,
		"brawl" => 2,
		"cost" => 1,
		"abilities" => array(
			"Pathfinder" => array("color" => "red",),
			"Burrow" => array(),
			"Flank" => array(),)
	),
  
	"mollok_berserker_grunt" => array(
		"name" => "Mollok Berserker",
		"type" => "unit",
		"class" => "Grunt",
		"faction" => "Subterran Uprising",
		"agenda" => "Fiends",
		"energyType" => "Biotech",
		"set" => "Now",
		"rarity" => 2,
		"speed" => 5,
		"defense" => 3,
		"brawl" => 2,
		"brawlBoost" => 1,
		"cost" => 2,
		"abilities" => array(
			"Rage" => array(),
			"Berserk" => array("color" => "red",),
			"Jump" => array(),
			"Riled" => array(),)
	),
  
	"mollok_brute_grunt" => array(
		"name" => "Mollok Brute",
		"type" => "unit",
		"class" => "Grunt",
		"faction" => "Subterran Uprising",
		"agenda" => "Fiends",
		"energyType" => "Biotech",
		"set" => "Now",
		"rarity" => 1,
		"speed" => 5,
		"defense" => 4,
		"brawl" => 1,
		"brawlBoost" => 1,
		"cost" => 1,
		"abilities" => array(
			"Jump" => array(),)
	),
  
	"mollok_brute_elite" => array(
		"name" => "Mollok Brute",
		"type" => "unit",
		"class" => "Elite",
		"faction" => "Subterran Uprising",
		"agenda" => "Fiends",
		"energyType" => "Biotech",
		"set" => "Now",
		"rarity" => 3,
		"speed" => 5,
		"defense" => 4,
		"brawl" => 1,
		"brawlBoost" => 2,
		"cost" => 2,
		"abilities" => array(
			"Champion" => array(),
			"Jump" => array(),
			"Leadership" => array(),)
	),
  
	"mollok_mortar_grunt" => array(
		"name" => "Mollok Mortar",
		"type" => "unit",
		"class" => "Grunt",
		"faction" => "Subterran Uprising",
		"agenda" => "Fiends",
		"energyType" => "Biotech",
		"set" => "Now",
		"rarity" => 1,
		"speed" => 4,
		"defense" => 3,
		"brawl" => 2,
		"blast" => 2,
		"blastBoost" => 1,
		"blastRange" => "short",
		"cost" => 1,
		"abilities" => array(
			"Power Drain" => array("trigger" => "blast", ),
			"Burrow" => array(),)
	),
  
	"mollok_mortar_elite" => array(
		"name" => "Mollok Mortar",
		"type" => "unit",
		"class" => "Elite",
		"faction" => "Subterran Uprising",
		"agenda" => "Fiends",
		"energyType" => "Biotech",
		"set" => "Now",
		"rarity" => 3,
		"speed" => 4,
		"defense" => 3,
		"brawl" => 2,
		"brawlBoost" => 1,
		"blast" => 2,
		"blastBoost" => 2,
		"blastRange" => "short",
		"cost" => 2,
		"abilities" => array(
			"Power Drain" => array("trigger" => "blast", ),
			"Burrow" => array(),
			"Leadership" => array(),)
	),
  
	"mollok_mortar_glass" => array(
		"name" => "Mollok Mortar",
		"type" => "unit",
		"form" => "Glass",
		"class" => "Grunt",
		"faction" => "Subterran Uprising",
		"agenda" => "Fiends",
		"energyType" => "Biotech",
		"set" => "Now",
		"setColor" => "blue",
		"rarity" => 4,
		"speed" => 6,
		"defense" => 3,
		"brawl" => 2,
		"brawlBoost" => 1,
		"blast" => 2,
		"blastBoost" => 1,
		"blastRange" => "short",
		"cost" => 1,
		"abilities" => array(
			"Power Drain" => array("trigger" => "blast", ),
			"Burrow" => array(),
			"Fragile" => array(),)
	),
  
	"oppressor_grunt" => array(
		"name" => "Oppressor",
		"type" => "unit",
		"class" => "Grunt",
		"faction" => "Subterran Uprising",
		"agenda" => "Fiends",
		"energyType" => "Biotech",
		"set" => "Big in Japan",
		"rarity" => 1,
		"speed" => 4,
		"defense" => 3,
		"brawl" => 3,
		"brawlBoost" => 1,
		"cost" => 1,
		"abilities" => array(
			"Abduct" => array(),
			"Tow" => array(),
			"Burrow" => array(),)
	),
  
	"oppressor_elite" => array(
		"name" => "Oppressor",
		"type" => "unit",
		"class" => "Elite",
		"faction" => "Subterran Uprising",
		"agenda" => "Fiends",
		"energyType" => "Biotech",
		"set" => "Big in Japan",
		"rarity" => 2,
		"speed" => 4,
		"defense" => 3,
		"brawl" => 3,
		"brawlBoost" => 2,
		"cost" => 2,
		"abilities" => array(
			"Abduct" => array(),
			"Tow" => array(),
			"Burrow" => array(),
			"Leadership" => array(),)
	),
  
	"oppressor_glass" => array(
		"name" => "Oppressor",
		"type" => "unit",
		"form" => "Glass",
		"class" => "Grunt",
		"faction" => "Subterran Uprising",
		"agenda" => "Fiends",
		"energyType" => "Biotech",
		"set" => "Big in Japan",
		"setColor" => "blue",
		"rarity" => 4,
		"speed" => 6,
		"defense" => 3,
		"brawl" => 3,
		"brawlBoost" => 1,
		"blast" => 2,
		"blastRange" => "short",
		"cost" => 1,
		"abilities" => array(
			"Abduct" => array("color" => "red",),
			"Tow" => array(),
			"Burrow" => array(),
			"Fragile" => array(),)
	),
  
