


/*    =============    Terrasaurs    =============    */

	"armodax_alpha" => array(
		"name" => "Armodax",
		"type" => "monster",
		"form" => "Alpha",
		"faction" => "Terrasaurs",
		"agenda" => "Radicals",
		"energyType" => "Nature",
		"set" => "Rise",
		"rarity" => 3,
		"speed" => 6,
		"defense" => 5,
		"brawl" => 7,
		"brawlBoost" => 2,
		"power" => 6,
		"powerBoost" => 2,
		"health" => 6,
		"hyper" => 0,
		"abilities" => array(
			"Hit and Run" => array("color" => "blue", "trigger" => "brawl", ),
			"Shelter" => array("color" => "red",),
			"Super Smash" => array(),
			"Super Stomp" => array(),)
	),
  
	"armodax_ultra" => array(
		"name" => "Armodax",
		"type" => "monster",
		"form" => "Ultra",
		"faction" => "Terrasaurs",
		"agenda" => "Radicals",
		"energyType" => "Nature",
		"set" => "Rise",
		"rarity" => 3,
		"speed" => 6,
		"defense" => 7,
		"brawl" => 8,
		"brawlBoost" => 3,
		"power" => 7,
		"powerBoost" => 2,
		"health" => 6,
		"hyper" => 4,
		"abilities" => array(
			"Resilience" => array(),
			"Super Smash" => array(),
			"Super Stomp" => array(),
			"Super Strength" => array(),)
	),
  
	"armodax_mega" => array(
		"name" => "Armodax",
		"type" => "monster",
		"form" => "Mega",
		"faction" => "Terrasaurs",
		"agenda" => "Radicals",
		"energyType" => "Nature",
		"set" => "Rise",
		"setColor" => "blue",
		"rarity" => 5,
		"speed" => 6,
		"defense" => 7,
		"brawl" => 6,
		"brawlBoost" => 2,
		"blast" => 8,
		"blastBoost" => 4,
		"blastRange" => "long",
		"power" => 4,
		"powerBoost" => 1,
		"health" => 6,
		"hyper" => 5,
		"abilities" => array(
			"Beat Back" => array("trigger" => "blast", ),
			"Atomize" => array(),
			"Resilience" => array(),
			"Solid" => array(),)
	),
  
	"pteradax_alpha" => array(
		"name" => "Pteradax",
		"type" => "monster",
		"form" => "Alpha",
		"faction" => "Terrasaurs",
		"agenda" => "Radicals",
		"energyType" => "Nature",
		"set" => "I Chomp NY",
		"rarity" => 3,
		"speed" => 7,
		"defense" => 7,
		"brawl" => 6,
		"brawlBoost" => 1,
		"blast" => 7,
		"blastBoost" => 2,
		"blastRange" => "long",
		"power" => 6,
		"powerBoost" => 2,
		"health" => 5,
		"hyper" => 0,
		"abilities" => array(
			"Summon" => array(),
			"Energy Sap" => array("color" => "red","trigger" => "brawl", ),
			"Flight" => array(),
			"Super Strength" => array(),)
	),
  
	"pteradax_ultra" => array(
		"name" => "Pteradax",
		"type" => "monster",
		"form" => "Ultra",
		"faction" => "Terrasaurs",
		"agenda" => "Radicals",
		"energyType" => "Nature",
		"set" => "I Chomp NY",
		"rarity" => 3,
		"speed" => 7,
		"defense" => 6,
		"brawl" => 6,
		"brawlBoost" => 2,
		"blast" => 7,
		"blastBoost" => 1,
		"blastRange" => "short",
		"power" => 7,
		"powerBoost" => 3,
		"health" => 7,
		"hyper" => 4,
		"abilities" => array(
			"Abduct" => array("color" => "blue", ),
			"Power Gorge" => array("trigger" => "brawl", ),
			"Follow Through" => array("trigger" => "power", ),
			"Hit and Run" => array("trigger" => "power", ),
			"Flight" => array(),)
	),
  
	"pteradax_mega" => array(
		"name" => "Pteradax",
		"type" => "monster",
		"form" => "Mega",
		"faction" => "Terrasaurs",
		"agenda" => "Radicals",
		"energyType" => "Nature",
		"set" => "I Chomp NY",
		"setColor" => "blue",
		"rarity" => 4,
		"speed" => 6,
		"defense" => 7,
		"brawl" => 8,
		"brawlBoost" => 3,
		"power" => 7,
		"powerBoost" => 2,
		"health" => 6,
		"hyper" => 4,
		"abilities" => array(
			"Tow" => array(),
			"Chain Attack" => array("trigger" => "brawl", ),
			"Energy Sap" => array("color" => "red","trigger" => "brawl", ),
			"Munch" => array("trigger" => "brawl", ),
			"Flight" => array(),)
	),
  
	"rakadon_alpha" => array(
		"name" => "Rakadon",
		"type" => "monster",
		"form" => "Alpha",
		"faction" => "Terrasaurs",
		"agenda" => "Radicals",
		"energyType" => "Nature",
		"set" => "I Chomp NY",
		"rarity" => 3,
		"speed" => 6,
		"defense" => 6,
		"brawl" => 6,
		"brawlBoost" => 3,
		"blast" => 5,
		"blastRange" => "short",
		"power" => 6,
		"powerBoost" => 2,
		"health" => 6,
		"hyper" => 0,
		"abilities" => array(
			"Hit and Run" => array("color" => "red","trigger" => "brawl", ),
			"Munch" => array("trigger" => "brawl", ),
			"Berserk" => array("color" => "blue", ),
			"Flank" => array("color" => "red",),)
	),
  
	"rakadon_ultra" => array(
		"name" => "Rakadon",
		"type" => "monster",
		"form" => "Ultra",
		"faction" => "Terrasaurs",
		"agenda" => "Radicals",
		"energyType" => "Nature",
		"set" => "I Chomp NY",
		"rarity" => 3,
		"speed" => 6,
		"defense" => 7,
		"brawl" => 8,
		"brawlBoost" => 3,
		"blast" => 6,
		"blastBoost" => 1,
		"blastRange" => "short",
		"power" => 7,
		"powerBoost" => 2,
		"health" => 6,
		"hyper" => 4,
		"abilities" => array(
			"Hit and Run" => array("trigger" => "power", ),
			"Armored" => array(),
			"Berserk" => array("color" => "blue", ),
			"Flank" => array("color" => "red",),)
	),
  
	"rakadon_mega" => array(
		"name" => "Rakadon",
		"type" => "monster",
		"form" => "Mega",
		"faction" => "Terrasaurs",
		"agenda" => "Radicals",
		"energyType" => "Nature",
		"set" => "I Chomp NY",
		"setColor" => "blue",
		"rarity" => 4,
		"speed" => 6,
		"defense" => 7,
		"brawl" => 8,
		"brawlBoost" => 3,
		"blast" => 7,
		"blastBoost" => 3,
		"blastRange" => "short",
		"power" => 8,
		"powerBoost" => 2,
		"health" => 5,
		"hyper" => 4,
		"abilities" => array(
			"Beat Back" => array("trigger" => "brawl", ),
			"Following Fire" => array("trigger" => "brawl", ),
			"Munch" => array("trigger" => "brawl", ),
			"Berserk" => array("color" => "blue", ),
			"Flank" => array("color" => "red",),)
	),
  
	"terra_khan_alpha" => array(
		"name" => "Terra Khan",
		"type" => "monster",
		"form" => "Alpha",
		"faction" => "Terrasaurs",
		"agenda" => "Radicals",
		"energyType" => "Nature",
		"set" => "Rise",
		"rarity" => 3,
		"speed" => 6,
		"defense" => 6,
		"brawl" => 8,
		"brawlBoost" => 2,
		"blast" => 5,
		"blastBoost" => 1,
		"blastRange" => "long",
		"power" => 6,
		"powerBoost" => 2,
		"health" => 5,
		"hyper" => 0,
		"abilities" => array(
			"Feeding Frenzy" => array("trigger" => "brawl", ),
			"Munch" => array("trigger" => "brawl", ),
			"Berserk" => array("color" => "blue", ),
			"Flank" => array(),
			"Motivator" => array(),)
	),
  
	"terra_khan_ultra" => array(
		"name" => "Terra Khan",
		"type" => "monster",
		"form" => "Ultra",
		"faction" => "Terrasaurs",
		"agenda" => "Radicals",
		"energyType" => "Nature",
		"set" => "Rise",
		"rarity" => 3,
		"speed" => 8,
		"defense" => 5,
		"brawl" => 9,
		"brawlBoost" => 4,
		"blast" => 7,
		"blastBoost" => 2,
		"blastRange" => "short",
		"power" => 7,
		"powerBoost" => 2,
		"health" => 6,
		"hyper" => 4,
		"abilities" => array(
			"Lightning Attack" => array("trigger" => "brawl", ),
			"Disrupt" => array("trigger" => "blast", ),
			"Explosion" => array("trigger" => "blast", ),
			"Weapon Master" => array("trigger" => "power", ),)
	),
  
	"terra_khan_mega" => array(
		"name" => "Terra Khan",
		"type" => "monster",
		"form" => "Mega",
		"faction" => "Terrasaurs",
		"agenda" => "Radicals",
		"energyType" => "Nature",
		"set" => "Rise",
		"setColor" => "blue",
		"rarity" => 4,
		"speed" => 8,
		"defense" => 5,
		"brawl" => 9,
		"brawlBoost" => 2,
		"blast" => 6,
		"blastBoost" => 1,
		"blastRange" => "short",
		"power" => 8,
		"powerBoost" => 3,
		"health" => 6,
		"hyper" => 4,
		"abilities" => array(
			"Chain Attack" => array("trigger" => "brawl", ),
			"Charge" => array(),
			"Super Rampage" => array(),
			"Terrify" => array(),)
	),
  
	"tyrranix_alpha_fox_jaw-fte" => array(
		"name" => "Tyrranix",
		"type" => "monster",
		"form" => "Fox Jaw-FTE",
		"faction" => "Terrasaurs",
		"agenda" => "Radicals",
		"energyType" => "Mechanical",
		"set" => "All Your Base",
		"rarity" => 3,
		"speed" => 6,
		"defense" => 5,
		"brawl" => 3,
		"brawlBoost" => 1,
		"blast" => 2,
		"blastBoost" => 2,
		"blastRange" => "long",
		"health" => 6,
		"hyper" => 0,
		"abilities" => array(
			"Explosion" => array("trigger" => "blast", ),
			"Armor Piercing" => array("color" => "red",),
			"Jump" => array(),)
	),
  
	"tyrranix_alpha_gearjammer-bto" => array(
		"name" => "Tyrranix",
		"type" => "monster",
		"form" => "Gearjammer-BTO",
		"faction" => "Terrasaurs",
		"agenda" => "Radicals",
		"energyType" => "Mechanical",
		"set" => "All Your Base",
		"rarity" => 3,
		"speed" => 6,
		"defense" => 5,
		"brawl" => 3,
		"brawlBoost" => 1,
		"blast" => 3,
		"blastBoost" => 1,
		"blastRange" => "short",
		"health" => 6,
		"hyper" => 0,
		"abilities" => array(
			"Tow" => array(),
			"Blitz" => array("trigger" => "brawl", ),
			"Charge" => array("color" => "red",),
			"Jump" => array(),)
	),
  
	"tyrranix_alpha_gypsy_sunbeam" => array(
		"name" => "Tyrranix",
		"type" => "monster",
		"form" => "Gypsy Sunbeam",
		"faction" => "Terrasaurs",
		"agenda" => "Radicals",
		"energyType" => "Mechanical",
		"set" => "All Your Base",
		"rarity" => 3,
		"speed" => 6,
		"defense" => 5,
		"brawl" => 3,
		"brawlBoost" => 1,
		"blast" => 3,
		"blastBoost" => 1,
		"blastRange" => "short",
		"health" => 6,
		"hyper" => 0,
		"abilities" => array(
			"Multi-shot" => array("trigger" => "blast", ),
			"Indirect Fire" => array("color" => "red",),
			"Jump" => array(),
			"Terrify" => array("color" => "red",),)
	),
  
	"tyrranix_alpha_rolling_ranch" => array(
		"name" => "Tyrranix",
		"type" => "monster",
		"form" => "Rolling Ranch",
		"faction" => "Terrasaurs",
		"agenda" => "Radicals",
		"energyType" => "Mechanical",
		"set" => "All Your Base",
		"rarity" => 3,
		"speed" => 6,
		"defense" => 5,
		"brawl" => 4,
		"brawlBoost" => 1,
		"health" => 6,
		"hyper" => 0,
		"abilities" => array(
			"Summon" => array(),
			"Beat Back" => array("trigger" => "brawl", ),
			"Jump" => array(),
			"Penetrator" => array("color" => "red",),)
	),
  
	"tyrranix_ultra" => array(
		"name" => "Tyrranix",
		"type" => "monster",
		"form" => "Ultra",
		"faction" => "Terrasaurs",
		"agenda" => "Radicals",
		"energyType" => "Nature",
		"set" => "All Your Base",
		"rarity" => 3,
		"speed" => 6,
		"defense" => 6,
		"brawl" => 8,
		"brawlBoost" => 2,
		"power" => 8,
		"powerBoost" => 4,
		"health" => 6,
		"hyper" => 4,
		"abilities" => array(
			"Rage" => array("color" => "red",),
			"Crunch" => array("trigger" => "power", ),
			"Super Rampage" => array(),
			"Super Stomp" => array(),
			"Super Strength" => array(),)
	),
  
	"tyrranix_mega" => array(
		"name" => "Tyrranix",
		"type" => "monster",
		"form" => "Mega",
		"faction" => "Terrasaurs",
		"agenda" => "Radicals",
		"energyType" => "Nature",
		"set" => "All Your Base",
		"setColor" => "blue",
		"rarity" => 4,
		"speed" => 6,
		"defense" => 6,
		"brawl" => 8,
		"brawlBoost" => 3,
		"blast" => 8,
		"blastBoost" => 2,
		"blastRange" => "short",
		"power" => 8,
		"powerBoost" => 3,
		"health" => 5,
		"hyper" => 5,
		"abilities" => array(
			"Rage" => array("color" => "red",),
			"Radial Attack" => array("trigger" => "brawl", ),
			"Weapon Master" => array("trigger" => "power", ),
			"Terrify" => array(),)
	),
  
	"mt._terra" => array(
		"name" => "Mt. Terra",
		"type" => "building",
		"hazard" => "fire",
		"faction" => "Terrasaurs",
		"agenda" => "Radicals",
		"set" => "All Your Base",
		"rarity" => 3,
		"defense" => 5,
		"energy" => 5,
		"abilities" => array(
			"Beacon" => array(),
			"Discount" => array(),
			"No-Fly Zone" => array(),
			"Blazing Inferno" => array(),)
	),
  
	"bellower_grunt" => array(
		"name" => "Bellower",
		"type" => "unit",
		"class" => "Grunt",
		"faction" => "Terrasaurs",
		"agenda" => "Radicals",
		"energyType" => "Nature",
		"set" => "I Chomp NY",
		"rarity" => 2,
		"speed" => 5,
		"defense" => 3,
		"brawl" => 2,
		"blast" => 1,
		"blastBoost" => 1,
		"blastRange" => "long",
		"cost" => 1,
		"abilities" => array(
			"Extinguish" => array("color" => "red",),
			"Energy Sap" => array("trigger" => "blast", ),
			"Demolition" => array(),)
	),
  
	"bellower_elite" => array(
		"name" => "Bellower",
		"type" => "unit",
		"class" => "Elite",
		"faction" => "Terrasaurs",
		"agenda" => "Radicals",
		"energyType" => "Nature",
		"set" => "I Chomp NY",
		"rarity" => 3,
		"speed" => 5,
		"defense" => 3,
		"brawl" => 2,
		"brawlBoost" => 1,
		"blast" => 1,
		"blastBoost" => 2,
		"blastRange" => "long",
		"cost" => 2,
		"abilities" => array(
			"Extinguish" => array("color" => "red",),
			"Energy Sap" => array("trigger" => "blast", ),
			"Demolition" => array(),
			"Leadership" => array(),)
	),
  
	"brontox_grunt" => array(
		"name" => "Brontox",
		"type" => "unit",
		"class" => "Grunt",
		"faction" => "Terrasaurs",
		"agenda" => "Radicals",
		"energyType" => "Nature",
		"set" => "Rise",
		"rarity" => 3,
		"speed" => 4,
		"defense" => 4,
		"brawl" => 1,
		"cost" => 2,
		"abilities" => array(
			"Nesting" => array(),
			"Dig In" => array(),
			"Fortify" => array(),)
	),
  
	"carnidon_grunt" => array(
		"name" => "Carnidon",
		"type" => "unit",
		"class" => "Grunt",
		"faction" => "Terrasaurs",
		"agenda" => "Radicals",
		"energyType" => "Nature",
		"set" => "Rise",
		"rarity" => 1,
		"speed" => 4,
		"defense" => 3,
		"brawl" => 2,
		"brawlBoost" => 1,
		"cost" => 1,
		"abilities" => array()
	),
  
	"carnidon_elite" => array(
		"name" => "Carnidon",
		"type" => "unit",
		"class" => "Elite",
		"faction" => "Terrasaurs",
		"agenda" => "Radicals",
		"energyType" => "Nature",
		"set" => "Rise",
		"rarity" => 3,
		"speed" => 4,
		"defense" => 3,
		"brawl" => 2,
		"brawlBoost" => 2,
		"cost" => 2,
		"abilities" => array(
			"Leadership" => array(),)
	),
  
	"green_fury_van_grunt" => array(
		"name" => "Green Fury Van",
		"type" => "unit",
		"class" => "Grunt",
		"faction" => "Terrasaurs",
		"agenda" => "Radicals",
		"energyType" => "Mechanical",
		"set" => "All Your Base",
		"rarity" => 1,
		"speed" => 5,
		"defense" => 2,
		"brawl" => 1,
		"blast" => 2,
		"blastRange" => "long",
		"cost" => 1,
		"abilities" => array(
			"Munch" => array("color" => "red","trigger" => "brawl", ),
			"Chain Reaction" => array("trigger" => "blast", ),)
	),
  
	"green_fury_van_elite" => array(
		"name" => "Green Fury Van",
		"type" => "unit",
		"class" => "Elite",
		"faction" => "Terrasaurs",
		"agenda" => "Radicals",
		"energyType" => "Mechanical",
		"set" => "All Your Base",
		"rarity" => 2,
		"speed" => 5,
		"defense" => 2,
		"brawl" => 1,
		"brawlBoost" => 1,
		"blast" => 2,
		"blastBoost" => 1,
		"blastRange" => "long",
		"cost" => 2,
		"abilities" => array(
			"Munch" => array("color" => "red","trigger" => "brawl", ),
			"Chain Reaction" => array("trigger" => "blast", ),
			"Leadership" => array(),)
	),
  
	"green_fury_van_shadow" => array(
		"name" => "Green Fury Van",
		"type" => "unit",
		"form" => "Shadow",
		"class" => "Elite",
		"faction" => "Terrasaurs",
		"agenda" => "Radicals",
		"energyType" => "Mechanical",
		"set" => "All Your Base",
		"setColor" => "blue",
		"rarity" => 4,
		"speed" => 5,
		"defense" => 2,
		"brawl" => 1,
		"brawlBoost" => 1,
		"blast" => 2,
		"blastBoost" => 1,
		"blastRange" => "long",
		"cost" => 3,
		"abilities" => array(
			"Munch" => array("color" => "red","trigger" => "brawl", ),
			"Chain Reaction" => array("trigger" => "blast", ),
			"Cloak" => array(),
			"Leadership" => array(),)
	),
  
	"pteradactix_grunt" => array(
		"name" => "Pteradactix",
		"type" => "unit",
		"class" => "Grunt",
		"faction" => "Terrasaurs",
		"agenda" => "Radicals",
		"energyType" => "Nature",
		"set" => "I Chomp NY",
		"rarity" => 1,
		"speed" => 6,
		"defense" => 3,
		"brawl" => 3,
		"cost" => 1,
		"abilities" => array(
			"Tow" => array(),
			"Flight" => array(),)
	),
  
	"pteradactix_elite" => array(
		"name" => "Pteradactix",
		"type" => "unit",
		"class" => "Elite",
		"faction" => "Terrasaurs",
		"agenda" => "Radicals",
		"energyType" => "Nature",
		"set" => "I Chomp NY",
		"rarity" => 2,
		"speed" => 6,
		"defense" => 3,
		"brawl" => 3,
		"brawlBoost" => 1,
		"cost" => 2,
		"abilities" => array(
			"Tow" => array(),
			"Flight" => array(),
			"Leadership" => array(),
			"Riled" => array("color" => "red",),)
	),
  
	"pteradactix_shadow" => array(
		"name" => "Pteradactix",
		"type" => "unit",
		"form" => "Shadow",
		"class" => "Grunt",
		"faction" => "Terrasaurs",
		"agenda" => "Radicals",
		"energyType" => "Nature",
		"set" => "I Chomp NY",
		"setColor" => "blue",
		"rarity" => 4,
		"speed" => 6,
		"defense" => 3,
		"brawl" => 3,
		"cost" => 2,
		"abilities" => array(
			"Tow" => array(),
			"Cloak" => array(),
			"Flight" => array(),)
	),
  
	"raptix_grunt" => array(
		"name" => "Raptix",
		"type" => "unit",
		"class" => "Grunt",
		"faction" => "Terrasaurs",
		"agenda" => "Radicals",
		"energyType" => "Nature",
		"set" => "Rise",
		"rarity" => 1,
		"speed" => 5,
		"defense" => 3,
		"brawl" => 1,
		"cost" => 1,
		"abilities" => array(
			"Anti-air" => array(),
			"Flank" => array(),
			"Jump" => array(),)
	),
  
	"raptix_elite" => array(
		"name" => "Raptix",
		"type" => "unit",
		"class" => "Elite",
		"faction" => "Terrasaurs",
		"agenda" => "Radicals",
		"energyType" => "Nature",
		"set" => "Rise",
		"rarity" => 2,
		"speed" => 5,
		"defense" => 3,
		"brawl" => 1,
		"brawlBoost" => 1,
		"cost" => 2,
		"abilities" => array(
			"Anti-air" => array(),
			"Flank" => array(),
			"Jump" => array(),
			"Leadership" => array(),)
	),
  
	"spikasaur_grunt" => array(
		"name" => "Spikasaur",
		"type" => "unit",
		"class" => "Grunt",
		"faction" => "Terrasaurs",
		"agenda" => "Radicals",
		"energyType" => "Nature",
		"set" => "All Your Base",
		"rarity" => 3,
		"speed" => 4,
		"defense" => 4,
		"brawl" => 1,
		"cost" => 1,
		"abilities" => array(
			"Hazardous" => array(),)
	),
  
	"spikodon_elite" => array(
		"name" => "Spikodon",
		"type" => "unit",
		"class" => "Elite",
		"faction" => "Terrasaurs",
		"agenda" => "Radicals",
		"energyType" => "Nature",
		"set" => "Rise",
		"rarity" => 2,
		"speed" => 4,
		"defense" => 3,
		"brawl" => 1,
		"blast" => 2,
		"blastBoost" => 2,
		"blastRange" => "long",
		"cost" => 2,
		"abilities" => array(
			"Explosion" => array("trigger" => "blast", ),)
	),

	"spikodon_shadow" => array(
		"name" => "Spikodon",
		"type" => "unit",
		"form" => "Shadow",
		"class" => "Elite",
		"faction" => "Terrasaurs",
		"agenda" => "Radicals",
		"energyType" => "Nature",
		"set" => "Rise",
		"setColor" => "blue",
		"rarity" => 5,
		"speed" => 4,
		"defense" => 3,
		"brawl" => 1,
		"blast" => 2,
		"blastBoost" => 2,
		"blastRange" => "long",
		"cost" => 3,
		"abilities" => array(
			"Explosion" => array("trigger" => "blast", ),
			"Cloak" => array(),)
	),
  
