


/*    =============    Tritons    =============    */

	"anglax_alpha" => array(
		"name" => "Anglax",
		"type" => "monster",
		"form" => "Alpha",
		"faction" => "Tritons",
		"agenda" => "Invaders",
		"energyType" => "Nature",
		"set" => "Now",
		"rarity" => 3,
		"speed" => 7,
		"defense" => 6,
		"brawl" => 7,
		"brawlBoost" => 2,
		"blast" => 5,
		"blastBoost" => 1,
		"blastRange" => "short",
		"power" => 7,
		"powerBoost" => 3,
		"health" => 5,
		"hyper" => 0,
		"abilities" => array(
			"Command" => array(),
			"Leach" => array(),
			"Jam" => array(),
			"Super Rampage" => array(),)
	),
  
	"anglax_ultra" => array(
		"name" => "Anglax",
		"type" => "monster",
		"form" => "Ultra",
		"faction" => "Tritons",
		"agenda" => "Invaders",
		"energyType" => "Nature",
		"set" => "Now",
		"rarity" => 3,
		"speed" => 6,
		"defense" => 6,
		"brawl" => 8,
		"brawlBoost" => 3,
		"blast" => 6,
		"blastBoost" => 2,
		"blastRange" => "short",
		"power" => 8,
		"powerBoost" => 4,
		"health" => 5,
		"hyper" => 4,
		"abilities" => array(
			"Command" => array(),
			"Leach" => array(),
			"High Impact" => array("color" => "blue", ),
			"Jam" => array(),
			"Weaken" => array(),)
	),
  
	"anglax_mega" => array(
		"name" => "Anglax",
		"type" => "monster",
		"form" => "Mega",
		"faction" => "Tritons",
		"agenda" => "Invaders",
		"energyType" => "Nature",
		"set" => "Now",
		"setColor" => "blue",
		"rarity" => 4,
		"speed" => 6,
		"defense" => 6,
		"brawl" => 6,
		"brawlBoost" => 2,
		"blast" => 8,
		"blastBoost" => 3,
		"blastRange" => "short",
		"power" => 7,
		"powerBoost" => 3,
		"health" => 5,
		"hyper" => 4,
		"abilities" => array(
			"Multi-shot" => array("trigger" => "blast", ),
			"Siphon" => array("trigger" => "blast", ),
			"Vampirism" => array("trigger" => "blast", ),
			"Distract" => array(),
			"Jam" => array(),
			"Weaken" => array(),)
	),
  
	"crustaceor_alpha" => array(
		"name" => "Crustaceor",
		"type" => "monster",
		"form" => "Alpha",
		"faction" => "Tritons",
		"agenda" => "Invaders",
		"energyType" => "Nature",
		"set" => "Big in Japan",
		"rarity" => 3,
		"speed" => 5,
		"defense" => 5,
		"brawl" => 7,
		"brawlBoost" => 2,
		"blast" => 5,
		"blastBoost" => 2,
		"blastRange" => "short",
		"power" => 5,
		"powerBoost" => 1,
		"health" => 5,
		"hyper" => 0,
		"abilities" => array(
			"Hoist" => array(),
			"Crunch" => array("trigger" => "brawl", ),
			"Demolish" => array("trigger" => "brawl", ),
			"Reach" => array(),)
	),
  
	"crustaceor_ultra" => array(
		"name" => "Crustaceor",
		"type" => "monster",
		"form" => "Ultra",
		"faction" => "Tritons",
		"agenda" => "Invaders",
		"energyType" => "Nature",
		"set" => "Big in Japan",
		"rarity" => 3,
		"speed" => 6,
		"defense" => 5,
		"brawl" => 8,
		"brawlBoost" => 3,
		"blast" => 6,
		"blastBoost" => 3,
		"blastRange" => "short",
		"power" => 6,
		"powerBoost" => 2,
		"health" => 6,
		"hyper" => 3,
		"abilities" => array(
			"Crunch" => array("trigger" => "brawl", ),
			"Power Strike" => array("trigger" => "brawl", ),
			"Jump" => array(),
			"Reach" => array(),)
	),
  
	"crustaceor_mega" => array(
		"name" => "Crustaceor",
		"type" => "monster",
		"form" => "Mega",
		"faction" => "Tritons",
		"agenda" => "Invaders",
		"energyType" => "Nature",
		"set" => "Big in Japan",
		"setColor" => "blue",
		"rarity" => 4,
		"speed" => 7,
		"defense" => 5,
		"brawl" => 7,
		"brawlBoost" => 3,
		"blast" => 7,
		"blastBoost" => 2,
		"blastRange" => "short",
		"power" => 6,
		"powerBoost" => 3,
		"health" => 5,
		"hyper" => 5,
		"abilities" => array(
			"Hoist" => array(),
			"Crunch" => array("trigger" => "power", ),
			"Hit and Run" => array("trigger" => "power", ),
			"Synchronized Move" => array("trigger" => "power", ),
			"Reach" => array(),)
	),
  
	"krakenoctus_alpha" => array(
		"name" => "Krakenoctus",
		"type" => "monster",
		"form" => "Alpha",
		"faction" => "Tritons",
		"agenda" => "Invaders",
		"energyType" => "Nature",
		"set" => "Now",
		"rarity" => 3,
		"speed" => 5,
		"defense" => 6,
		"brawl" => 7,
		"brawlBoost" => 2,
		"blast" => 8,
		"blastBoost" => 3,
		"blastRange" => "long",
		"power" => 6,
		"powerBoost" => 1,
		"health" => 6,
		"hyper" => 0,
		"abilities" => array(
			"Tow" => array(),
			"Munch" => array("trigger" => "blast", ),
			"Reach" => array(),
			"Riled" => array(),)
	),
  
	"krakenoctus_ultra" => array(
		"name" => "Krakenoctus",
		"type" => "monster",
		"form" => "Ultra",
		"faction" => "Tritons",
		"agenda" => "Invaders",
		"energyType" => "Nature",
		"set" => "Now",
		"rarity" => 3,
		"speed" => 6,
		"defense" => 5,
		"brawl" => 9,
		"brawlBoost" => 4,
		"blast" => 6,
		"blastBoost" => 3,
		"blastRange" => "short",
		"power" => 7,
		"powerBoost" => 2,
		"health" => 5,
		"hyper" => 4,
		"abilities" => array(
			"Tow" => array(),
			"Fling" => array("trigger" => "brawl", ),
			"Following Fire" => array("trigger" => "brawl", ),
			"Munch" => array("trigger" => "brawl", ),
			"Reach" => array(),)
	),
  
	"krakenoctus_mega" => array(
		"name" => "Krakenoctus",
		"type" => "monster",
		"form" => "Mega",
		"faction" => "Tritons",
		"agenda" => "Invaders",
		"energyType" => "Nature",
		"set" => "Now",
		"setColor" => "blue",
		"rarity" => 4,
		"speed" => 5,
		"defense" => 5,
		"brawl" => 7,
		"brawlBoost" => 2,
		"blast" => 9,
		"blastBoost" => 4,
		"blastRange" => "long",
		"power" => 7,
		"powerBoost" => 2,
		"health" => 6,
		"hyper" => 4,
		"abilities" => array(
			"Fling" => array("trigger" => "blast", ),
			"Negation" => array(),
			"Reach" => array(),
			"Super Swat" => array(),)
	),
  
	"leviathron_alpha" => array(
		"name" => "Leviathron",
		"type" => "monster",
		"form" => "Alpha",
		"faction" => "Tritons",
		"agenda" => "Invaders",
		"energyType" => "Nature",
		"set" => "Big in Japan",
		"rarity" => 3,
		"speed" => 7,
		"defense" => 5,
		"brawl" => 6,
		"brawlBoost" => 1,
		"blast" => 7,
		"blastBoost" => 2,
		"blastRange" => "short",
		"power" => 7,
		"powerBoost" => 2,
		"health" => 5,
		"hyper" => 0,
		"abilities" => array(
			"Pathfinder_short" => array(),
			"Power Cycle" => array(),
			"Radial Attack_short" => array("trigger" => "brawl", ),
			"Power Drain" => array("trigger" => "power", ),
			"Armored" => array(),)
	),
  
	"leviathron_ultra" => array(
		"name" => "Leviathron",
		"type" => "monster",
		"form" => "Ultra",
		"faction" => "Tritons",
		"agenda" => "Invaders",
		"energyType" => "Nature",
		"set" => "Big in Japan",
		"rarity" => 3,
		"speed" => 7,
		"defense" => 5,
		"brawl" => 6,
		"brawlBoost" => 2,
		"blast" => 8,
		"blastBoost" => 3,
		"blastRange" => "long",
		"power" => 9,
		"powerBoost" => 3,
		"health" => 5,
		"hyper" => 4,
		"abilities" => array(
			"Pathfinder_short" => array(),
			"Power Drain" => array("trigger" => "power", ),
			"Radial Attack_short" => array("trigger" => "power", ),
			"Armored" => array(),
			"Hasten" => array("color" => "blue", ),
			"Super Strength" => array(),)
	),
  
	"leviathron_mega" => array(
		"name" => "Leviathron",
		"type" => "monster",
		"form" => "Mega",
		"faction" => "Tritons",
		"agenda" => "Invaders",
		"energyType" => "Nature",
		"set" => "Big in Japan",
		"setColor" => "blue",
		"rarity" => 4,
		"speed" => 8,
		"defense" => 5,
		"brawl" => 6,
		"brawlBoost" => 2,
		"blast" => 9,
		"blastBoost" => 3,
		"blastRange" => "long",
		"power" => 8,
		"powerBoost" => 3,
		"health" => 5,
		"hyper" => 4,
		"abilities" => array(
			"Ignite_short" => array(),
			"Pathfinder_short" => array(),
			"Radial Attack_short" => array("trigger" => "blast", ),
			"Armored" => array(),
			"Shelter" => array("color" => "red",),
			"Riled" => array(),)
	),
  
	"hunter_kor'al" => array(
		"name" => "Hunter Kor'al",
		"type" => "character",
		"form" => "Maco Hunter Sub",
		"class" => "Elite",
		"faction" => "Tritons",
		"agenda" => "Invaders",
		"energyType" => "Mechanical",
		"set" => "Big in Japan",
		"rarity" => 4,
		"speed" => 4,
		"defense" => 4,
		"brawl" => 2,
		"brawlBoost" => 1,
		"blast" => 1,
		"blastBoost" => 2,
		"blastRange" => "short",
		"cost" => 2,
		"abilities" => array(
			"Power Gorge" => array("trigger" => "blast", ),
			"Amphibious" => array(),
			"Limited" => array(),
			"Radar" => array("color" => "red",),)
	),
  
	"maco_hunter_sub_grunt" => array(
		"name" => "Maco Hunter Sub",
		"type" => "unit",
		"class" => "Grunt",
		"faction" => "Tritons",
		"agenda" => "Invaders",
		"energyType" => "Mechanical",
		"set" => "Big in Japan",
		"rarity" => 1,
		"speed" => 4,
		"defense" => 4,
		"brawl" => 2,
		"blast" => 1,
		"blastBoost" => 1,
		"blastRange" => "short",
		"cost" => 1,
		"abilities" => array(
			"Disrupt" => array("trigger" => "blast", ),
			"Energy Sap" => array("trigger" => "blast", ),
			"Amphibious" => array(),)
	),
  
	"maco_hunter_sub_elite" => array(
		"name" => "Maco Hunter Sub",
		"type" => "unit",
		"class" => "Elite",
		"faction" => "Tritons",
		"agenda" => "Invaders",
		"energyType" => "Mechanical",
		"set" => "Big in Japan",
		"rarity" => 2,
		"speed" => 4,
		"defense" => 4,
		"brawl" => 2,
		"brawlBoost" => 1,
		"blast" => 1,
		"blastBoost" => 2,
		"blastRange" => "short",
		"cost" => 2,
		"abilities" => array(
			"Disrupt" => array("trigger" => "blast", ),
			"Energy Sap" => array("trigger" => "blast", ),
			"Amphibious" => array(),
			"Leadership" => array(),)
	),
  
	"nautilus_blaster_grunt" => array(
		"name" => "Nautilus Blaster",
		"type" => "unit",
		"class" => "Grunt",
		"faction" => "Tritons",
		"agenda" => "Invaders",
		"energyType" => "Mechanical",
		"set" => "Now",
		"rarity" => 2,
		"speed" => 3,
		"defense" => 2,
		"blast" => 1,
		"blastBoost" => 1,
		"blastRange" => "long",
		"cost" => 1,
		"abilities" => array(
			"Power Gorge" => array("color" => "red","trigger" => "blast", ),
			"Amphibious" => array(),
			"Armor Piercing" => array(),)
	),
  
	"psi-eel_grunt" => array(
		"name" => "Psi-Eel",
		"type" => "unit",
		"class" => "Grunt",
		"faction" => "Tritons",
		"agenda" => "Invaders",
		"energyType" => "Nature",
		"set" => "Big in Japan",
		"rarity" => 1,
		"speed" => 6,
		"defense" => 2,
		"brawl" => 2,
		"brawlBoost" => 1,
		"cost" => 1,
		"abilities" => array(
			"Amphibious" => array(),
			"Hazardous" => array(),
			"Unstable" => array(),)
	),
  
	"psi-eel_elite" => array(
		"name" => "Psi-Eel",
		"type" => "unit",
		"class" => "Elite",
		"faction" => "Tritons",
		"agenda" => "Invaders",
		"energyType" => "Nature",
		"set" => "Big in Japan",
		"rarity" => 3,
		"speed" => 6,
		"defense" => 2,
		"brawl" => 2,
		"brawlBoost" => 2,
		"cost" => 2,
		"abilities" => array(
			"Amphibious" => array(),
			"Hazardous" => array(),
			"Leadership" => array(),
			"Unstable" => array(),)
	),
  
	"psi-eel_glass" => array(
		"name" => "Psi-Eel",
		"type" => "unit",
		"form" => "Glass",
		"class" => "Grunt",
		"faction" => "Tritons",
		"agenda" => "Invaders",
		"energyType" => "Nature",
		"set" => "Big in Japan",
		"setColor" => "blue",
		"rarity" => 4,
		"speed" => 6,
		"defense" => 2,
		"brawl" => 2,
		"brawlBoost" => 1,
		"cost" => 1,
		"abilities" => array(
			"Radial Attack" => array("trigger" => "brawl", ),
			"Amphibious" => array(),
			"Fragile" => array(),
			"Hazardous" => array(),)
	),
  
	"spadefin_skimmer_grunt" => array(
		"name" => "Spadefin Skimmer",
		"type" => "unit",
		"class" => "Grunt",
		"faction" => "Tritons",
		"agenda" => "Invaders",
		"energyType" => "Mechanical",
		"set" => "Now",
		"rarity" => 1,
		"speed" => 5,
		"defense" => 3,
		"blast" => 1,
		"blastRange" => "short",
		"cost" => 1,
		"abilities" => array(
			"Extinguish" => array(),
			"Tow" => array(),
			"Hover" => array(),)
	),
  
	"spadefin_skimmer_elite" => array(
		"name" => "Spadefin Skimmer",
		"type" => "unit",
		"class" => "Elite",
		"faction" => "Tritons",
		"agenda" => "Invaders",
		"energyType" => "Mechanical",
		"set" => "Now",
		"rarity" => 3,
		"speed" => 5,
		"defense" => 3,
		"blast" => 1,
		"blastBoost" => 1,
		"blastRange" => "short",
		"cost" => 2,
		"abilities" => array(
			"Extinguish" => array(),
			"Tow" => array(),
			"Hover" => array(),
			"Leadership" => array(),)
	),
  
	"spiral_relay_grunt" => array(
		"name" => "Spiral Relay",
		"type" => "unit",
		"class" => "Grunt",
		"faction" => "Tritons",
		"agenda" => "Invaders",
		"energyType" => "Mechanical",
		"set" => "Now",
		"rarity" => 2,
		"speed" => 6,
		"defense" => 4,
		"cost" => 1,
		"abilities" => array(
			"Sprint" => array("color" => "red",),
			"Synchronized Move" => array("color" => "red","trigger" => "blast", ),
			"Hover" => array(),)
	),
  
	"spiral_relay_glass" => array(
		"name" => "Spiral Relay",
		"type" => "unit",
		"form" => "Glass",
		"class" => "Grunt",
		"faction" => "Tritons",
		"agenda" => "Invaders",
		"energyType" => "Mechanical",
		"set" => "Now",
		"setColor" => "blue",
		"rarity" => 4,
		"speed" => 6,
		"defense" => 4,
		"blast" => 1,
		"blastBoost" => 1,
		"blastRange" => "long",
		"cost" => 1,
		"abilities" => array(
			"Sprint" => array("color" => "red",),
			"Synchronized Move" => array("color" => "red","trigger" => "blast", ),
			"Hover" => array(),
			"Fragile" => array(),)
	),
  
	"steel_shell_crab_grunt" => array(
		"name" => "Steel Shell Crab",
		"type" => "unit",
		"class" => "Grunt",
		"faction" => "Tritons",
		"agenda" => "Invaders",
		"energyType" => "Nature",
		"set" => "Now",
		"rarity" => 1,
		"speed" => 4,
		"defense" => 4,
		"brawl" => 3,
		"brawlBoost" => 1,
		"cost" => 1,
		"abilities" => array(
			"Burrow" => array(),
			"Dig In" => array(),
			"Reach" => array(),)
	),
  
	"steel_shell_crab_elite" => array(
		"name" => "Steel Shell Crab",
		"type" => "unit",
		"class" => "Elite",
		"faction" => "Tritons",
		"agenda" => "Invaders",
		"energyType" => "Nature",
		"set" => "Now",
		"rarity" => 3,
		"speed" => 4,
		"defense" => 4,
		"brawl" => 3,
		"brawlBoost" => 2,
		"cost" => 1,
		"abilities" => array(
			"Burrow" => array(),
			"Dig In" => array(),
			"Leadership" => array(),
			"Reach" => array(),)
	),
