


/*    =============    Ubercorp International    =============    */

	"cyber_khan_alpha" => array(
		"name" => "Cyber Khan",
		"type" => "monster",
		"form" => "Alpha",
		"faction" => "UberCorp International",
		"agenda" => "Collaborators",
		"energyType" => "Mechanical",
		"set" => "Now",
		"rarity" => 3,
		"speed" => 6,
		"defense" => 6,
		"brawl" => 8,
		"brawlBoost" => 2,
		"blast" => 5,
		"blastBoost" => 1,
		"blastRange" => "long",
		"power" => 6,
		"powerBoost" => 2,
		"health" => 5,
		"hyper" => 0,
		"abilities" => array(
			"Refuel" => array(),
			"Following Fire" => array("trigger" => "brawl", ),
			"Flight" => array(),
			"High Impact" => array("color" => "blue", ),
			"Spotter" => array(),)
	),
  
	"cyber_khan_ultra" => array(
		"name" => "Cyber Khan",
		"type" => "monster",
		"form" => "Ultra",
		"faction" => "UberCorp International",
		"agenda" => "Collaborators",
		"energyType" => "Mechanical",
		"set" => "Now",
		"rarity" => 3,
		"speed" => 8,
		"defense" => 6,
		"brawl" => 9,
		"brawlBoost" => 4,
		"blast" => 7,
		"blastBoost" => 2,
		"blastRange" => "short",
		"power" => 6,
		"powerBoost" => 2,
		"health" => 5,
		"hyper" => 4,
		"abilities" => array(
			"Disrupt" => array("trigger" => "blast", ),
			"Multi-shot" => array("trigger" => "blast", ),
			"Follow Through" => array("trigger" => "power", ),
			"Flight_short" => array(),
			"Super Smash" => array(),)
	),
  
	"cyber_khan_mega" => array(
		"name" => "Cyber Khan",
		"type" => "monster",
		"form" => "Mega",
		"faction" => "UberCorp International",
		"agenda" => "Collaborators",
		"energyType" => "Mechanical",
		"set" => "Now",
		"setColor" => "blue",
		"rarity" => 4,
		"speed" => 8,
		"defense" => 5,
		"brawl" => 9,
		"brawlBoost" => 2,
		"blast" => 6,
		"blastBoost" => 1,
		"blastRange" => "short",
		"power" => 8,
		"powerBoost" => 3,
		"health" => 6,
		"hyper" => 4,
		"abilities" => array(
			"Follow Through" => array("trigger" => "brawl", ),
			"Power Gorge" => array("trigger" => "brawl", ),
			"Jump" => array(),
			"Martial Artist" => array(),
			"Super Stomp" => array(),)
	),
  
	"gorghadratron_alpha" => array(
		"name" => "Gorghadratron",
		"type" => "monster",
		"form" => "Alpha",
		"faction" => "UberCorp International",
		"agenda" => "Collaborators",
		"energyType" => "Mechanical",
		"set" => "Now",
		"rarity" => 3,
		"speed" => 6,
		"defense" => 5,
		"brawl" => 8,
		"brawlBoost" => 2,
		"blast" => 6,
		"blastBoost" => 2,
		"blastRange" => "short",
		"power" => 6,
		"powerBoost" => 2,
		"health" => 7,
		"hyper" => 0,
		"abilities" => array(
			"Power Drain" => array("color" => "blue", "trigger" => "brawl", ),
			"Chain Reaction" => array("trigger" => "blast", ),
			"Power Drain " => array("color" => "blue", "trigger" => "blast", ),
			"Drain Life" => array("color" => "blue", ),
			"Power Sink" => array(),)
	),
  
	"gorghadratron_ultra" => array(
		"name" => "Gorghadratron",
		"type" => "monster",
		"form" => "Ultra",
		"faction" => "UberCorp International",
		"agenda" => "Collaborators",
		"energyType" => "Mechanical",
		"set" => "Now",
		"rarity" => 3,
		"speed" => 6,
		"defense" => 7,
		"brawl" => 9,
		"brawlBoost" => 3,
		"blast" => 5,
		"blastBoost" => 3,
		"blastRange" => "short",
		"power" => 8,
		"powerBoost" => 3,
		"health" => 5,
		"hyper" => 4,
		"abilities" => array(
			"Multi-shot" => array("trigger" => "blast", ),
			"Power Strike" => array("trigger" => "blast", ),
			"Weapon Master" => array("trigger" => "blast", ),
			"Cloak" => array(),
			"Power Sink" => array(),)
	),
  
	"gorghadratron_mega" => array(
		"name" => "Gorghadratron",
		"type" => "monster",
		"form" => "Mega",
		"faction" => "UberCorp International",
		"agenda" => "Collaborators",
		"energyType" => "Mechanical",
		"set" => "Now",
		"setColor" => "blue",
		"rarity" => 4,
		"speed" => 5,
		"defense" => 7,
		"brawl" => 7,
		"brawlBoost" => 2,
		"blast" => 7,
		"blastBoost" => 4,
		"blastRange" => "long",
		"power" => 6,
		"powerBoost" => 2,
		"health" => 6,
		"hyper" => 4,
		"abilities" => array(
			"Fission" => array(),
			"Rage" => array(),
			"Explosion" => array("trigger" => "blast", ),
			"Armor Piercing" => array(),
			"Hasten" => array("color" => "blue", ),)
	),

	"mechathugrosh_alpha" => array(
		"name" => "Mechathugrosh",
		"type" => "monster",
		"form" => "Alpha",
		"faction" => "UberCorp International",
		"agenda" => "Collaborators",
		"energyType" => "Mechanical",
		"set" => "Big in Japan",
		"rarity" => 3,
		"speed" => 6,
		"defense" => 5,
		"brawl" => 7,
		"brawlBoost" => 2,
		"blast" => 5,
		"blastBoost" => 1,
		"blastRange" => "short",
		"power" => 6,
		"powerBoost" => 2,
		"health" => 6,
		"hyper" => 0,
		"abilities" => array(
			"Restoration" => array(),
			"Tow" => array(),
			"Transport" => array(),
			"Flight_short" => array(),
			"Motivator" => array(),
			"Super Swat" => array(),)
	),
  
	"mechathugrosh_ultra" => array(
		"name" => "Mechathugrosh",
		"type" => "monster",
		"form" => "Ultra",
		"faction" => "UberCorp International",
		"agenda" => "Collaborators",
		"energyType" => "Mechanical",
		"set" => "Big in Japan",
		"rarity" => 3,
		"speed" => 7,
		"defense" => 6,
		"brawl" => 8,
		"brawlBoost" => 3,
		"blast" => 5,
		"blastBoost" => 2,
		"blastRange" => "short",
		"power" => 7,
		"powerBoost" => 2,
		"health" => 5,
		"hyper" => 4,
		"abilities" => array(
			"Tow" => array(),
			"Transport" => array(),
			"Weapon Master" => array("trigger" => "brawl", ),
			"Burrow" => array(),
			"Halt" => array(),
			"Motivator" => array(),)
	),
  
	"mechathugrosh_mega" => array(
		"name" => "Mechathugrosh",
		"type" => "monster",
		"form" => "Mega",
		"faction" => "UberCorp International",
		"agenda" => "Collaborators",
		"energyType" => "Mechanical",
		"set" => "Big in Japan",
		"setColor" => "blue",
		"rarity" => 4,
		"speed" => 7,
		"defense" => 6,
		"brawl" => 7,
		"brawlBoost" => 1,
		"blast" => 6,
		"blastBoost" => 3,
		"blastRange" => "long",
		"power" => 6,
		"powerBoost" => 2,
		"health" => 5,
		"hyper" => 4,
		"abilities" => array(
			"Rage" => array(),
			"Crunch" => array("trigger" => "blast", ),
			"Halt" => array(),
			"Jump" => array(),
			"Riled" => array(),)
	),
  
	"robo_kondo_alpha" => array(
		"name" => "Robo Kondo",
		"type" => "monster",
		"form" => "Alpha",
		"faction" => "UberCorp International",
		"agenda" => "Collaborators",
		"energyType" => "Mechanical",
		"set" => "Big in Japan",
		"rarity" => 3,
		"speed" => 6,
		"defense" => 5,
		"brawl" => 7,
		"brawlBoost" => 2,
		"blast" => 5,
		"blastBoost" => 1,
		"blastRange" => "short",
		"power" => 6,
		"powerBoost" => 2,
		"health" => 6,
		"hyper" => 0,
		"abilities" => array(
			"Hit and Run" => array("trigger" => "brawl", ),
			"Synchronized Move" => array("trigger" => "brawl", ),
			"Flight" => array(),
			"High Impact" => array("color" => "blue", ),)
	),
  
	"robo_kondo_ultra" => array(
		"name" => "Robo Kondo",
		"type" => "monster",
		"form" => "Ultra",
		"faction" => "UberCorp International",
		"agenda" => "Collaborators",
		"energyType" => "Mechanical",
		"set" => "Big in Japan",
		"rarity" => 3,
		"speed" => 6,
		"defense" => 5,
		"brawl" => 8,
		"brawlBoost" => 3,
		"blast" => 5,
		"blastBoost" => 1,
		"blastRange" => "short",
		"power" => 8,
		"powerBoost" => 3,
		"health" => 6,
		"hyper" => 4,
		"abilities" => array(
			"Chain Attack" => array("trigger" => "brawl", ),
			"Explosion" => array("color" => "red","trigger" => "blast", ),
			"Hit and Run" => array("trigger" => "power", ),
			"Flight" => array(),
			"Super Strength" => array(),)
	),
  
	"robo_kondo_mega" => array(
		"name" => "Robo Kondo",
		"type" => "monster",
		"form" => "Mega",
		"faction" => "UberCorp International",
		"agenda" => "Collaborators",
		"energyType" => "Mechanical",
		"set" => "Big in Japan",
		"setColor" => "blue",
		"rarity" => 4,
		"speed" => 7,
		"defense" => 5,
		"brawl" => 7,
		"brawlBoost" => 2,
		"blast" => 5,
		"blastBoost" => 1,
		"blastRange" => "short",
		"power" => 9,
		"powerBoost" => 4,
		"health" => 6,
		"hyper" => 4,
		"abilities" => array(
			"Power Cycle" => array(),
			"Follow Through" => array("trigger" => "power", ),
			"Flight" => array(),
			"Power Sink" => array(),)
	),
  
	"s1_robo_brontox" => array(
		"name" => "S1 Robo Brontox",
		"type" => "character",
		"form" => "Robo Brontox",
		"class" => "Elite",
		"faction" => "UberCorp International",
		"agenda" => "Collaborators",
		"energyType" => "Mechanical",
		"set" => "Big in Japan",
		"rarity" => 4,
		"speed" => 4,
		"defense" => 4,
		"blast" => 2,
		"blastBoost" => 2,
		"blastRange" => "long",
		"cost" => 2,
		"abilities" => array(
			"Amplify" => array(),
			"Intensify" => array(),
			"Limited" => array(),
			"Satellite Support" => array(),)
	),
	  
	"carnitron_grunt" => array(
		"name" => "Carnitron",
		"type" => "unit",
		"class" => "Grunt",
		"faction" => "UberCorp International",
		"agenda" => "Collaborators",
		"energyType" => "Mechanical",
		"set" => "Now",
		"rarity" => 1,
		"speed" => 5,
		"defense" => 3,
		"brawl" => 2,
		"brawlBoost" => 1,
		"blast" => 1,
		"blastRange" => "short",
		"cost" => 1,
		"abilities" => array(
			"Chain Reaction" => array("trigger" => "brawl", ),)
	),
  
	"carnitron_elite" => array(
		"name" => "Carnitron",
		"type" => "unit",
		"class" => "Elite",
		"faction" => "UberCorp International",
		"agenda" => "Collaborators",
		"energyType" => "Mechanical",
		"set" => "Now",
		"rarity" => 3,
		"speed" => 5,
		"defense" => 3,
		"brawl" => 2,
		"brawlBoost" => 2,
		"blast" => 1,
		"blastBoost" => 1,
		"blastRange" => "short",
		"cost" => 2,
		"abilities" => array(
			"Chain Reaction" => array("trigger" => "brawl", ),
			"Leadership" => array(),)
	),
  
	"mecha_chomper_grunt" => array(
		"name" => "Mecha Chomper",
		"type" => "unit",
		"class" => "Grunt",
		"faction" => "UberCorp International",
		"agenda" => "Collaborators",
		"energyType" => "Mechanical",
		"set" => "Big in Japan",
		"rarity" => 1,
		"speed" => 5,
		"defense" => 3,
		"brawl" => 2,
		"brawlBoost" => 1,
		"blast" => 1,
		"blastRange" => "short",
		"cost" => 1,
		"abilities" => array(
			"Gang" => array(),
			"Radar" => array("color" => "red",),)
	),
  
	"mecha_chomper_elite" => array(
		"name" => "Mecha Chomper",
		"type" => "unit",
		"class" => "Elite",
		"faction" => "UberCorp International",
		"agenda" => "Collaborators",
		"energyType" => "Mechanical",
		"set" => "Big in Japan",
		"rarity" => 2,
		"speed" => 5,
		"defense" => 3,
		"brawl" => 2,
		"brawlBoost" => 2,
		"blast" => 1,
		"blastBoost" => 1,
		"blastRange" => "short",
		"cost" => 2,
		"abilities" => array(
			"Gang" => array(),
			"Leadership" => array(),
			"Radar" => array("color" => "red",),)
	),
  
	"mecha_chomper_glass" => array(
		"name" => "Mecha Chomper",
		"type" => "unit",
		"form" => "Glass",
		"class" => "Grunt",
		"faction" => "UberCorp International",
		"agenda" => "Collaborators",
		"energyType" => "Mechanical",
		"set" => "Big in Japan",
		"setColor" => "blue",
		"rarity" => 4,
		"speed" => 5,
		"defense" => 3,
		"brawl" => 2,
		"brawlBoost" => 1,
		"blast" => 1,
		"blastBoost" => 1,
		"blastRange" => "short",
		"cost" => 1,
		"abilities" => array(
			"fragile" => array(),
			"gang" => array("color" => "red", ),
			"jump" => array(),
			"radar" => array("color" => "red", ),)
	),

	"mecha_task_master_grunt" => array(
		"name" => "Mecha Task Master",
		"type" => "unit",
		"class" => "Grunt",
		"faction" => "UberCorp International",
		"agenda" => "Collaborators",
		"energyType" => "Mechanical",
		"set" => "Now",
		"rarity" => 2,
		"speed" => 4,
		"defense" => 2,
		"brawl" => 1,
		"brawlBoost" => 1,
		"blast" => 2,
		"blastRange" => "long",
		"cost" => 1,
		"abilities" => array(
			"Command" => array("color" => "red",),
			"Cargo" => array(),
			"Hover" => array(),)
	),
  
	"robo_brontox_grunt" => array(
		"name" => "Robo Brontox",
		"type" => "unit",
		"class" => "Grunt",
		"faction" => "UberCorp International",
		"agenda" => "Collaborators",
		"energyType" => "Mechanical",
		"set" => "Big in Japan",
		"rarity" => 1,
		"speed" => 4,
		"defense" => 4,
		"blast" => 1,
		"blastRange" => "long",
		"cost" => 1,
		"abilities" => array(
			"Beacon" => array(),
			"Amplify" => array(),)
	),
  
	"robo_brontox_elite" => array(
		"name" => "Robo Brontox",
		"type" => "unit",
		"class" => "Elite",
		"faction" => "UberCorp International",
		"agenda" => "Collaborators",
		"energyType" => "Mechanical",
		"set" => "Big in Japan",
		"rarity" => 3,
		"speed" => 4,
		"defense" => 4,
		"blast" => 1,
		"blastBoost" => 1,
		"blastRange" => "long",
		"cost" => 2,
		"abilities" => array(
			"Beacon" => array(),
			"Amplify" => array(),
			"Cloak" => array("color" => "red",),
			"Leadership" => array(),)
	),
  
	"robo_squix_grunt" => array(
		"name" => "Robo Squix",
		"type" => "unit",
		"class" => "Grunt",
		"faction" => "UberCorp International",
		"agenda" => "Collaborators",
		"energyType" => "Mechanical",
		"set" => "Now",
		"rarity" => 1,
		"speed" => 6,
		"defense" => 2,
		"brawl" => 2,
		"blast" => 1,
		"blastRange" => "short",
		"cost" => 1,
		"abilities" => array(
			"Explosion" => array("trigger" => "blast", ),
			"Anti-air" => array(),
			"Flight" => array(),)
	),
  
	"robo_squix_elite" => array(
		"name" => "Robo Squix",
		"type" => "unit",
		"class" => "Elite",
		"faction" => "UberCorp International",
		"agenda" => "Collaborators",
		"energyType" => "Mechanical",
		"set" => "Now",
		"rarity" => 3,
		"speed" => 6,
		"defense" => 2,
		"brawl" => 2,
		"brawlBoost" => 1,
		"blast" => 1,
		"blastBoost" => 1,
		"blastRange" => "short",
		"cost" => 2,
		"abilities" => array(
			"Explosion" => array("trigger" => "blast", ),
			"Anti-air" => array(),
			"Flight" => array(),
			"Leadership" => array(),)
	),
  
	"robo_squix_glass" => array(
		"name" => "Robo Squix",
		"type" => "unit",
		"form" => "Glass",
		"class" => "Grunt",
		"faction" => "UberCorp International",
		"agenda" => "Collaborators",
		"energyType" => "Mechanical",
		"set" => "Now",
		"setColor" => "blue",
		"rarity" => 4,
		"speed" => 6,
		"defense" => 2,
		"brawl" => 2,
		"brawlBoost" => 1,
		"blast" => 1,
		"blastBoost" => 1,
		"blastRange" => "short",
		"cost" => 1,
		"abilities" => array(
			"Explosion" => array("trigger" => "blast", ),
			"Anti-air" => array(),
			"Flight" => array(),
			"Fragile" => array(),)
	),

	"uci_mrv_grunt" => array(
		"name" => "UCI MRV",
		"type" => "unit",
		"class" => "Grunt",
		"faction" => "UberCorp International",
		"agenda" => "Collaborators",
		"energyType" => "Mechanical",
		"set" => "Now",
		"rarity" => 2,
		"speed" => 5,
		"defense" => 3,
		"cost" => 2,
		"abilities" => array(
			"Repair" => array(),
			"Amplify" => array(),
			"Force Field" => array("color" => "red",),
			"Hover" => array(),)
	),
